Cantera: ReactorBase Class Reference
ReactorBase Class Reference
Base class for stirred reactors.
#include <ReactorBase.h>
Public Member Functions
ReactorBase (const std::string &name="(none)")
virtual int type () const
std::string name () const
void setName (const std::string &name)
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
thermo_t & contents ()
return a reference to the contents.
const thermo_t & contents () const
doublereal residenceTime ()
int error (const std::string &msg) const
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
Methods to set up a simulation.
void setInitialVolume (doublereal vol)
Set the initial reactor volume.
void setThermoMgr (thermo_t &thermo)
Specify the mixture contained in the reactor.
void addInlet (FlowDevice &inlet)
void addOutlet (FlowDevice &outlet)
FlowDevice & inlet (size_t n=0)
FlowDevice & outlet (size_t n=0)
size_t nInlets ()
size_t nOutlets ()
size_t nWalls ()
void addWall (Wall &w, int lr)
Wall & wall (size_t n)
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
virtual void start ()
Solution components.
The values returned are those after the last call to advance or step.
doublereal volume () const
Returns the current volume of the reactor.
doublereal density () const
doublereal temperature () const
doublereal enthalpy_mass () const
doublereal intEnergy_mass () const
doublereal pressure () const
doublereal mass () const
const doublereal * massFractions () const
doublereal massFraction (size_t k) const
Protected Attributes
size_t m_nsp
Number of homogeneous species in the mixture.
thermo_t * m_thermo
doublereal m_vol
doublereal m_vol0
bool m_init
size_t m_nInlets
size_t m_nOutlets
bool m_open
doublereal m_enthalpy
doublereal m_intEnergy
doublereal m_pressure
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< Wall * > m_wall
vector_int m_lr
size_t m_nwalls
std::string m_name
double m_rho0
ReactorNet * m_net
The ReactorNet that this reactor is part of.
Private Member Functions
void tilt (const std::string &method="") const
Detailed Description
Base class for stirred reactors.
Allows using any substance model, with arbitrary inflow, outflow, heat loss/gain, surface chemistry, and volume change.
Definition at line 29 of file ReactorBase.h.
Member Function Documentation
void setInitialVolume (doublereal vol) inline
Set the initial reactor volume.
By default, the volume is 1.0 m^3.
Definition at line 57 of file ReactorBase.h.
void setThermoMgr (thermo_t & thermo)
Specify the mixture contained in the reactor.
Note that a pointer to this substance is stored, and as the integration proceeds, the state of the substance is modified.
Definition at line 32 of file ReactorBase.cpp.
References ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), ReactorBase::m_nsp, Phase::nSpecies(), ThermoPhase::pressure(), and Phase::saveState().
Referenced by Reactor::insert().
virtual void initialize (doublereal t0 = 0.0) inline virtual
Initialize the reactor.
Must be called after specifying the (and if necessary the inlet mixture) and before calling advance.
Reimplemented in Reactor, ConstPressureReactor, and FlowReactor.
Definition at line 92 of file ReactorBase.h.
void restoreState () inline
Set the state of the Phase object associated with this reactor to the reactor's current state.
Definition at line 102 of file ReactorBase.h.
References Phase::restoreState().
thermo_t& contents () inline
return a reference to the contents.
Definition at line 110 of file ReactorBase.h.
Referenced by FlowDevice::install().
doublereal volume () const inline
Returns the current volume of the reactor.
Returns
Return the volume in m**3
Definition at line 131 of file ReactorBase.h.
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
Definition at line 72 of file ReactorBase.cpp.
References ReactorBase::m_net.
void setNetwork (ReactorNet * net)
Set the ReactorNet that this reactor belongs to.
Definition at line 82 of file ReactorBase.cpp.
References ReactorBase::m_net.
Member Data Documentation
size_t m_nsp protected
Number of homogeneous species in the mixture.
Definition at line 175 of file ReactorBase.h.
Referenced by FlowReactor::initialize(), ConstPressureReactor::initialize(), Reactor::initialize(), ReactorBase::setThermoMgr(), ConstPressureReactor::updateState(), and Reactor::updateState().
ReactorNet* m_net protected
The ReactorNet that this reactor is part of.
Definition at line 194 of file ReactorBase.h.
Referenced by ReactorBase::network(), and ReactorBase::setNetwork().
The documentation for this class was generated from the following files:
ReactorBase.h
ReactorBase.cpp