Cantera: IdealSolnGasVPSS Class Reference
IdealSolnGasVPSS Class Reference
Thermodynamic Properties
An ideal solution or an ideal gas approximation of a phase.
#include <IdealSolnGasVPSS.h>
Public Member Functions
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
virtual void setState_TP (doublereal T, doublereal pres)
Set the temperature and pressure at the same time.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Protected Attributes
int m_idealGas
boolean indicating what ideal solution this is
int m_formGC
form of the generalized concentrations
vector_fp m_pp
Temporary storage - length = m_kk.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Constructors and Duplicators for IdealSolnGasVPSS
IdealSolnGasVPSS ()
Constructor.
IdealSolnGasVPSS (const std::string &infile, std::string id="")
Create an object from an XML input file.
IdealSolnGasVPSS (const IdealSolnGasVPSS &)
Copy Constructor.
IdealSolnGasVPSS & operator= (const IdealSolnGasVPSS &)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine.
Utilities (IdealSolnGasVPSS)
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties
doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
doublereal entropy_mole () const
Molar entropy. Units: J/kmol/K.
doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Mechanical Properties
void setPressure (doublereal p)
Set the pressure in the fluid.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Partial Molar Properties of the Solution
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Get the species partial molar entropies. Units: J/kmol/K.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Get the species partial molar enthalpies. Units: J/kmol.
virtual void getPartialMolarCp (doublereal *cpbar) const
Get the partial molar heat capacities Units: J/kmol/K.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Get the species partial molar volumes. Units: m^3/kmol.
Initialization Methods - For Internal use
virtual void setParametersFromXML (const XML_Node &thermoNode)
Set equation of state parameter values from XML entries.
virtual void initThermo ()
void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Initialize a ThermoPhase object, potentially reading activity coefficient information from an XML database.
void initLengths ()
Additional Inherited Members
Protected Member Functions inherited from VPStandardStateTP
virtual void _updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
const vector_fp & Gibbs_RT_ref () const
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Detailed Description
An ideal solution or an ideal gas approximation of a phase.
Uses variable pressure standard state methods for calculating thermodynamic properties.
Definition at line 43 of file IdealSolnGasVPSS.h.
Constructor & Destructor Documentation
IdealSolnGasVPSS ()
Constructor.
Definition at line 27 of file IdealSolnGasVPSS.cpp.
Referenced by IdealSolnGasVPSS::duplMyselfAsThermoPhase().
IdealSolnGasVPSS (const std::string & infile, std::string id = "")
Create an object from an XML input file.
Definition at line 34 of file IdealSolnGasVPSS.cpp.
References Cantera::get_XML_File(), Cantera::get_XML_NameID(), and Cantera::importPhase().
IdealSolnGasVPSS (const IdealSolnGasVPSS & b)
Copy Constructor.
Definition at line 51 of file IdealSolnGasVPSS.cpp.
Member Function Documentation
IdealSolnGasVPSS & operator= (const IdealSolnGasVPSS & b)
Assignment operator.
Definition at line 60 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_formGC, IdealSolnGasVPSS::m_idealGas, and VPStandardStateTP::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine.
Reimplemented from VPStandardStateTP.
Definition at line 77 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::IdealSolnGasVPSS().
int eosType () const virtual
Equation of state type flag.
The base class returns zero. Subclasses should define this to return a unique non-zero value. Constants defined for this purpose are listed in mix_defs.h.
Reimplemented from VPStandardStateTP.
Definition at line 82 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_idealGas.
Referenced by IdealSolnGasVPSS::getUnitsStandardConc().
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 94 of file IdealSolnGasVPSS.cpp.
References DATA_PTR, VPSSMgr::enthalpy_RT(), Cantera::GasConstant, VPStandardStateTP::m_VPSS_ptr, Phase::mean_X(), Phase::temperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::gibbs_mole(), and IdealSolnGasVPSS::intEnergy_mole().
doublereal intEnergy_mole () const virtual
Molar internal energy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 102 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::enthalpy_mole(), Phase::molarDensity(), and VPStandardStateTP::pressure().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 109 of file IdealSolnGasVPSS.cpp.
References DATA_PTR, VPSSMgr::entropy_R(), Cantera::GasConstant, VPStandardStateTP::m_VPSS_ptr, Phase::mean_X(), Phase::sum_xlogx(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::gibbs_mole().
doublereal gibbs_mole () const virtual
Molar Gibbs function. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 117 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::enthalpy_mole(), IdealSolnGasVPSS::entropy_mole(), and Phase::temperature().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 122 of file IdealSolnGasVPSS.cpp.
References VPSSMgr::cp_R(), DATA_PTR, Cantera::GasConstant, VPStandardStateTP::m_VPSS_ptr, Phase::mean_X(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealSolnGasVPSS::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 129 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::cp_mole(), and Cantera::GasConstant.
void setPressure (doublereal p) virtual
Set the pressure in the fluid.
Parameters
p pressure in pascals.
Reimplemented from VPStandardStateTP.
Definition at line 134 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::calcDensity(), VPStandardStateTP::m_Pcurrent, and VPStandardStateTP::updateStandardStateThermo().
doublereal isothermalCompressibility () const virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
Reimplemented from ThermoPhase.
Definition at line 163 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_idealGas, and VPStandardStateTP::m_Pcurrent.
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the species standard state molar volumes. The species molar volumes may be functions of temperature and pressure.
Reimplemented from VPStandardStateTP.
Definition at line 141 of file IdealSolnGasVPSS.cpp.
References Cantera::dot(), Cantera::GasConstant, VPSSMgr::getStandardVolumes(), IdealSolnGasVPSS::m_idealGas, VPStandardStateTP::m_Pcurrent, VPStandardStateTP::m_VPSS_ptr, Phase::meanMolecularWeight(), Phase::moleFractdivMMW(), Phase::setDensity(), and Phase::temperature().
Referenced by IdealSolnGasVPSS::setPressure().
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations.
\(C^a_k\) are defined such that \(a_k = C^a_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. Note that they may or may not have units of concentration — they might be partial pressures, mole fractions, or surface coverages, for example.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 174 of file IdealSolnGasVPSS.cpp.
References Phase::getConcentrations(), VPSSMgr::getStandardVolumes(), IdealSolnGasVPSS::m_formGC, IdealSolnGasVPSS::m_idealGas, Phase::m_kk, VPStandardStateTP::m_VPSS_ptr, and Phase::moleFraction().
doublereal standardConcentration (size_t k = 0) const virtual
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity. In many cases, this quantity will be the same for all species in a phase. Since the activity for an ideal gas mixture is simply the mole fraction, for an ideal gas \(C^0_k = P/\hat R T \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 200 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPSSMgr::getStandardVolumes(), IdealSolnGasVPSS::m_formGC, IdealSolnGasVPSS::m_idealGas, VPStandardStateTP::m_VPSS_ptr, VPStandardStateTP::pressure(), and Phase::temperature().
Referenced by IdealSolnGasVPSS::logStandardConc().
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species.
Parameters
k index of the species. (defaults to zero)
Reimplemented from ThermoPhase.
Definition at line 220 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::standardConcentration().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations.
Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
The base ThermoPhase class assigns the default quantities of (kmol/m3) for all species. Inherited classes are responsible for overriding the default values if necessary.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented from ThermoPhase.
Definition at line 226 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::eosType(), and Phase::nDim().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For ideal gases, the activity coefficients are all equal to one.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 257 of file IdealSolnGasVPSS.cpp.
References Phase::m_kk.
void getChemPotentials_RT (doublereal * mu) const virtual
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
\(\mu_k / \hat R T \). Units: unitless
We close the loop on this function, here, calling getChemPotentials() and then dividing by RT. No need for child classes to handle.
Parameters
mu Output vector of non-dimensional species chemical potentials Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 268 of file IdealSolnGasVPSS.cpp.
References ThermoPhase::_RT(), IdealSolnGasVPSS::getChemPotentials(), and Phase::m_kk.
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 277 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), Phase::m_kk, Phase::moleFraction(), Cantera::SmallNumber, and Phase::temperature().
Referenced by IdealSolnGasVPSS::getChemPotentials_RT().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 288 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, Cantera::scale(), and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Get the species partial molar entropies. Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 295 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), Phase::m_kk, Phase::moleFraction(), Cantera::scale(), and Cantera::SmallNumber.
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Get the species partial molar enthalpies. Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 306 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getIntEnergy_RT(), Phase::m_kk, Cantera::scale(), and Phase::temperature().
void getPartialMolarCp (doublereal * cpbar) const virtual
Get the partial molar heat capacities Units: J/kmol/K.
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 313 of file IdealSolnGasVPSS.cpp.
References Cantera::GasConstant, VPStandardStateTP::getCp_R(), Phase::m_kk, and Cantera::scale().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Get the species partial molar volumes. Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 320 of file IdealSolnGasVPSS.cpp.
References VPStandardStateTP::getStandardVolumes().
void setParametersFromXML (const XML_Node & thermoNode) virtual
Set equation of state parameter values from XML entries.
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
This method is called by function importPhase in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
Parameters
thermoNode An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from VPStandardStateTP.
Definition at line 422 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::m_idealGas, and VPStandardStateTP::setParametersFromXML().
void initThermo () virtual
Initialize the object
This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
See Also
importCTML.cpp
Reimplemented from VPStandardStateTP.
Definition at line 325 of file IdealSolnGasVPSS.cpp.
References IdealSolnGasVPSS::initLengths(), and VPStandardStateTP::initThermo().
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from ThermoPhase.
Definition at line 331 of file IdealSolnGasVPSS.cpp.
References VPSSMgr::Gibbs_RT_ref(), Phase::m_kk, IdealSolnGasVPSS::m_pp, VPStandardStateTP::m_VPSS_ptr, VPSSMgr::refPressure(), ThermoPhase::setState_PX(), and VPStandardStateTP::updateStandardStateThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Initialize a ThermoPhase object, potentially reading activity coefficient information from an XML database.
This routine initializes the lengths in the current object and then calls the parent routine. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase().
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 370 of file IdealSolnGasVPSS.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), IdealSolnGasVPSS::initLengths(), VPStandardStateTP::initThermoXML(), Cantera::lowercase(), IdealSolnGasVPSS::m_formGC, and IdealSolnGasVPSS::m_idealGas.
void initLengths () private
Initialize the internal lengths in this object.
Note this is not a virtual function and only handles this object
Definition at line 364 of file IdealSolnGasVPSS.cpp.
References Phase::m_kk, IdealSolnGasVPSS::m_pp, and Phase::nSpecies().
Referenced by IdealSolnGasVPSS::initThermo(), and IdealSolnGasVPSS::initThermoXML().
Member Data Documentation
int m_idealGas protected
boolean indicating what ideal solution this is
1 = ideal gas
0 = ideal soln
Definition at line 388 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::calcDensity(), IdealSolnGasVPSS::eosType(), IdealSolnGasVPSS::getActivityConcentrations(), IdealSolnGasVPSS::initThermoXML(), IdealSolnGasVPSS::isothermalCompressibility(), IdealSolnGasVPSS::operator=(), IdealSolnGasVPSS::setParametersFromXML(), and IdealSolnGasVPSS::standardConcentration().
int m_formGC protected
form of the generalized concentrations
0 unity
1 1/V_k
2 1/V_0
Definition at line 396 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::getActivityConcentrations(), IdealSolnGasVPSS::initThermoXML(), IdealSolnGasVPSS::operator=(), and IdealSolnGasVPSS::standardConcentration().
vector_fp m_pp protected
Temporary storage - length = m_kk.
Definition at line 399 of file IdealSolnGasVPSS.h.
Referenced by IdealSolnGasVPSS::initLengths(), and IdealSolnGasVPSS::setToEquilState().
The documentation for this class was generated from the following files:
IdealSolnGasVPSS.h
IdealSolnGasVPSS.cpp