Cantera: SolidTransport Class Reference
SolidTransport Class Reference
Class SolidTransport implements transport properties for solids.
#include <SolidTransport.h>
Public Member Functions
SolidTransport ()
Default constructor.
SolidTransport (const SolidTransport &right)
Copy Constructor.
virtual ~SolidTransport ()
Destructor.
SolidTransport & operator= (const SolidTransport &right)
Assignment operator.
virtual Transport * duplMyselfAsTransport () const
Duplication routine for objects which inherit from Transport.
virtual int model () const
Transport model.
virtual doublereal ionConductivity ()
The ionic conducitivity in 1/ohm/m.
virtual doublereal thermalConductivity ()
Returns the mixture thermal conductivity in W/m/K.
virtual doublereal electricalConductivity ()
The electrical conductivity (Siemens/m).
virtual doublereal defectDiffusivity ()
The diffusivity of defects in the solid (m^2/s).
virtual doublereal defectActivity ()
The activity of defects in the solid.
virtual void getMixDiffCoeffs (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMobilities (doublereal *const mobil)
Compute the electrical mobilities of the species from the diffusion coefficients, using the Einstein relation.
virtual void setParameters (const int n, const int k, const doublereal *const p)
Set model parameters for derived classes.
Public Member Functions inherited from Transport
Transport (thermo_t *thermo=0, size_t ndim=1)
Constructor.
virtual ~Transport ()
Destructor.
Transport (const Transport &right)
Copy Constructor for the Transport object.
Transport & operator= (const Transport &right)
Assignment operator.
thermo_t & thermo ()
Phase object.
bool ready ()
Returns true if the transport manager is ready for use.
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
virtual doublereal getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_V, doublereal *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the specified solution averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesFluxesES (size_t ndim, const doublereal *grad_T, size_t ldx, const doublereal *grad_X, size_t ldf, const doublereal *grad_Phi, doublereal *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_Phi, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const cfluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const doublereal *state1, const doublereal *state2, doublereal delta, doublereal *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return a vector of Thermal diffusion coefficients [kg/m/sec].
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void getMixDiffCoeffsMole (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
virtual void getMixDiffCoeffsMass (doublereal *const d)
Returns a vector of mixture averaged diffusion coefficients.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
virtual doublereal viscosity ()
The viscosity in Pa-s.
virtual void getSpeciesViscosities (doublereal *const visc)
Returns the pure species viscosities.
virtual doublereal bulkViscosity ()
The bulk viscosity in Pa-s.
virtual void getSpeciesIonConductivity (doublereal *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void selfDiffusion (doublereal *const selfDiff)
Returns the self diffusion coefficients of the species in the phase.
virtual void getSpeciesSelfDiffusion (double **selfDiff)
Returns the pure species self diffusion in solution of each species.
virtual void getFluidMobilities (doublereal *const mobil_f)
Get the fluid mobilities (s kmol/kg).
virtual void setThermo (thermo_t &thermo)
Specifies the ThermPhase object.
Protected Member Functions
virtual bool initSolid (SolidTransportData &tr)
Initialize the transport object.
Protected Member Functions inherited from Transport
virtual bool initGas (GasTransportParams &tr)
Called by TransportFactory to set parameters.
virtual bool initLiquid (LiquidTransportParams &tr)
Called by TransportFactory to set parameters.
void finalize ()
Enable the transport object for use.
Private Attributes
LTPspecies * m_ionConductivity
Model type for the ionic conductivity.
LTPspecies * m_thermalConductivity
Model type for the thermal conductivity.
LTPspecies * m_electConductivity
Model type for the electrical conductivity.
LTPspecies * m_defectDiffusivity
Model type for the defectDiffusivity – or more like a defect diffusivity in the context of the solid phase.
LTPspecies * m_defectActivity
Model type for the defectActivity.
size_t m_nmobile
number of mobile species
vector_fp m_Adiff
Coefficient for the diffusivity of species within a solid.
vector_fp m_Ndiff
Temperature power coefficient for the diffusivity of species in a solid.
vector_fp m_Ediff
Arrhenius factor for the species diffusivities of a solid.
vector_int m_sp
Index of mobile species to global species.
doublereal m_Alam
Coefficient for the thermal conductivity of a solid.
doublereal m_Nlam
Temperature power coefficient for the thermal conductivity of a solid.
doublereal m_Elam
Arrhenius factor for the thermal conductivity of a solid.
vector_fp m_work
extra fp array of length nSpecies()
Friends
class TransportFactory
Additional Inherited Members
Protected Attributes inherited from Transport
thermo_t * m_thermo
pointer to the object representing the phase
bool m_ready
true if finalize has been called
size_t m_nsp
Number of species.
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis
Velocity basis from which diffusion velocities are computed.
Detailed Description
Class SolidTransport implements transport properties for solids.
Definition at line 28 of file SolidTransport.h.
Constructor & Destructor Documentation
SolidTransport ()
Default constructor.
Definition at line 24 of file SolidTransport.cpp.
Referenced by SolidTransport::duplMyselfAsTransport().
SolidTransport (const SolidTransport & right)
Copy Constructor.
Parameters
right Object to be copied
Definition at line 41 of file SolidTransport.cpp.
~SolidTransport () virtual
Destructor.
Definition at line 37 of file SolidTransport.cpp.
Member Function Documentation
SolidTransport & operator= (const SolidTransport & right)
Assignment operator.
This is NOT a virtual function.
Parameters
right Reference to Transport object to be copied into the current one.
Definition at line 59 of file SolidTransport.cpp.
References SolidTransport::m_Adiff, SolidTransport::m_Alam, SolidTransport::m_Ediff, SolidTransport::m_Elam, SolidTransport::m_Ndiff, SolidTransport::m_Nlam, SolidTransport::m_nmobile, SolidTransport::m_sp, and Transport::operator=().
Transport * duplMyselfAsTransport () const virtual
Duplication routine for objects which inherit from Transport.
This virtual routine can be used to duplicate Transport objects inherited from Transport even if the application only has a pointer to Transport to work with.
These routines are basically wrappers around the derived copy constructor.
Reimplemented from Transport.
Definition at line 79 of file SolidTransport.cpp.
References SolidTransport::SolidTransport().
virtual int model () const inline virtual
Transport model.
The transport model is the set of equations used to compute the transport properties. This virtual method returns an integer flag that identifies the transport model implemented. The base class returns 0.
Reimplemented from Transport.
Definition at line 66 of file SolidTransport.h.
doublereal ionConductivity () virtual
The ionic conducitivity in 1/ohm/m.
Reimplemented from Transport.
Definition at line 164 of file SolidTransport.cpp.
References LTPspecies::getSpeciesTransProp(), and SolidTransport::m_ionConductivity.
doublereal thermalConductivity () virtual
Returns the mixture thermal conductivity in W/m/K.
Units are in W / m K or equivalently kg m / s3 K
Returns
returns thermal conductivity in W/m/K.
Reimplemented from Transport.
Definition at line 210 of file SolidTransport.cpp.
References LTPspecies::getSpeciesTransProp(), SolidTransport::m_Alam, SolidTransport::m_Elam, SolidTransport::m_Nlam, SolidTransport::m_thermalConductivity, Transport::m_thermo, and Phase::temperature().
doublereal electricalConductivity () virtual
The electrical conductivity (Siemens/m).
Reimplemented from Transport.
Definition at line 181 of file SolidTransport.cpp.
References Phase::charge(), SolidTransport::getMobilities(), LTPspecies::getSpeciesTransProp(), SolidTransport::m_electConductivity, SolidTransport::m_nmobile, Transport::m_thermo, SolidTransport::m_work, Phase::molarDensity(), Phase::moleFraction(), and Phase::nSpecies().
doublereal defectDiffusivity () virtual
The diffusivity of defects in the solid (m^2/s).
Definition at line 231 of file SolidTransport.cpp.
References LTPspecies::getSpeciesTransProp(), and SolidTransport::m_defectDiffusivity.
doublereal defectActivity () virtual
The activity of defects in the solid.
At some point this should be variable and the diffusion coefficient should depend on it...
Definition at line 246 of file SolidTransport.cpp.
References LTPspecies::getSpeciesTransProp(), and SolidTransport::m_defectActivity.
void getMixDiffCoeffs (doublereal *const d) virtual
Returns a vector of mixture averaged diffusion coefficients.
Mixture-averaged diffusion coefficients [m^2/s]. If the
transport manager implements a mixture-averaged diffusion model, then this method returns the array of mixture-averaged diffusion coefficients. Otherwise it throws an exception.
Parameters
d Return vector of mixture averaged diffusion coefficients Units = m2/s. Length = n_sp
Reimplemented from Transport.
Definition at line 278 of file SolidTransport.cpp.
References Transport::m_thermo, and Phase::nSpecies().
Referenced by SolidTransport::getMobilities().
void getMobilities (doublereal *const mobil) virtual
Compute the electrical mobilities of the species from the diffusion coefficients, using the Einstein relation.
Frequently, but not always, the mobility is calculated from the diffusion coefficient using the Einstein relation
\[ \mu^e_k = \frac{F D_k}{R T} \]
units (m^2/V/s).
Parameters
mobil Returns the mobilities of the species in array mobil_e. The array must be dimensioned at least as large as the number of species.
Reimplemented from Transport.
Definition at line 256 of file SolidTransport.cpp.
References Cantera::Boltzmann, SolidTransport::getMixDiffCoeffs(), Transport::m_thermo, Phase::nSpecies(), and Phase::temperature().
Referenced by SolidTransport::electricalConductivity().
void setParameters (const int n, const int k, const doublereal *const p) virtual
Set model parameters for derived classes.
This method may be derived in subclasses to set model-specific parameters. The primary use of this class is to set parameters while in the middle of a calculation without actually having to dynamically cast the base Transport pointer.
Parameters
type Specifies the type of parameters to set 0 : Diffusion coefficient 1 : Thermal Conductivity The rest are currently unused.
k Species index to set the parameters on
p Vector of parameters. The length of the vector varies with the parameterization
Reimplemented from Transport.
Definition at line 126 of file SolidTransport.cpp.
References SolidTransport::m_Adiff, SolidTransport::m_Alam, SolidTransport::m_Ediff, SolidTransport::m_Elam, SolidTransport::m_Ndiff, SolidTransport::m_Nlam, SolidTransport::m_nmobile, SolidTransport::m_sp, Transport::m_thermo, SolidTransport::m_work, and Phase::nSpecies().
bool initSolid (SolidTransportData & tr) protected virtual
Initialize the transport object.
Here we change all of the internal dimensions to be sufficient. We get the object ready to do property evaluations. A lot of the input required to do property evaluations is contained in the SolidTransportParams class that is filled in TransportFactory.
Parameters
tr Transport parameters for all of the species in the phase.
Reimplemented from Transport.
Definition at line 96 of file SolidTransport.cpp.
References SolidTransportData::defectActivity, SolidTransportData::defectDiffusivity, SolidTransportData::electConductivity, SolidTransportData::ionConductivity, SolidTransport::m_defectActivity, SolidTransport::m_defectDiffusivity, SolidTransport::m_electConductivity, SolidTransport::m_ionConductivity, SolidTransport::m_thermalConductivity, Transport::m_thermo, SolidTransportData::thermalConductivity, and TransportParams::thermo.
Member Data Documentation
LTPspecies* m_ionConductivity private
Model type for the ionic conductivity.
shallow pointer that should be zero during destructor
Definition at line 165 of file SolidTransport.h.
Referenced by SolidTransport::initSolid(), and SolidTransport::ionConductivity().
LTPspecies* m_thermalConductivity private
Model type for the thermal conductivity.
shallow pointer that should be zero during destructor
Definition at line 171 of file SolidTransport.h.
Referenced by SolidTransport::initSolid(), and SolidTransport::thermalConductivity().
LTPspecies* m_electConductivity private
Model type for the electrical conductivity.
shallow pointer that should be zero during destructor
Definition at line 177 of file SolidTransport.h.
Referenced by SolidTransport::electricalConductivity(), and SolidTransport::initSolid().
LTPspecies* m_defectDiffusivity private
Model type for the defectDiffusivity – or more like a defect diffusivity in the context of the solid phase.
shallow pointer that should be zero during destructor
Definition at line 183 of file SolidTransport.h.
Referenced by SolidTransport::defectDiffusivity(), and SolidTransport::initSolid().
LTPspecies* m_defectActivity private
Model type for the defectActivity.
shallow pointer that should be zero during destructor
Definition at line 189 of file SolidTransport.h.
Referenced by SolidTransport::defectActivity(), and SolidTransport::initSolid().
size_t m_nmobile private
number of mobile species
This is equal to the
Definition at line 195 of file SolidTransport.h.
Referenced by SolidTransport::electricalConductivity(), SolidTransport::operator=(), and SolidTransport::setParameters().
vector_fp m_Adiff private
Coefficient for the diffusivity of species within a solid.
This is with respect to the lattice units = m**2 / s vector of length m_nmobile
Definition at line 203 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), and SolidTransport::setParameters().
vector_fp m_Ndiff private
Temperature power coefficient for the diffusivity of species in a solid.
vector of length m_nmobile
Definition at line 209 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), and SolidTransport::setParameters().
vector_fp m_Ediff private
Arrhenius factor for the species diffusivities of a solid.
units = temperature vector of length m_nmobile
Definition at line 216 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), and SolidTransport::setParameters().
vector_int m_sp private
Index of mobile species to global species.
vector of length m_nmobile
Definition at line 222 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), and SolidTransport::setParameters().
doublereal m_Alam private
Coefficient for the thermal conductivity of a solid.
units = kg m / s3 /K = W/m/K
Definition at line 228 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), SolidTransport::setParameters(), and SolidTransport::thermalConductivity().
doublereal m_Nlam private
Temperature power coefficient for the thermal conductivity of a solid.
Definition at line 231 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), SolidTransport::setParameters(), and SolidTransport::thermalConductivity().
doublereal m_Elam private
Arrhenius factor for the thermal conductivity of a solid.
units = temperature
Definition at line 237 of file SolidTransport.h.
Referenced by SolidTransport::operator=(), SolidTransport::setParameters(), and SolidTransport::thermalConductivity().
vector_fp m_work private
extra fp array of length nSpecies()
Definition at line 240 of file SolidTransport.h.
Referenced by SolidTransport::electricalConductivity(), and SolidTransport::setParameters().
The documentation for this class was generated from the following files:
SolidTransport.h
SolidTransport.cpp