Cantera: MolarityIonicVPSSTP Class Reference
MolarityIonicVPSSTP Class Reference
Thermodynamic Properties
#include <MolarityIonicVPSSTP.h>
Public Member Functions
MolarityIonicVPSSTP ()
Constructor.
MolarityIonicVPSSTP (const std::string &inputFile, const std::string &id="")
Construct and initialize a MolarityIonicVPSSTP ThermoPhase object directly from an XML input file.
MolarityIonicVPSSTP (XML_Node &phaseRef, const std::string &id="")
Construct and initialize a MolarityIonicVPSSTP ThermoPhase object directly from an XML database.
MolarityIonicVPSSTP (const MolarityIonicVPSSTP &b)
Copy constructor.
MolarityIonicVPSSTP & operator= (const MolarityIonicVPSSTP &b)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
virtual void calcPseudoBinaryMoleFractions () const
Calculate pseudo binary mole fractions.
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
Utilities
virtual int eosType () const
Equation of state type flag.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
Initialization
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
virtual void initThermo ()
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Public Member Functions inherited from GibbsExcessVPSSTP
GibbsExcessVPSSTP ()
GibbsExcessVPSSTP (const GibbsExcessVPSSTP &b)
Copy constructor.
GibbsExcessVPSSTP & operator= (const GibbsExcessVPSSTP &b)
Assignment operator.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getdlnActCoeffdT (doublereal *dlnActCoeffdT) const
Get the array of temperature derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnX (doublereal *dlnActCoeffdlnX) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual const vector_fp & getPartialMolarVolumes () const
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Protected Attributes
int PBType_
size_t numPBSpecies_
Number of pseudo binary species.
size_t indexSpecialSpecies_
index of special species
std::vector< doublereal > PBMoleFractions_
std::vector< size_t > cationList_
Vector of cation indices in the mixture.
size_t numCationSpecies_
Number of cations in the mixture.
std::vector< size_t > anionList_
size_t numAnionSpecies_
std::vector< size_t > passThroughList_
size_t numPassThroughSpecies_
size_t neutralPBindexStart
std::vector< doublereal > moleFractionsTmp_
Protected Attributes inherited from GibbsExcessVPSSTP
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
std::vector< doublereal > lnActCoeff_Scaled_
Storage for the current values of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdT_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > d2lnActCoeffdT2_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnN_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnX_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Array2D dlnActCoeffdlnN_
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
std::vector< doublereal > m_pp
Temporary storage space that is fair game.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void initLengths ()
Initialize lengths of local variables after all species have been identified.
void readXMLBinarySpecies (XML_Node &xmlBinarySpecies)
Process an XML node called "binaryNeutralSpeciesParameters".
void s_update_lnActCoeff () const
Update the activity coefficients.
void s_update_dlnActCoeff_dT () const
Update the derivative of the log of the activity coefficients wrt T.
void s_update_dlnActCoeff_dX_ () const
Internal routine that calculates the derivative of the activity coefficients wrt the mole fractions.
doublereal err (const std::string &msg) const
Error function.
Additional Inherited Members
Protected Member Functions inherited from GibbsExcessVPSSTP
double checkMFSum (const doublereal *const x) const
utility routine to check mole fraction sum
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Detailed Description
MolarityIonicVPSSTP is a derived class of GibbsExcessVPSSTP that handles variable pressure standard state methods for calculating thermodynamic properties that are further based on expressing the Excess Gibbs free energy as a function of the mole fractions (or pseudo mole fractions) of the constituents. This category is the workhorse for describing ionic systems which are not on the molality scale.
This class adds additional functions onto the ThermoPhase interface that handles the calculation of the excess Gibbs free energy. The ThermoPhase class includes a member function, ThermoPhase::activityConvention() that indicates which convention the activities are based on. The default is to assume activities are based on the molar convention. That default is used here.
All of the Excess Gibbs free energy formulations in this area employ symmetrical formulations.
This layer will massage the mole fraction vector to implement cation and anion based mole numbers in an optional manner, such that it is expected that there exists a charge balance at all times. One of the ions must be a "special ion" in the sense that its' thermodynamic functions are set to zero, and the thermo functions of all other ions are based on a valuation relative to that special ion.
Definition at line 58 of file MolarityIonicVPSSTP.h.
Constructor & Destructor Documentation
MolarityIonicVPSSTP ()
Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements.xml file. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 30 of file MolarityIonicVPSSTP.cpp.
Referenced by MolarityIonicVPSSTP::duplMyselfAsThermoPhase().
MolarityIonicVPSSTP (const std::string & inputFile, const std::string & id = "")
Construct and initialize a MolarityIonicVPSSTP ThermoPhase object directly from an XML input file.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 42 of file MolarityIonicVPSSTP.cpp.
References ThermoPhase::initThermoFile().
MolarityIonicVPSSTP (XML_Node & phaseRef, const std::string & id = "")
Construct and initialize a MolarityIonicVPSSTP ThermoPhase object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 56 of file MolarityIonicVPSSTP.cpp.
References Cantera::findXMLPhase(), and Cantera::importPhase().
MolarityIonicVPSSTP (const MolarityIonicVPSSTP & b)
Copy constructor.
Parameters
b class to be copied
Definition at line 70 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::operator=().
Member Function Documentation
MolarityIonicVPSSTP & operator= (const MolarityIonicVPSSTP & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 84 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::cationList_, MolarityIonicVPSSTP::indexSpecialSpecies_, MolarityIonicVPSSTP::numCationSpecies_, MolarityIonicVPSSTP::numPBSpecies_, GibbsExcessVPSSTP::operator=(), and MolarityIonicVPSSTP::PBType_.
Referenced by MolarityIonicVPSSTP::MolarityIonicVPSSTP(), and MixedSolventElectrolyte::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate thermophase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from GibbsExcessVPSSTP.
Reimplemented in MixedSolventElectrolyte.
Definition at line 107 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::MolarityIonicVPSSTP().
int eosType () const virtual
Equation of state type flag.
The ThermoPhase base class returns zero. Subclasses should define this to return a unique non-zero value. Known constants defined for this purpose are listed in mix_defs.h. The MolalityVPSSTP class also returns zero, as it is a non-complete class.
Reimplemented from GibbsExcessVPSSTP.
Reimplemented in MixedSolventElectrolyte.
Definition at line 116 of file MolarityIonicVPSSTP.cpp.
Referenced by MolarityIonicVPSSTP::err().
void getLnActivityCoefficients (doublereal * lnac) const virtual
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
lnac Output vector of ln activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 125 of file MolarityIonicVPSSTP.cpp.
References GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, and MolarityIonicVPSSTP::s_update_lnActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Reimplemented in MixedSolventElectrolyte.
Definition at line 140 of file MolarityIonicVPSSTP.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, MolarityIonicVPSSTP::s_update_lnActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by MolarityIonicVPSSTP::getElectrochemPotentials(), and MolarityIonicVPSSTP::report().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk.
Definition at line 164 of file MolarityIonicVPSSTP.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), MolarityIonicVPSSTP::getChemPotentials(), and Phase::m_kk.
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
Parameters
hbar Vector of returned partial molar enthalpies (length m_kk, units = J/kmol)
Reimplemented from ThermoPhase.
Reimplemented in MixedSolventElectrolyte.
Definition at line 173 of file MolarityIonicVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, MolarityIonicVPSSTP::s_update_dlnActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), and Phase::temperature().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
Parameters
sbar Vector of returned partial molar entropies (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Reimplemented in MixedSolventElectrolyte.
Definition at line 224 of file MolarityIonicVPSSTP.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, MolarityIonicVPSSTP::s_update_dlnActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), Cantera::SmallNumber, and Phase::temperature().
void getPartialMolarCp (doublereal * cpbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ ??????????????? \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} ??????????????? \]
Parameters
cpbar Vector of returned partial molar heat capacities (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Reimplemented in MixedSolventElectrolyte.
Definition at line 199 of file MolarityIonicVPSSTP.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getCp_R(), Phase::m_kk, MolarityIonicVPSSTP::s_update_dlnActCoeff_dT(), MolarityIonicVPSSTP::s_update_lnActCoeff(), and Phase::temperature().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Frequently, for this class of thermodynamics representations, the excess Volume due to mixing is zero. Here, we set it as a default. It may be overridden in derived classes.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from GibbsExcessVPSSTP.
Reimplemented in MixedSolventElectrolyte.
Definition at line 251 of file MolarityIonicVPSSTP.cpp.
References VPStandardStateTP::getStandardVolumes(), and Phase::m_kk.
void calcPseudoBinaryMoleFractions () const virtual
Calculate pseudo binary mole fractions.
Definition at line 262 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::cationList_, Phase::m_kk, Phase::m_speciesCharge, GibbsExcessVPSSTP::moleFractions_, Cantera::npos, MolarityIonicVPSSTP::numCationSpecies_, MolarityIonicVPSSTP::numPBSpecies_, and MolarityIonicVPSSTP::PBType_.
void initThermo () virtual
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from GibbsExcessVPSSTP.
Reimplemented in MixedSolventElectrolyte.
Definition at line 372 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::cationList_, MolarityIonicVPSSTP::initLengths(), GibbsExcessVPSSTP::initThermo(), Phase::m_kk, Phase::m_speciesCharge, MolarityIonicVPSSTP::numCationSpecies_, MolarityIonicVPSSTP::numPBSpecies_, and MolarityIonicVPSSTP::PBType_.
Referenced by MixedSolventElectrolyte::initThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 416 of file MolarityIonicVPSSTP.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), XML_Node::id(), VPStandardStateTP::initThermoXML(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), MolarityIonicVPSSTP::readXMLBinarySpecies(), and Phase::size().
Referenced by MixedSolventElectrolyte::initThermoXML().
std::string report (bool show_thermo = true) const virtual
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented from ThermoPhase.
Definition at line 485 of file MolarityIonicVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), GibbsExcessVPSSTP::getActivities(), MolarityIonicVPSSTP::getChemPotentials(), Phase::getMoleFractions(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), VPStandardStateTP::pressure(), CanteraError::save(), and Phase::temperature().
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 410 of file MolarityIonicVPSSTP.cpp.
References Phase::m_kk, and Phase::nSpecies().
Referenced by MolarityIonicVPSSTP::initThermo().
void readXMLBinarySpecies (XML_Node & xmlBinarySpecies) private
Process an XML node called "binaryNeutralSpeciesParameters".
This node contains all of the parameters necessary to describe the Redlich-Kister model for a particular binary interaction. This function reads the XML file and writes the coefficients it finds to an internal data structures.
Parameters
xmlBinarySpecies Reference to the XML_Node named "binaryNeutralSpeciesParameters" containing the binary interaction
Definition at line 479 of file MolarityIonicVPSSTP.cpp.
References XML_Node::name().
Referenced by MolarityIonicVPSSTP::initThermoXML().
void s_update_lnActCoeff () const private
Update the activity coefficients.
This function will be called to update the internally stored natural logarithm of the activity coefficients
Definition at line 343 of file MolarityIonicVPSSTP.cpp.
References GibbsExcessVPSSTP::lnActCoeff_Scaled_, and Phase::m_kk.
Referenced by MolarityIonicVPSSTP::getChemPotentials(), MolarityIonicVPSSTP::getLnActivityCoefficients(), MolarityIonicVPSSTP::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), and MolarityIonicVPSSTP::getPartialMolarEntropies().
void s_update_dlnActCoeff_dT () const private
Update the derivative of the log of the activity coefficients wrt T.
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt temperature.
Definition at line 350 of file MolarityIonicVPSSTP.cpp.
Referenced by MolarityIonicVPSSTP::getPartialMolarCp(), MolarityIonicVPSSTP::getPartialMolarEnthalpies(), and MolarityIonicVPSSTP::getPartialMolarEntropies().
void s_update_dlnActCoeff_dX_ () const private
Internal routine that calculates the derivative of the activity coefficients wrt the mole fractions.
This routine calculates the the derivative of the activity coefficients wrt to mole fraction with all other mole fractions held constant. This is strictly not permitted. However, if the resulting matrix is multiplied by a permissible deltaX vector then everything is ok.
This is the natural way to handle concentration derivatives in this routine.
Definition at line 356 of file MolarityIonicVPSSTP.cpp.
doublereal err (const std::string & msg) const private
Error function.
Print an error string and exit
Parameters
msg Message to be printed
Definition at line 365 of file MolarityIonicVPSSTP.cpp.
References MolarityIonicVPSSTP::eosType(), and Cantera::int2str().
Member Data Documentation
int PBType_ protected
PBTYPE_PASSTHROUGH - All species are passthrough species
PBTYPE_SINGLEANION - there is only one anion in the mixture
PBTYPE_SINGLECATION - there is only one cation in the mixture
PBTYPE_MULTICATIONANION - Complex mixture
Definition at line 355 of file MolarityIonicVPSSTP.h.
Referenced by MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::initThermo(), and MolarityIonicVPSSTP::operator=().
size_t numPBSpecies_ protected
Number of pseudo binary species.
Definition at line 358 of file MolarityIonicVPSSTP.h.
Referenced by MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::initThermo(), and MolarityIonicVPSSTP::operator=().
size_t indexSpecialSpecies_ protected
index of special species
Definition at line 361 of file MolarityIonicVPSSTP.h.
Referenced by MolarityIonicVPSSTP::operator=().
std::vector<size_t> cationList_ protected
Vector of cation indices in the mixture.
Definition at line 366 of file MolarityIonicVPSSTP.h.
Referenced by MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::initThermo(), and MolarityIonicVPSSTP::operator=().
size_t numCationSpecies_ protected
Number of cations in the mixture.
Definition at line 369 of file MolarityIonicVPSSTP.h.
Referenced by MolarityIonicVPSSTP::calcPseudoBinaryMoleFractions(), MolarityIonicVPSSTP::initThermo(), and MolarityIonicVPSSTP::operator=().
The documentation for this class was generated from the following files:
MolarityIonicVPSSTP.h
MolarityIonicVPSSTP.cpp