Cantera: IdealMolalSoln Class Reference
IdealMolalSoln Class Reference
Thermodynamic Properties
This phase is based upon the mixing-rule assumption that all molality-based activity coefficients are equal to one.
#include <IdealMolalSoln.h>
Public Member Functions
IdealMolalSoln ()
Constructor.
IdealMolalSoln (const IdealMolalSoln &)
Copy Constructor.
IdealMolalSoln & operator= (const IdealMolalSoln &)
Assignment operator.
IdealMolalSoln (const std::string &inputFile, const std::string &id="")
Constructor for phase initialization.
IdealMolalSoln (XML_Node &phaseRef, const std::string &id="")
Constructor for phase initialization.
ThermoPhase * duplMyselfAsThermoPhase () const
Duplication function.
virtual void setParameters (int n, doublereal *const c)
virtual void getParameters (int &n, doublereal *const c) const
virtual void setParametersFromXML (const XML_Node &eosdata)
virtual void initThermo ()
Initialization routine for an IdealMolalSoln phase.
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id="")
Import and initialize an IdealMolalSoln phase specification in an XML tree into the current object.
double speciesMolarVolume (int k) const
Report the molar volume of species k.
void getSpeciesMolarVolumes (double *smv) const
Utilities
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Molar enthalpy of the solution. Units: J/kmol.
virtual doublereal intEnergy_mole () const
Molar internal energy of the solution: Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy of the solution. Units: J/kmol/K.
virtual doublereal gibbs_mole () const
Molar Gibbs function for the solution: Units J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity of the solution at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity of the solution at constant volume. Units: J/kmol/K.
Potential Energy
Species may have an additional potential energy due to the presence of external gravitation or electric fields.
These methods allow specifying a potential energy for individual species.
virtual void setPotentialEnergy (int k, doublereal pe)
Set the potential energy of species k to pe.
virtual doublereal potentialEnergy (int k) const
Get the potential energy of species k.
Activities and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T)\) is the chemical potential at unit activity, which depends only on temperature and the pressure.
virtual void getActivityConcentrations (doublereal *c) const
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
virtual void getActivities (doublereal *ac) const
virtual void getMolalityActivityCoefficients (doublereal *acMolality) const
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials: Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution. Units: J/kmol.
virtual void getPartialMolarVolumes (doublereal *vbar) const
virtual void getPartialMolarCp (doublereal *cpbar) const
Partial molar heat capacity of the solution:. UnitsL J/kmol/K.
Chemical Equilibrium
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
Critical state properties.
These methods are only implemented by some subclasses.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critDensity () const
Critical density (kg/m3).
Public Member Functions inherited from MolalityVPSSTP
MolalityVPSSTP ()
Default Constructor.
MolalityVPSSTP (const MolalityVPSSTP &b)
Copy constructor.
MolalityVPSSTP & operator= (const MolalityVPSSTP &b)
Assignment operator.
virtual void setStateFromXML (const XML_Node &state)
Set equation of state parameter values from XML entries.
void setState_TPM (doublereal t, doublereal p, const doublereal *const molalities)
Set the temperature (K), pressure (Pa), and molalities (gmol kg-1) of the solutes.
void setState_TPM (doublereal t, doublereal p, compositionMap &m)
Set the temperature (K), pressure (Pa), and molalities.
void setState_TPM (doublereal t, doublereal p, const std::string &m)
Set the temperature (K), pressure (Pa), and molalities.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
void setpHScale (const int pHscaleType)
Set the pH scale, which determines the scale for single-ion activity coefficients.
int pHScale () const
Reports the pH scale, which determines the scale for single-ion activity coefficients.
void setSolvent (size_t k)
This routine sets the index number of the solvent for the phase.
size_t solventIndex () const
Returns the solvent index.
void setMoleFSolventMin (doublereal xmolSolventMIN)
Sets the minimum mole fraction in the molality formulation.
doublereal moleFSolventMin () const
Returns the minimum mole fraction in the molality formulation.
void calcMolalities () const
Calculates the molality of all species and stores the result internally.
void getMolalities (doublereal *const molal) const
This function will return the molalities of the species.
void setMolalities (const doublereal *const molal)
Set the molalities of the solutes in a phase.
void setMolalitiesByName (compositionMap &xMap)
Set the molalities of a phase.
void setMolalitiesByName (const std::string &name)
Set the molalities of a phase.
int activityConvention () const
This method returns the activity convention.
void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual double osmoticCoefficient () const
Calculate the osmotic coefficient.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Public Attributes
int IMS_typeCutoff_
Cutoff type.
doublereal IMS_X_o_cutoff_
value of the solute mole fraction that centers the cutoff polynomials for the cutoff =1 process;
doublereal IMS_gamma_o_min_
gamma_o value for the cutoff process at the zero solvent point
doublereal IMS_gamma_k_min_
gamma_k minimum for the cutoff process at the zero solvent point
doublereal IMS_slopefCut_
Parameter in the polyExp cutoff treatment.
doublereal IMS_slopegCut_
Parameter in the polyExp cutoff treatment.
Parameters in the polyExp cutoff treatment having to do with rate of exp decay
doublereal IMS_cCut_
doublereal IMS_dfCut_
doublereal IMS_efCut_
doublereal IMS_afCut_
doublereal IMS_bfCut_
doublereal IMS_dgCut_
doublereal IMS_egCut_
doublereal IMS_agCut_
doublereal IMS_bgCut_
Protected Attributes
vector_fp m_speciesMolarVolume
Species molar volume \(m^3 kmol^{-1} \).
int m_formGC
The standard concentrations can have three different forms depending on the value of the member attribute m_formGC, which is supplied in the XML file.
Protected Attributes inherited from MolalityVPSSTP
size_t m_indexSolvent
Index of the solvent.
int m_pHScalingType
Scaling to be used for output of single-ion species activity coefficients.
size_t m_indexCLM
Index of the phScale species.
doublereal m_weightSolvent
Molecular weight of the Solvent.
doublereal m_xmolSolventMIN
doublereal m_Mnaught
This is the multiplication factor that goes inside log expressions involving the molalities of species.
vector_fp m_molalities
Current value of the molalities of the species in the phase.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
Protected Attributes inherited from Phase
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
doublereal err (const std::string &msg) const
Internal error message.
void s_updateIMS_lnMolalityActCoeff () const
This function will be called to update the internally stored natural logarithm of the molality activity coefficients.
void initLengths ()
This internal function adjusts the lengths of arrays.
void calcIMSCutoffParams_ ()
Calculate parameters for cutoff treatments of activity coefficients.
Private Attributes
vector_fp m_pp
Temporary array used in equilibrium calculations.
vector_fp m_tmpV
vector of size m_kk, used as a temporary holding area.
vector_fp IMS_lnActCoeffMolal_
Logarithm of the molal activity coefficients.
Mechanical Equation of State Properties
In this equation of state implementation, the density is a function only of the mole fractions.
Therefore, it can't be an independent variable. Instead, the pressure is used as the independent variable. Functions which try to set the thermodynamic state by calling setDensity() may cause an exception to be thrown.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature.
void setDensity (const doublereal rho)
Overwritten setDensity() function is necessary because the density is not an independent variable.
void setMolarDensity (const doublereal rho)
Overwritten setMolarDensity() function is necessary because the density is not an independent variable.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual doublereal isothermalCompressibility () const
The isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
The thermal expansion coefficient. Units: 1/K.
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Additional Inherited Members
Protected Member Functions inherited from MolalityVPSSTP
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
virtual void getUnscaledMolalityActivityCoefficients (doublereal *acMolality) const
Get the array of unscaled non-dimensional molality based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void applyphScale (doublereal *acMolality) const
Apply the current phScale to a set of activity Coefficients or activities.
Detailed Description
This phase is based upon the mixing-rule assumption that all molality-based activity coefficients are equal to one.
This is a full instantiation of a ThermoPhase object. The assumption is that the molality-based activity coefficient is equal to one. This also implies that the osmotic coefficient is equal to one.
Note, this does not mean that the solution is an ideal solution. In fact, there is a singularity in the formulation as the solvent concentration goes to zero.
The mechanical equation of state is currently assumed to be that of an incompressible solution. This may change in the future. Each species has its own molar volume. The molar volume is a constant.
Class IdealMolalSoln represents a condensed phase. The phase and the pure species phases which comprise the standard states of the species are assumed to have zero volume expansivity and zero isothermal compressibility. Each species does, however, have constant but distinct partial molar volumes equal to their pure species molar volumes. The class derives from class ThermoPhase, and overloads the virtual methods defined there with ones that use expressions appropriate for incompressible mixtures.
The standard concentrations can have three different forms depending on the value of the member attribute m_formGC, which is supplied in the XML file.
m_formGC ActivityConc StandardConc
0 \({m_k}/ { m^{\Delta}}\) \(1.0 \)
1 \(m_k / (m^{\Delta} V_k)\) \(1.0 / V_k \)
2 \(m_k / (m^{\Delta} V^0_0)\) \(1.0 / V^0_0\)
\(V^0_0 \) is the solvent standard molar volume. \(m^{\Delta} \) is a constant equal to a molality of \(1.0 \quad\mbox{gm kmol}^{-1} \).
The current default is to have mformGC = 2.
The value and form of the activity concentration will affect reaction rate constants involving species in this phase.
 <thermo model="IdealMolalSoln">
    <standardConc model="solvent_volume" />
    <solvent> H2O(l) </solvent>
    <activityCoefficients model="IdealMolalSoln" >
        <idealMolalSolnCutoff model="polyExp">
            <gamma_O_limit> 1.0E-5  </gamma_O_limit>
            <gamma_k_limit> 1.0E-5  <gamma_k_limit>
            <X_o_cutoff>    0.20    </X_o_cutoff>
            <C_0_param>     0.05    </C_0_param>
            <slope_f_limit> 0.6     </slope_f_limit>
            <slope_g_limit> 0.0     </slope_g_limit>
        </idealMolalSolnCutoff>
     </activityCoefficients>
 </thermo>
Definition at line 97 of file IdealMolalSoln.h.
Constructor & Destructor Documentation
IdealMolalSoln ()
Constructor.
Definition at line 28 of file IdealMolalSoln.cpp.
Referenced by IdealMolalSoln::duplMyselfAsThermoPhase().
IdealMolalSoln (const IdealMolalSoln & b)
Copy Constructor.
Definition at line 49 of file IdealMolalSoln.cpp.
IdealMolalSoln (const std::string & inputFile, const std::string & id = "")
Constructor for phase initialization.
This constructor will initialize a phase, by reading the required information from an input file.
Parameters
inputFile Name of the Input file that contains information about the phase
id id of the phase within the input file
Definition at line 88 of file IdealMolalSoln.cpp.
References ThermoPhase::initThermoFile().
IdealMolalSoln (XML_Node & phaseRef, const std::string & id = "")
Constructor for phase initialization.
This constructor will initialize a phase, by reading the required information from XML_Node tree.
Parameters
phaseRef reference for an XML_Node tree that contains the information necessary to initialize the phase.
id id of the phase within the input file
Definition at line 111 of file IdealMolalSoln.cpp.
References Cantera::findXMLPhase(), and Cantera::importPhase().
Member Function Documentation
IdealMolalSoln & operator= (const IdealMolalSoln & b)
Assignment operator.
Definition at line 60 of file IdealMolalSoln.cpp.
References IdealMolalSoln::IMS_gamma_k_min_, IdealMolalSoln::IMS_gamma_o_min_, IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_slopefCut_, IdealMolalSoln::IMS_slopegCut_, IdealMolalSoln::IMS_typeCutoff_, IdealMolalSoln::IMS_X_o_cutoff_, IdealMolalSoln::m_formGC, IdealMolalSoln::m_pp, IdealMolalSoln::m_speciesMolarVolume, IdealMolalSoln::m_tmpV, and MolalityVPSSTP::operator=().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication function.
This virtual function is used to create a duplicate of the current phase. It's used to duplicate the phase when given a ThermoPhase pointer to the phase.
Returns
It returns a ThermoPhase pointer.
Reimplemented from MolalityVPSSTP.
Definition at line 133 of file IdealMolalSoln.cpp.
References IdealMolalSoln::IdealMolalSoln().
virtual int eosType () const inline virtual
Equation of state type flag.
The base class returns zero. Subclasses should define this to return a unique non-zero value. Constants defined for this purpose are listed in mix_defs.h.
Reimplemented from MolalityVPSSTP.
Definition at line 150 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::getUnitsStandardConc().
doublereal enthalpy_mole () const virtual
Molar enthalpy of the solution. Units: J/kmol.
Returns the amount of enthalpy per mole of solution. For an ideal molal solution,
\[ \bar{h}(T, P, X_k) = \sum_k X_k \bar{h}_k(T) \]
The formula is written in terms of the partial molar enthalpies. \(\bar{h}_k(T, p, m_k) \). See the partial molar enthalpy function, getPartialMolarEnthalpies(), for details.
Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 138 of file IdealMolalSoln.cpp.
References DATA_PTR, Phase::getMoleFractions(), IdealMolalSoln::getPartialMolarEnthalpies(), IdealMolalSoln::m_pp, IdealMolalSoln::m_tmpV, and Phase::mean_X().
doublereal intEnergy_mole () const virtual
Molar internal energy of the solution: Units: J/kmol.
Returns the amount of internal energy per mole of solution. For an ideal molal solution,
\[ \bar{u}(T, P, X_k) = \sum_k X_k \bar{u}_k(T) \]
The formula is written in terms of the partial molar internal energy. \(\bar{u}_k(T, p, m_k) \).
Reimplemented from ThermoPhase.
Definition at line 145 of file IdealMolalSoln.cpp.
References DATA_PTR, IdealMolalSoln::getPartialMolarEnthalpies(), IdealMolalSoln::m_tmpV, and Phase::mean_X().
doublereal entropy_mole () const virtual
Molar entropy of the solution. Units: J/kmol/K.
Returns the amount of entropy per mole of solution. For an ideal molal solution,
\[ \bar{s}(T, P, X_k) = \sum_k X_k \bar{s}_k(T) \]
The formula is written in terms of the partial molar entropies. \(\bar{s}_k(T, p, m_k) \). See the partial molar entropies function, getPartialMolarEntropies(), for details.
Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 151 of file IdealMolalSoln.cpp.
References DATA_PTR, IdealMolalSoln::getPartialMolarEntropies(), IdealMolalSoln::m_tmpV, and Phase::mean_X().
doublereal gibbs_mole () const virtual
Molar Gibbs function for the solution: Units J/kmol.
Returns the gibbs free energy of the solution per mole of the solution.
\[ \bar{g}(T, P, X_k) = \sum_k X_k \mu_k(T) \]
Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 157 of file IdealMolalSoln.cpp.
References DATA_PTR, IdealMolalSoln::getChemPotentials(), IdealMolalSoln::m_tmpV, and Phase::mean_X().
doublereal cp_mole () const virtual
Molar heat capacity of the solution at constant pressure. Units: J/kmol/K.
\[ \bar{c}_p(T, P, X_k) = \sum_k X_k \bar{c}_{p,k}(T) \]
Units: J/kmol/K
Reimplemented from ThermoPhase.
Definition at line 163 of file IdealMolalSoln.cpp.
References DATA_PTR, IdealMolalSoln::getPartialMolarCp(), IdealMolalSoln::m_tmpV, and Phase::mean_X().
doublereal cv_mole () const virtual
Molar heat capacity of the solution at constant volume. Units: J/kmol/K.
NOT IMPLEMENTED.
Reimplemented from ThermoPhase.
Definition at line 169 of file IdealMolalSoln.cpp.
References IdealMolalSoln::err().
void setPressure (doublereal p) virtual
Set the pressure at constant temperature.
Units: Pa. This method sets a constant within the object. The mass density is not a function of pressure.
Parameters
p Input Pressure
Reimplemented from VPStandardStateTP.
Definition at line 178 of file IdealMolalSoln.cpp.
References IdealMolalSoln::setState_TP(), and Phase::temperature().
void calcDensity () protected virtual
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
The formula for this is
\[ \rho = \frac{\sum_k{X_k W_k}}{\sum_k{X_k V_k}} \]
where \(X_k\) are the mole fractions, \(W_k\) are the molecular weights, and \(V_k\) are the pure species molar volumes.
Note, the basis behind this formula is that in an ideal solution the partial molar volumes are equal to the pure species molar volumes. We have additionally specified in this class that the pure species molar volumes are independent of temperature and pressure.
Reimplemented from VPStandardStateTP.
Definition at line 183 of file IdealMolalSoln.cpp.
References Phase::getMoleFractions(), IdealMolalSoln::getPartialMolarVolumes(), Phase::m_kk, IdealMolalSoln::m_pp, IdealMolalSoln::m_tmpV, Phase::meanMolecularWeight(), and Phase::setDensity().
Referenced by IdealMolalSoln::setState_TP().
void setDensity (const doublereal rho) virtual
Overwritten setDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition
May have to adjust the strategy here to make the eos for these materials slightly compressible, in order to create a condition where the density is a function of the pressure.
This function will now throw an error condition.
Parameters
rho Input Density
Reimplemented from Phase.
Definition at line 207 of file IdealMolalSoln.cpp.
References Phase::density().
void setMolarDensity (const doublereal rho) virtual
Overwritten setMolarDensity() function is necessary because the density is not an independent variable.
This function will now throw an error condition.
Parameters
rho Input Density
Reimplemented from Phase.
Definition at line 216 of file IdealMolalSoln.cpp.
References Phase::molarDensity().
void setState_TP (doublereal t, doublereal p) virtual
Set the temperature (K) and pressure (Pa)
Set the temperature and pressure.
Parameters
t Temperature (K)
p Pressure (Pa)
Reimplemented from VPStandardStateTP.
Definition at line 225 of file IdealMolalSoln.cpp.
References IdealMolalSoln::calcDensity(), VPStandardStateTP::m_Pcurrent, Phase::setTemperature(), and VPStandardStateTP::updateStandardStateThermo().
Referenced by IdealMolalSoln::setPressure().
doublereal isothermalCompressibility () const virtual
The isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
It's equal to zero for this model, since the molar volume doesn't change with pressure or temperature.
Reimplemented from ThermoPhase.
Definition at line 197 of file IdealMolalSoln.cpp.
doublereal thermalExpansionCoeff () const virtual
The thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
It's equal to zero for this model, since the molar volume doesn't change with pressure or temperature.
Reimplemented from ThermoPhase.
Definition at line 202 of file IdealMolalSoln.cpp.
virtual void setPotentialEnergy (int k, doublereal pe) inline virtual
Set the potential energy of species k to pe.
Units: J/kmol.
Parameters
k Species index
pe Input potential energy.
Definition at line 354 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
virtual doublereal potentialEnergy (int k) const inline virtual
Get the potential energy of species k.
Units: J/kmol.
Parameters
k Species index
Definition at line 364 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
void getActivityConcentrations (doublereal * c) const virtual
This method returns an array of generalized concentrations \(C_k\) that are defined such that \(a_k = C_k / C^0_k, \) where \(C^0_k \) is a standard concentration defined below. These generalized concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions.
Parameters
c Array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from MolalityVPSSTP.
Definition at line 238 of file IdealMolalSoln.cpp.
References IdealMolalSoln::getActivities(), IdealMolalSoln::m_formGC, Phase::m_kk, and IdealMolalSoln::standardConcentration().
doublereal standardConcentration (size_t k = 0) const virtual
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k Species index
Reimplemented from MolalityVPSSTP.
Definition at line 255 of file IdealMolalSoln.cpp.
References IdealMolalSoln::m_formGC, MolalityVPSSTP::m_indexSolvent, and IdealMolalSoln::m_speciesMolarVolume.
Referenced by IdealMolalSoln::getActivityConcentrations(), and IdealMolalSoln::logStandardConc().
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species
Parameters
k Species index
Reimplemented from MolalityVPSSTP.
Definition at line 272 of file IdealMolalSoln.cpp.
References IdealMolalSoln::standardConcentration().
void getUnitsStandardConc (double * uA, int k = 0, int sizeUA = 6) const virtual
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
This routine is used in print out applications where the units are needed. Usually, MKS units are assumed throughout the program and in the XML input files.
Parameters
uA Output vector containing the units uA[0] = kmol units - default = 1 uA[1] = m units - default = -nDim(), the number of spatial dimensions in the Phase class. uA[2] = kg units - default = 0; uA[3] = Pa(pressure) units - default = 0; uA[4] = Temperature units - default = 0; uA[5] = time units - default = 0
k species index. Defaults to 0.
sizeUA output int containing the size of the vector. Currently, this is equal to 6.
Reimplemented from MolalityVPSSTP.
Definition at line 278 of file IdealMolalSoln.cpp.
References IdealMolalSoln::eosType(), and Phase::nDim().
void getActivities (doublereal * ac) const virtual
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
(note solvent is on molar scale)
Parameters
ac Output activity coefficients. Length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 309 of file IdealMolalSoln.cpp.
References VPStandardStateTP::_updateStandardStateThermo(), MolalityVPSSTP::calcMolalities(), IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_typeCutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_molalities, MolalityVPSSTP::m_xmolSolventMIN, Phase::moleFraction(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
Referenced by IdealMolalSoln::getActivityConcentrations().
void getMolalityActivityCoefficients (doublereal * acMolality) const virtual
Get the array of non-dimensional molality-based activity coefficients at the current solution temperature, pressure, and solution concentration.
(note solvent is on molar scale. The solvent molar based activity coefficient is returned).
Parameters
acMolality Output Molality-based activity coefficients. Length: m_kk.
Reimplemented from MolalityVPSSTP.
Definition at line 344 of file IdealMolalSoln.cpp.
References IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_typeCutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, Phase::moleFraction(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials: Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution.
\[ \mu_k = \mu^{o}_k(T,P) + R T \ln(\frac{m_k}{m^\Delta}) \]
\[ \mu_w = \mu^{o}_w(T,P) + R T ((X_w - 1.0) / X_w) \]
\(w \) refers to the solvent species. \(X_w \) is the mole fraction of the solvent. \(m_k \) is the molality of the kth solute. \(m^\Delta \) is 1 gmol solute per kg solvent.
Units: J/kmol.
Parameters
mu Output vector of species chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 369 of file IdealMolalSoln.cpp.
References AssertThrow, MolalityVPSSTP::calcMolalities(), Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_typeCutoff_, IdealMolalSoln::IMS_X_o_cutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_molalities, Phase::moleFraction(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by IdealMolalSoln::gibbs_mole().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol) For this phase, the partial molar enthalpies are equal to the species standard state enthalpies.
\[ \bar h_k(T,P) = \hat h^{ref}_k(T) + (P - P_{ref}) \hat V^0_k \]
The reference-state pure-species enthalpies, \(\hat h^{ref}_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See Also
SpeciesThermo
Parameters
hbar Output vector of partial molar enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 427 of file IdealMolalSoln.cpp.
References ThermoPhase::_RT(), VPStandardStateTP::getEnthalpy_RT(), and Phase::m_kk.
Referenced by IdealMolalSoln::enthalpy_mole(), and IdealMolalSoln::intEnergy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution. Units: J/kmol.
Maxwell's equations provide an insight in how to calculate this (p.215 Smith and Van Ness)
\[ \frac{d(\mu_k)}{dT} = -\bar{s}_i \]
For this phase, the partial molar entropies are equal to the standard state species entropies plus the ideal molal solution contribution.
\[ \bar{s}_k(T,P) = s^0_k(T) - R \ln(\frac{m_k}{m^{\triangle}}) \]
\[ \bar{s}_w(T,P) = s^0_w(T) - R ((X_w - 1.0) / X_w) \]
The subscript, w, refers to the solvent species. \(X_w \) is the mole fraction of solvent. The reference-state pure-species entropies, \(s^0_k(T) \), at the reference pressure, \(P_{ref} \), are computed by the species thermodynamic property manager. They are polynomial functions of temperature.
See Also
SpeciesThermo
Parameters
sbar Output vector of partial molar entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 436 of file IdealMolalSoln.cpp.
References MolalityVPSSTP::calcMolalities(), Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_typeCutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_molalities, Phase::moleFraction(), IdealMolalSoln::s_updateIMS_lnMolalityActCoeff(), and Cantera::SmallNumber.
Referenced by IdealMolalSoln::entropy_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
For this solution, the partial molar volumes are equal to the constant species molar volumes.
Units: m^3 kmol-1.
Parameters
vbar Output vector of partial molar volumes.
Reimplemented from ThermoPhase.
Definition at line 474 of file IdealMolalSoln.cpp.
References VPStandardStateTP::getStandardVolumes().
Referenced by IdealMolalSoln::calcDensity().
void getPartialMolarCp (doublereal * cpbar) const virtual
Partial molar heat capacity of the solution:. UnitsL J/kmol/K.
The kth partial molar heat capacity is equal to the temperature derivative of the partial molar enthalpy of the kth species in the solution at constant P and composition (p. 220 Smith and Van Ness).
\[ \bar{Cp}_k(T,P) = {Cp}^0_k(T) \]
For this solution, this is equal to the reference state heat capacities.
Units: J/kmol/K
Parameters
cpbar Output vector of partial molar heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 479 of file IdealMolalSoln.cpp.
References Cantera::GasConstant, VPStandardStateTP::getCp_R(), and Phase::m_kk.
Referenced by IdealMolalSoln::cp_mole().
virtual void setToEquilState (const doublereal * lambda_RT) inline virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Not implemented.
Parameters
lambda_RT vector of Nondimensional element potentials.
Reimplemented from MolalityVPSSTP.
Definition at line 599 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
void setParameters (int n, doublereal *const c) virtual
Set equation of state parameters. The number and meaning of these depends on the subclass.
Parameters
n number of parameters
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 673 of file IdealMolalSoln.cpp.
void getParameters (int & n, doublereal *const c) const virtual
Get the parameters used to initialize the phase.
Parameters
n number of parameters (output)
c array of n coefficients
Reimplemented from ThermoPhase.
Definition at line 677 of file IdealMolalSoln.cpp.
void setParametersFromXML (const XML_Node & eosdata) virtual
Set equation of state parameter values from XML entries. This method is called by function importPhase in file importCTML.cpp when processing a phase definition in an input file. It should be overloaded in subclasses to set any parameters that are specific to that particular phase model.
HKM -> Right now, the parameters are set elsewhere (initThermo) It just didn't seem to fit.
Parameters
eosdata An XML_Node object corresponding to the "thermo" entry for this phase in the input file.
Reimplemented from VPStandardStateTP.
Definition at line 681 of file IdealMolalSoln.cpp.
virtual doublereal critTemperature () const inline virtual
Critical temperature (K).
Not implemented for this phase type.
Reimplemented from ThermoPhase.
Definition at line 649 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
virtual doublereal critPressure () const inline virtual
Critical pressure (Pa).
Not implemented for this phase type.
Reimplemented from ThermoPhase.
Definition at line 659 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
virtual doublereal critDensity () const inline virtual
Critical density (kg/m3).
Not implemented for this phase type.
Reimplemented from ThermoPhase.
Definition at line 668 of file IdealMolalSoln.h.
References IdealMolalSoln::err().
void initThermo () virtual
Initialization routine for an IdealMolalSoln phase.
This internal routine is responsible for setting up the internal storage. This is reimplemented from the ThermoPhase class.
Reimplemented from MolalityVPSSTP.
Definition at line 496 of file IdealMolalSoln.cpp.
References IdealMolalSoln::initLengths(), and MolalityVPSSTP::initThermo().
Referenced by IdealMolalSoln::initThermoXML().
void initThermoXML (XML_Node & phaseNode, const std::string & id = "") virtual
Import and initialize an IdealMolalSoln phase specification in an XML tree into the current object.
This routine is called from importPhase() to finish up the initialization of the thermo object. It reads in the species molar volumes.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 502 of file IdealMolalSoln.cpp.
References XML_Node::attrib(), IdealMolalSoln::calcIMSCutoffParams_(), XML_Node::child(), XML_Node::findByAttr(), XML_Node::findByName(), Cantera::get_XML_NameID(), ctml::getFloat(), ctml::getStringArray(), XML_Node::hasChild(), XML_Node::id(), IdealMolalSoln::IMS_gamma_k_min_, IdealMolalSoln::IMS_gamma_o_min_, IdealMolalSoln::IMS_slopefCut_, IdealMolalSoln::IMS_slopegCut_, IdealMolalSoln::IMS_typeCutoff_, IdealMolalSoln::IMS_X_o_cutoff_, IdealMolalSoln::initThermo(), MolalityVPSSTP::initThermoXML(), IdealMolalSoln::m_formGC, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, IdealMolalSoln::m_speciesMolarVolume, Cantera::npos, XML_Node::root(), MolalityVPSSTP::setMoleFSolventMin(), MolalityVPSSTP::setStateFromXML(), Phase::speciesName(), and Phase::speciesNames().
double speciesMolarVolume (int k) const
Report the molar volume of species k.
units - \(m^3 kmol^{-1} \)
Parameters
k Species index.
void getSpeciesMolarVolumes (double * smv) const
Fill in a return vector containing the species molar volumes units - \(m^3 kmol^{-1} \)
Parameters
smv Output vector of species molar volumes.
doublereal err (const std::string & msg) const private
Internal error message.
Parameters
msg message to be printed
Definition at line 693 of file IdealMolalSoln.cpp.
Referenced by IdealMolalSoln::critDensity(), IdealMolalSoln::critPressure(), IdealMolalSoln::critTemperature(), IdealMolalSoln::cv_mole(), IdealMolalSoln::potentialEnergy(), IdealMolalSoln::setPotentialEnergy(), and IdealMolalSoln::setToEquilState().
void s_updateIMS_lnMolalityActCoeff () const private
This function will be called to update the internally stored natural logarithm of the molality activity coefficients.
Normally the solutes are all zero. However, sometimes they are not, due to stability schemes.
gamma_k_molar = gamma_k_molal / Xmol_solvent
gamma_o_molar = gamma_o_molal
Definition at line 700 of file IdealMolalSoln.cpp.
References MolalityVPSSTP::calcMolalities(), IdealMolalSoln::IMS_gamma_k_min_, IdealMolalSoln::IMS_gamma_o_min_, IdealMolalSoln::IMS_lnActCoeffMolal_, IdealMolalSoln::IMS_typeCutoff_, IdealMolalSoln::IMS_X_o_cutoff_, MolalityVPSSTP::m_indexSolvent, Phase::m_kk, MolalityVPSSTP::m_xmolSolventMIN, and Phase::moleFraction().
Referenced by IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), IdealMolalSoln::getMolalityActivityCoefficients(), and IdealMolalSoln::getPartialMolarEntropies().
void initLengths () private
This internal function adjusts the lengths of arrays.
This function is not virtual nor is it inherited
Definition at line 812 of file IdealMolalSoln.cpp.
References IdealMolalSoln::IMS_lnActCoeffMolal_, Phase::m_kk, IdealMolalSoln::m_pp, IdealMolalSoln::m_speciesMolarVolume, IdealMolalSoln::m_tmpV, and Phase::nSpecies().
Referenced by IdealMolalSoln::initThermo().
void calcIMSCutoffParams_ () private
Calculate parameters for cutoff treatments of activity coefficients.
Some cutoff treatments for the activity coefficients actually require some calculations to create a consistent treatment.
This routine is called during the setup to calculate these parameters
Definition at line 825 of file IdealMolalSoln.cpp.
References IdealMolalSoln::IMS_gamma_k_min_, IdealMolalSoln::IMS_gamma_o_min_, IdealMolalSoln::IMS_slopefCut_, IdealMolalSoln::IMS_slopegCut_, and IdealMolalSoln::IMS_X_o_cutoff_.
Referenced by IdealMolalSoln::initThermoXML().
Member Data Documentation
vector_fp m_speciesMolarVolume protected
Species molar volume \(m^3 kmol^{-1} \).
Definition at line 728 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::initLengths(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::standardConcentration().
int m_formGC protected
The standard concentrations can have three different forms depending on the value of the member attribute m_formGC, which is supplied in the XML file.
m_formGC ActivityConc StandardConc
0 \({m_k}/ { m^{\Delta}}\) \(1.0 \)
1 \(m_k / (m^{\Delta} V_k)\) \(1.0 / V_k \)
2 \(m_k / (m^{\Delta} V^0_0)\) \(1.0 / V^0_0\)
Definition at line 742 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::getActivityConcentrations(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::standardConcentration().
int IMS_typeCutoff_
Cutoff type.
Definition at line 746 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), IdealMolalSoln::getMolalityActivityCoefficients(), IdealMolalSoln::getPartialMolarEntropies(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
vector_fp m_pp mutable private
Temporary array used in equilibrium calculations.
Definition at line 752 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcDensity(), IdealMolalSoln::enthalpy_mole(), IdealMolalSoln::initLengths(), and IdealMolalSoln::operator=().
vector_fp m_tmpV mutable private
vector of size m_kk, used as a temporary holding area.
Definition at line 757 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcDensity(), IdealMolalSoln::cp_mole(), IdealMolalSoln::enthalpy_mole(), IdealMolalSoln::entropy_mole(), IdealMolalSoln::gibbs_mole(), IdealMolalSoln::initLengths(), IdealMolalSoln::intEnergy_mole(), and IdealMolalSoln::operator=().
vector_fp IMS_lnActCoeffMolal_ mutable private
Logarithm of the molal activity coefficients.
Normally these are all one. However, stability schemes will change that
Definition at line 763 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::getActivities(), IdealMolalSoln::getChemPotentials(), IdealMolalSoln::getMolalityActivityCoefficients(), IdealMolalSoln::getPartialMolarEntropies(), IdealMolalSoln::initLengths(), IdealMolalSoln::operator=(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_X_o_cutoff_
value of the solute mole fraction that centers the cutoff polynomials for the cutoff =1 process;
Definition at line 767 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcIMSCutoffParams_(), IdealMolalSoln::getChemPotentials(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_gamma_o_min_
gamma_o value for the cutoff process at the zero solvent point
Definition at line 770 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcIMSCutoffParams_(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_gamma_k_min_
gamma_k minimum for the cutoff process at the zero solvent point
Definition at line 773 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcIMSCutoffParams_(), IdealMolalSoln::initThermoXML(), IdealMolalSoln::operator=(), and IdealMolalSoln::s_updateIMS_lnMolalityActCoeff().
doublereal IMS_slopefCut_
Parameter in the polyExp cutoff treatment.
This is the slope of the f function at the zero solvent point Default value is 0.6
Definition at line 780 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcIMSCutoffParams_(), IdealMolalSoln::initThermoXML(), and IdealMolalSoln::operator=().
doublereal IMS_slopegCut_
Parameter in the polyExp cutoff treatment.
This is the slope of the g function at the zero solvent point Default value is 0.0
Definition at line 787 of file IdealMolalSoln.h.
Referenced by IdealMolalSoln::calcIMSCutoffParams_(), IdealMolalSoln::initThermoXML(), and IdealMolalSoln::operator=().
The documentation for this class was generated from the following files:
IdealMolalSoln.h
IdealMolalSoln.cpp