Cantera: PDSS_IdealGas Class Reference
PDSS_IdealGas Class Reference
Species Standard-State Thermodynamic Properties
Derived class for pressure dependent standard states of an ideal gas species.
#include <PDSS_IdealGas.h>
Public Member Functions
Constructors
PDSS_IdealGas (VPStandardStateTP *tp, int spindex)
Constructor.
PDSS_IdealGas (const PDSS_IdealGas &b)
Copy Constructur.
PDSS_IdealGas & operator= (const PDSS_IdealGas &b)
Assignment operator.
PDSS_IdealGas (VPStandardStateTP *tp, int spindex, const std::string &inputFile, const std::string &id="")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
PDSS_IdealGas (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &speciesNode, const XML_Node &phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
virtual ~PDSS_IdealGas ()
Destructor.
virtual PDSS * duplMyselfAsPDSS () const
Duplicator.
Molar Thermodynamic Properties of the Species Standard State
   in the Solution
virtual doublereal enthalpy_mole () const
Return the molar enthalpy in units of J kmol-1.
virtual doublereal enthalpy_RT () const
Return the standard state molar enthalpy divided by RT.
virtual doublereal intEnergy_mole () const
Return the molar internal Energy in units of J kmol-1.
virtual doublereal entropy_mole () const
Return the molar entropy in units of J kmol-1 K-1.
virtual doublereal entropy_R () const
Return the standard state entropy divided by RT.
virtual doublereal gibbs_mole () const
Return the molar gibbs free energy in units of J kmol-1.
virtual doublereal gibbs_RT () const
Return the molar gibbs free energy divided by RT.
virtual doublereal cp_mole () const
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
virtual doublereal cp_R () const
Return the molar const pressure heat capacity divided by RT.
virtual doublereal cv_mole () const
Return the molar const volume heat capacity in units of J kmol-1 K-1.
virtual doublereal molarVolume () const
Return the molar volume at standard state.
virtual doublereal density () const
Return the standard state density at standard state.
Properties of the Reference State of the Species
  in the Solution
virtual doublereal gibbs_RT_ref () const
Return the molar gibbs free energy divided by RT at reference pressure.
virtual doublereal enthalpy_RT_ref () const
Return the molar enthalpy divided by RT at reference pressure.
virtual doublereal entropy_R_ref () const
Return the molar entropy divided by R at reference pressure.
virtual doublereal cp_R_ref () const
Return the molar heat capacity divided by R at reference pressure.
virtual doublereal molarVolume_ref () const
Return the molar volume at reference pressure.
Mechanical Equation of State Properties
virtual doublereal pressure () const
Returns the pressure (Pa)
virtual void setPressure (doublereal pres)
Sets the pressure in the object.
virtual void setTemperature (doublereal temp)
Set the internal temperature.
doublereal temperature () const
Return the current stored temperature.
virtual void setState_TP (doublereal temp, doublereal pres)
Set the internal temperature and pressure.
virtual void setState_TR (doublereal temp, doublereal rho)
Set the internal temperature and density.
Miscellaneous properties of the standard state
virtual doublereal critTemperature () const
critical temperature
virtual doublereal critPressure () const
critical pressure
virtual doublereal critDensity () const
critical density
virtual doublereal satPressure (doublereal t)
saturation pressure
Initialization of the Object
void constructPDSSFile (VPStandardStateTP *vptp_ptr, size_t spindex, const std::string &inputFile, const std::string &id)
Initialization of a PDSS object using an input XML file.
void constructPDSSXML (VPStandardStateTP *vptp_ptr, size_t spindex, const XML_Node &phaseNode, const std::string &id)
Initialization of a PDSS object using an xml tree.
virtual void initThermoXML (const XML_Node &phaseNode, const std::string &id)
Initialization routine for the PDSS object based on the phaseNode.
virtual void initThermo ()
Initialization routine for all of the shallow pointers.
Public Member Functions inherited from PDSS
PDSS ()
Empty Constructor.
PDSS (VPStandardStateTP *tp, size_t spindex)
Constructor that initializes the object by examining the XML entries from the ThermoPhase object.
PDSS (const PDSS &b)
Copy Constructor.
PDSS & operator= (const PDSS &b)
Assignment operator.
virtual ~PDSS ()
Destructor for the phase.
virtual doublereal enthalpyDelp_mole () const
Get the difference in the standard state enthalpy between the current pressure and the reference pressure, p0.
virtual doublereal entropyDelp_mole () const
Get the difference in the standard state entropy between the current pressure and the reference pressure, p0.
virtual doublereal gibbsDelp_mole () const
Get the difference in the standard state gibbs free energy between the current pressure and the reference pressure, p0.
virtual doublereal cpDelp_mole () const
Get the difference in standard state heat capacity between the current pressure and the reference pressure, p0.
doublereal refPressure () const
Return the reference pressure for this phase.
doublereal minTemp () const
return the minimum temperature
doublereal maxTemp () const
return the minimum temperature
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
doublereal temperature () const
Return the current stored temperature.
doublereal molecularWeight () const
Return the molecular weight of the species in units of kg kmol-1.
void setMolecularWeight (doublereal mw)
Set the molecular weight of the species.
PDSS_enumType reportPDSSType () const
Returns the type of the standard state parameterization.
virtual void reportParams (size_t &kindex, int &type, doublereal *const c, doublereal &minTemp, doublereal &maxTemp, doublereal &refPressure) const
This utility function reports back the type of parameterization and all of the parameters for the species, index.
virtual void initAllPtrs (VPStandardStateTP *vptp_ptr, VPSSMgr *vpssmgr_ptr, SpeciesThermo *spthermo_ptr)
Initialize or Reinitialize all shallow pointers in the object.
Additional Inherited Members
Protected Attributes inherited from PDSS
PDSS_enumType m_pdssType
Enumerated type describing the type of the PDSS object.
doublereal m_temp
Current temperature used by the PDSS object.
doublereal m_pres
State of the system - pressure.
doublereal m_p0
Reference state pressure of the species.
doublereal m_minTemp
Minimum temperature.
doublereal m_maxTemp
Maximum temperature.
VPStandardStateTP * m_tp
Thermophase which this species belongs to.
VPSSMgr * m_vpssmgr_ptr
Pointer to the VPSS manager for this object.
doublereal m_mw
Molecular Weight of the species.
size_t m_spindex
Species index in the thermophase corresponding to this species.
SpeciesThermo * m_spthermo
Pointer to the species thermodynamic property manager.
doublereal * m_h0_RT_ptr
Reference state enthalpy divided by RT.
doublereal * m_cp0_R_ptr
Reference state heat capacity divided by R.
doublereal * m_s0_R_ptr
Reference state entropy divided by R.
doublereal * m_g0_RT_ptr
Reference state gibbs free energy divided by RT.
doublereal * m_V0_ptr
Reference state molar volume (m3 kg-1)
doublereal * m_hss_RT_ptr
Standard state enthalpy divided by RT.
doublereal * m_cpss_R_ptr
Standard state heat capacity divided by R.
doublereal * m_sss_R_ptr
Standard state entropy divided by R.
doublereal * m_gss_RT_ptr
Standard state gibbs free energy divided by RT.
doublereal * m_Vss_ptr
Standard State molar volume (m3 kg-1)
Detailed Description
Derived class for pressure dependent standard states of an ideal gas species.
This class is for a single Ideal Gas species.
Definition at line 30 of file PDSS_IdealGas.h.
Constructor & Destructor Documentation
PDSS_IdealGas (VPStandardStateTP * tp, int spindex)
Constructor.
Basic list of constructors and duplicators.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
Definition at line 29 of file PDSS_IdealGas.cpp.
References PDSS::m_pdssType.
Referenced by PDSS_IdealGas::duplMyselfAsPDSS().
PDSS_IdealGas (const PDSS_IdealGas & b)
Copy Constructur.
Parameters
b Object to be copied
Definition at line 60 of file PDSS_IdealGas.cpp.
PDSS_IdealGas (VPStandardStateTP * tp, int spindex, const std::string & inputFile, const std::string & id = "")
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSFile member function.
Parameters
tp Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
inputFile String name of the input file
id String name of the phase in the input file. The default is the empty string, in which case the first phase in the file is used.
Definition at line 36 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::constructPDSSFile(), and PDSS::m_pdssType.
PDSS_IdealGas (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & speciesNode, const XML_Node & phaseRef, bool spInstalled)
Constructor that initializes the object by examining the input file of the ThermoPhase object.
This function calls the constructPDSSXML member function.
Parameters
vptp_ptr Pointer to the ThermoPhase object pertaining to the phase
spindex Species index of the species in the phase
speciesNode Reference to the species XML tree.
phaseRef Reference to the XML tree containing the phase information.
spInstalled Boolean indicating whether the species is installed yet or not.
Definition at line 46 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::constructPDSSXML(), and PDSS::m_pdssType.
~PDSS_IdealGas () virtual
Destructor.
Definition at line 82 of file PDSS_IdealGas.cpp.
Member Function Documentation
PDSS_IdealGas & operator= (const PDSS_IdealGas & b)
Assignment operator.
Parameters
b Object to be copeid
Definition at line 73 of file PDSS_IdealGas.cpp.
References PDSS::operator=().
PDSS * duplMyselfAsPDSS () const virtual
Duplicator.
Reimplemented from PDSS.
Definition at line 87 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::PDSS_IdealGas().
doublereal enthalpy_mole () const virtual
Return the molar enthalpy in units of J kmol-1.
Returns the species standard state enthalpy in J kmol-1 at the current temperature and pressure.
Returns
returns the species standard state enthalpy in J kmol-1
Reimplemented from PDSS.
Definition at line 168 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::enthalpy_RT(), Cantera::GasConstant, and PDSS::m_temp.
doublereal enthalpy_RT () const virtual
Return the standard state molar enthalpy divided by RT.
Returns the species standard state enthalpy divided by RT at the current temperature and pressure.
Returns
returns the species standard state enthalpy in unitless form
Reimplemented from PDSS.
Definition at line 176 of file PDSS_IdealGas.cpp.
References PDSS::m_h0_RT_ptr, and PDSS::m_spindex.
Referenced by PDSS_IdealGas::enthalpy_mole().
doublereal intEnergy_mole () const virtual
Return the molar internal Energy in units of J kmol-1.
Returns the species standard state internal Energy in J kmol-1 at the current temperature and pressure.
Returns
returns the species standard state internal Energy in J kmol-1
Reimplemented from PDSS.
Definition at line 187 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_h0_RT_ptr, PDSS::m_spindex, and PDSS::m_temp.
doublereal entropy_mole () const virtual
Return the molar entropy in units of J kmol-1 K-1.
Returns the species standard state entropy in J kmol-1 K-1 at the current temperature and pressure.
Returns
returns the species standard state entropy in J kmol-1 K-1
Reimplemented from PDSS.
Definition at line 199 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::entropy_R(), and Cantera::GasConstant.
doublereal entropy_R () const virtual
Return the standard state entropy divided by RT.
Returns the species standard state entropy divided by RT at the current temperature and pressure.
Returns
returns the species standard state entropy divided by RT
Reimplemented from PDSS.
Definition at line 206 of file PDSS_IdealGas.cpp.
References PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, and PDSS::m_spindex.
Referenced by PDSS_IdealGas::entropy_mole().
doublereal gibbs_mole () const virtual
Return the molar gibbs free energy in units of J kmol-1.
Returns the species standard state gibbs free energy in J kmol-1 at the current temperature and pressure.
Returns
returns the species standard state gibbs free energy in J kmol-1
Reimplemented from PDSS.
Definition at line 216 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS_IdealGas::gibbs_RT(), and PDSS::m_temp.
doublereal gibbs_RT () const virtual
Return the molar gibbs free energy divided by RT.
Returns the species standard state gibbs free energy divided by RT at the current temperature and pressure.
Returns
returns the species standard state gibbs free energy divided by RT
Reimplemented from PDSS.
Definition at line 224 of file PDSS_IdealGas.cpp.
References PDSS::m_g0_RT_ptr, PDSS::m_p0, PDSS::m_pres, and PDSS::m_spindex.
Referenced by PDSS_IdealGas::gibbs_mole().
doublereal cp_mole () const virtual
Return the molar const pressure heat capacity in units of J kmol-1 K-1.
Returns the species standard state Cp in J kmol-1 K-1 at the current temperature and pressure.
Returns
returns the species standard state Cp in J kmol-1 K-1
Reimplemented from PDSS.
Definition at line 234 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::cp_R(), and Cantera::GasConstant.
Referenced by PDSS_IdealGas::cv_mole().
doublereal cp_R () const virtual
Return the molar const pressure heat capacity divided by RT.
Returns the species standard state Cp divided by RT at the current temperature and pressure.
Returns
returns the species standard state Cp divided by RT
Reimplemented from PDSS.
Definition at line 241 of file PDSS_IdealGas.cpp.
References PDSS::m_cp0_R_ptr, and PDSS::m_spindex.
Referenced by PDSS_IdealGas::cp_mole(), and PDSS_IdealGas::cp_R_ref().
doublereal cv_mole () const virtual
Return the molar const volume heat capacity in units of J kmol-1 K-1.
Returns the species standard state Cv in J kmol-1 K-1 at the current temperature and pressure.
Returns
returns the species standard state Cv in J kmol-1 K-1
Reimplemented from PDSS.
Definition at line 264 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::cp_mole(), and Cantera::GasConstant.
doublereal molarVolume () const virtual
Return the molar volume at standard state.
Returns the species standard state molar volume at the current temperature and pressure
Returns
returns the standard state molar volume divided by R units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 247 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_pres, and PDSS::m_temp.
doublereal density () const virtual
Return the standard state density at standard state.
Returns the species standard state density at the current temperature and pressure
Returns
returns the standard state density units are kg m-3
Reimplemented from PDSS.
Definition at line 254 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_mw, PDSS::m_pres, and PDSS::m_temp.
doublereal gibbs_RT_ref () const virtual
Return the molar gibbs free energy divided by RT at reference pressure.
Returns the species reference state gibbs free energy divided by RT at the current temperature.
Returns
returns the reference state gibbs free energy divided by RT
Reimplemented from PDSS.
Definition at line 271 of file PDSS_IdealGas.cpp.
References PDSS::m_g0_RT_ptr, and PDSS::m_spindex.
doublereal enthalpy_RT_ref () const virtual
Return the molar enthalpy divided by RT at reference pressure.
Returns the species reference state enthalpy divided by RT at the current temperature.
Returns
returns the reference state enthalpy divided by RT
Reimplemented from PDSS.
Definition at line 276 of file PDSS_IdealGas.cpp.
References PDSS::m_h0_RT_ptr, and PDSS::m_spindex.
doublereal entropy_R_ref () const virtual
Return the molar entropy divided by R at reference pressure.
Returns the species reference state entropy divided by R at the current temperature.
Returns
returns the reference state entropy divided by R
Reimplemented from PDSS.
Definition at line 281 of file PDSS_IdealGas.cpp.
References PDSS::m_s0_R_ptr, and PDSS::m_spindex.
doublereal cp_R_ref () const virtual
Return the molar heat capacity divided by R at reference pressure.
Returns the species reference state heat capacity divided by R at the current temperature.
Returns
returns the reference state heat capacity divided by R
Reimplemented from PDSS.
Definition at line 286 of file PDSS_IdealGas.cpp.
References PDSS_IdealGas::cp_R().
doublereal molarVolume_ref () const virtual
Return the molar volume at reference pressure.
Returns the species reference state molar volume at the current temperature.
Returns
returns the reference state molar volume divided by R units are m**3 kmol-1.
Reimplemented from PDSS.
Definition at line 291 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_p0, and PDSS::m_temp.
doublereal pressure () const virtual
Returns the pressure (Pa)
Reimplemented from PDSS.
Definition at line 301 of file PDSS_IdealGas.cpp.
void setPressure (doublereal pres) virtual
Sets the pressure in the object.
Currently, this sets the pressure in the PDSS object. It is indeterminant what happens to the owning VPStandardStateTP object and to the VPSSMgr object.
Parameters
pres Pressure to be set (Pascal)
Reimplemented from PDSS.
Definition at line 307 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_gss_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_sss_R_ptr, PDSS::m_temp, and PDSS::m_Vss_ptr.
void setTemperature (doublereal temp) virtual
Set the internal temperature.
Parameters
temp Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 349 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_cp0_R_ptr, PDSS::m_cpss_R_ptr, PDSS::m_g0_RT_ptr, PDSS::m_gss_RT_ptr, PDSS::m_h0_RT_ptr, PDSS::m_hss_RT_ptr, PDSS::m_p0, PDSS::m_pres, PDSS::m_s0_R_ptr, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_sss_R_ptr, PDSS::m_temp, PDSS::m_V0_ptr, PDSS::m_Vss_ptr, and SpeciesThermo::update_one().
Referenced by PDSS_IdealGas::setState_TP(), and PDSS_IdealGas::setState_TR().
doublereal temperature () const
Return the current stored temperature.
Definition at line 343 of file PDSS_IdealGas.cpp.
References PDSS::m_temp, PDSS::m_vpssmgr_ptr, and VPSSMgr::temperature().
void setState_TP (doublereal temp, doublereal pres) virtual
Set the internal temperature and pressure.
Parameters
temp Temperature (Kelvin)
pres pressure (Pascals)
Reimplemented from PDSS.
Definition at line 365 of file PDSS_IdealGas.cpp.
References PDSS::m_pres, and PDSS_IdealGas::setTemperature().
void setState_TR (doublereal temp, doublereal rho) virtual
Set the internal temperature and density.
Parameters
temp Temperature (Kelvin)
rho Density (Pascals)
Reimplemented from PDSS.
Definition at line 371 of file PDSS_IdealGas.cpp.
References Cantera::GasConstant, PDSS::m_mw, PDSS::m_pres, and PDSS_IdealGas::setTemperature().
doublereal critTemperature () const virtual
critical temperature
Reimplemented from PDSS.
Definition at line 316 of file PDSS_IdealGas.cpp.
doublereal critPressure () const virtual
critical pressure
Reimplemented from PDSS.
Definition at line 323 of file PDSS_IdealGas.cpp.
doublereal critDensity () const virtual
critical density
Reimplemented from PDSS.
Definition at line 330 of file PDSS_IdealGas.cpp.
doublereal satPressure (doublereal t) virtual
saturation pressure
Parameters
t Temperature (Kelvin)
Reimplemented from PDSS.
Definition at line 378 of file PDSS_IdealGas.cpp.
void constructPDSSFile (VPStandardStateTP * vptp_ptr, size_t spindex, const std::string & inputFile, const std::string & id)
Initialization of a PDSS object using an input XML file.
This routine is a precursor to constructPDSSXML(XML_Node*) routine, which does most of the work.
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
inputFile XML file containing the description of the phase
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 118 of file PDSS_IdealGas.cpp.
References XML_Node::build(), PDSS_IdealGas::constructPDSSXML(), Cantera::findInputFile(), and Cantera::findXMLPhase().
Referenced by PDSS_IdealGas::PDSS_IdealGas().
void constructPDSSXML (VPStandardStateTP * vptp_ptr, size_t spindex, const XML_Node & phaseNode, const std::string & id)
Initialization of a PDSS object using an xml tree.
This routine is a driver for the initialization of the object.
basic logic: initThermo() (cascade) getStuff from species Part of XML file initThermoXML(phaseNode) (cascade)
Parameters
vptp_ptr Pointer to the Variable pressure ThermoPhase object This object must have already been malloced.
spindex Species index within the phase
phaseNode Reference to the phase Information for the phase that owns this species.
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Definition at line 110 of file PDSS_IdealGas.cpp.
Referenced by PDSS_IdealGas::constructPDSSFile(), and PDSS_IdealGas::PDSS_IdealGas().
void initThermoXML (const XML_Node & phaseNode, const std::string & id) virtual
Initialization routine for the PDSS object based on the phaseNode.
This is a cascading call, where each level should call the the parent level.
Parameters
phaseNode Reference to the phase Information for the phase that owns this species.
id Optional parameter identifying the name of the phase. If none is given, the first XML phase element will be used.
Reimplemented from PDSS.
Definition at line 150 of file PDSS_IdealGas.cpp.
References PDSS::initThermoXML().
void initThermo () virtual
Initialization routine for all of the shallow pointers.
This is a cascading call, where each level should call the the parent level.
The initThermo() routines get called before the initThermoXML() routines from the constructPDSSXML() routine.
Calls initPtrs();
Reimplemented from PDSS.
Definition at line 155 of file PDSS_IdealGas.cpp.
References PDSS::initThermo(), PDSS::m_maxTemp, PDSS::m_minTemp, PDSS::m_p0, PDSS::m_spindex, PDSS::m_spthermo, PDSS::m_tp, SpeciesThermo::maxTemp(), SpeciesThermo::minTemp(), SpeciesThermo::refPressure(), and ThermoPhase::speciesThermo().
The documentation for this class was generated from the following files:
PDSS_IdealGas.h
PDSS_IdealGas.cpp