Cantera: PhaseCombo_Interaction Class Reference
PhaseCombo_Interaction Class Reference
Thermodynamic Properties
PhaseCombo_Interaction is a derived class of GibbsExcessVPSSTP that employs the Margules approximation for the excess gibbs free energy while eliminating the entropy of mixing term.
#include <PhaseCombo_Interaction.h>
Public Member Functions
PhaseCombo_Interaction ()
Constructor.
PhaseCombo_Interaction (const std::string &inputFile, const std::string &id="")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an xml input file.
PhaseCombo_Interaction (XML_Node &phaseRef, const std::string &id="")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an XML database.
PhaseCombo_Interaction (int testProb)
Special constructor for a hard-coded problem.
PhaseCombo_Interaction (const PhaseCombo_Interaction &b)
Copy constructor.
PhaseCombo_Interaction & operator= (const PhaseCombo_Interaction &b)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
Utilities
virtual int eosType () const
Equation of state type flag.
Molar Thermodynamic Properties
virtual doublereal enthalpy_mole () const
Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy. Units: J/kmol.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure. Units: J/kmol/K.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume. Units: J/kmol/K.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Returns an array of partial molar entropies for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getd2lnActCoeffdT2 (doublereal *d2lnActCoeffdT2) const
Get the array of temperature second derivatives of the log activity coefficients.
virtual void getdlnActCoeffdT (doublereal *dlnActCoeffdT) const
Get the array of temperature derivatives of the log activity coefficients.
Initialization
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
virtual void initThermo ()
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
Derivatives of Thermodynamic Variables needed for Applications
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients w.r.t.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of derivatives of the log activity coefficients wrt mole numbers - diagonal only.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the ln species mole numbers.
Public Member Functions inherited from GibbsExcessVPSSTP
GibbsExcessVPSSTP ()
GibbsExcessVPSSTP (const GibbsExcessVPSSTP &b)
Copy constructor.
GibbsExcessVPSSTP & operator= (const GibbsExcessVPSSTP &b)
Assignment operator.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getdlnActCoeffdlnX (doublereal *dlnActCoeffdlnX) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual const vector_fp & getPartialMolarVolumesVector () const
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of the standard state of one species in the phase (J kmol-1)
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Protected Attributes
size_t numBinaryInteractions_
number of binary interaction expressions
vector_fp m_HE_b_ij
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_HE_c_ij
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_HE_d_ij
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_b_ij
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_c_ij
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_SE_d_ij
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_b_ij
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_c_ij
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VHE_d_ij
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_b_ij
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_c_ij
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
vector_fp m_VSE_d_ij
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
std::vector< size_t > m_pSpecies_A_ij
vector of species indices representing species A in the interaction
std::vector< size_t > m_pSpecies_B_ij
vector of species indices representing species B in the interaction
int formMargules_
form of the Margules interaction expression
int formTempModel_
form of the temperature dependence of the Margules interaction expression
Protected Attributes inherited from GibbsExcessVPSSTP
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
std::vector< doublereal > lnActCoeff_Scaled_
Storage for the current values of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdT_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > d2lnActCoeffdT2_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnN_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnX_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Array2D dlnActCoeffdlnN_
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
std::vector< doublereal > m_pp
Temporary storage space that is fair game.
Protected Attributes inherited from VPStandardStateTP
doublereal m_Pcurrent
Current value of the pressure - state variable.
doublereal m_Tlast_ss
The last temperature at which the standard statethermodynamic properties were calculated at.
doublereal m_Plast_ss
The last pressure at which the Standard State thermodynamic properties were calculated at.
doublereal m_P0
VPSSMgr * m_VPSS_ptr
Pointer to the VPSS manager that calculates all of the standard state info efficiently.
std::vector< PDSS * > m_PDSS_storage
Storage for the PDSS objects for the species.
Protected Attributes inherited from ThermoPhase
SpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase.
vector_fp m_lambdaRRT
Vector of element potentials.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
std::vector< doublereal > xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
Private Member Functions
void readXMLBinarySpecies (XML_Node &xmlBinarySpecies)
Process an XML node called "binaryNeutralSpeciesParameters".
void resizeNumInteractions (const size_t num)
Resize internal arrays within the object that depend upon the number of binary Margules interaction terms.
void initLengths ()
Initialize lengths of local variables after all species have been identified.
void s_update_lnActCoeff () const
Update the activity coefficients.
void s_update_dlnActCoeff_dT () const
Update the derivative of the log of the activity coefficients wrt T.
void s_update_dlnActCoeff_dlnX_diag () const
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
void s_update_dlnActCoeff_dlnN_diag () const
Update the derivative of the log of the activity coefficients wrt log(moles) - diagonal only.
void s_update_dlnActCoeff_dlnN () const
Update the derivative of the log of the activity coefficients wrt log(moles_m)
doublereal err (const std::string &msg) const
Error function.
Additional Inherited Members
Protected Member Functions inherited from GibbsExcessVPSSTP
double checkMFSum (const doublereal *const x) const
utility routine to check mole fraction sum
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Detailed Description
PhaseCombo_Interaction is a derived class of GibbsExcessVPSSTP that employs the Margules approximation for the excess gibbs free energy while eliminating the entropy of mixing term.
PhaseCombo_Interaction derives from class GibbsExcessVPSSTP which is derived from VPStandardStateTP, and overloads the virtual methods defined there with ones that use expressions appropriate for the Margules Excess gibbs free energy approximation. The reader should refer to the MargulesVPSSTP class for information on that class. This class in addition adds a term to the activity coefficient that eliminates the ideal solution mixing term within the chemical potential. This is a very radical thing to do, but it is supported by experimental evidence under some conditions.
The independent unknowns are pressure, temperature, and mass fraction.
Several concepts are introduced. The first concept is that there are temporary variables for holding the species standard state values of Cp, H, S, G, and V at the last temperature and pressure called. These functions are not recalculated if a new call is made using the previous temperature and pressure. Currently, these variables and the calculation method are handled by the VPSSMgr class, for which VPStandardStateTP owns a pointer to.
To support the above functionality, pressure and temperature variables, m_plast_ss and m_tlast_ss, are kept which store the last pressure and temperature used in the evaluation of standard state properties.
This class is introduced to represent specific conditions observed in thermal batteries. HOwever, it may be physically motivated to represent conditions where there may be a mixture of compounds that are not "mixed" at the molecular level. Therefore, there is no mixing term.
The lack of a mixing term has profound effects. First, the mole fraction of a species can now be identically zero due to thermodynamic considerations. The phase behaves more like a series of phases. That's why we named it PhaseCombo.
Specification of Species Standard State Properties
All species are defined to have standard states that depend upon both the temperature and the pressure. The Margules approximation assumes symmetric standard states, where all of the standard state assume that the species are in pure component states at the temperature and pressure of the solution. I don't think it prevents, however, some species from being dilute in the solution.
Specification of Solution Thermodynamic Properties
The molar excess Gibbs free energy is given by the following formula which is a sum over interactions i. Each of the interactions are binary interactions involving two of the species in the phase, denoted, Ai and Bi. This is the generalization of the Margules formulation for a phase that has more than 2 species. The second term in the excess gibbs free energy is a negation of the ideal solution's mixing term.
\[ G^E = \sum_i \left(H_{Ei} - T S_{Ei} \right) - \sum_i \left(n_i R T \ln{X_i} \right) \]
\[ H^E_i = n X_{Ai} X_{Bi} \left(h_{o,i} + h_{1,i} X_{Bi} \right) \]
\[ S^E_i = n X_{Ai} X_{Bi} \left(s_{o,i} + s_{1,i} X_{Bi} \right) \]
where n is the total moles in the solution.
The activity of a species defined in the phase is given by an excess Gibbs free energy formulation.
\[ a_k = \gamma_k X_k \]
where
\[ R T \ln(\gamma_k)= \frac{d(n G^E)}{d(n_k)}\Bigg|_{n_i} \]
Taking the derivatives results in the following expression
\[ R T \ln(\gamma_k)= \sum_i \left(\left(\delta_{Ai,k} X_{Bi} + \delta_{Bi,k} X_{Ai} - X_{Ai} X_{Bi} \right) \left(g^E_{o,i} + g^E_{1,i} X_{Bi} \right) + \left(\delta_{Bi,k} - X_{Bi} \right) X_{Ai} X_{Bi} g^E_{1,i} \right) - RT \ln{X_k} \]
where \(g^E_{o,i} = h_{o,i} - T s_{o,i} \) and \(g^E_{1,i} = h_{1,i} - T s_{1,i} \) and where \(X_k \) is the mole fraction of species k.
This object inherits from the class VPStandardStateTP. Therefore, the specification and calculation of all standard state and reference state values are handled at that level. Various functional forms for the standard state are permissible. The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T, P) + R T \ln(\gamma_k X_k) \]
The partial molar entropy for species k is given by the following relation,
\[ \tilde{s}_k(T,P) = s^o_k(T,P) - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
The partial molar enthalpy for species k is given by
\[ \tilde{h}_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
The partial molar volume for species k is
\[ \tilde V_k(T,P) = V^o_k(T,P) + R T \frac{d \ln(\gamma_k) }{dP} \]
The partial molar Heat Capacity for species k is
\[ \tilde{C}_{p,k}(T,P) = C^o_{p,k}(T,P) - 2 R T \frac{d \ln(\gamma_k)}{dT} - R T^2 \frac{d^2 \ln(\gamma_k) }{{dT}^2} \]
Application within Kinetics Managers
\(C^a_k\) are defined such that \(a_k = C^a_k / C^s_k, \) where \(C^s_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. The activity concentration, \(C^a_k \),is given by the following expression.
\[ C^a_k = C^s_k X_k = \frac{P}{R T} X_k \]
The standard concentration for species k is independent of k and equal to
\[ C^s_k = C^s = \frac{P}{R T} \]
For example, a bulk-phase binary gas reaction between species j and k, producing a new gas species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^s a_j) (C^s a_k) \]
where
\[ C_j^a = C^s a_j \mbox{\quad and \quad} C_k^a = C^s a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^s \) is the standard concentration. \(a_j \) is the activity of species j which is equal to the mole fraction of j.
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K_a^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K_a^{o,1} \) is the dimensionless form of the equilibrium constant, associated with the pressure dependent standard states \(\mu^o_l(T,P) \) and their associated activities, \(a_l \), repeated here:
\[ \mu_l(T,P) = \mu^o_l(T, P) + R T \log(a_l) \]
We can switch over to expressing the equilibrium constant in terms of the reference state chemical potentials
\[ K_a^{o,1} = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{P} \]
The concentration equilibrium constant, \(K_c \), may be obtained by changing over to activity concentrations. When this is done:
\[ \frac{C^a_j C^a_k}{ C^a_l} = C^o K_a^{o,1} = K_c^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{RT} \]
Kinetics managers will calculate the concentration equilibrium constant, \(K_c \), using the second and third part of the above expression as a definition for the concentration equilibrium constant.
For completeness, the pressure equilibrium constant may be obtained as well
\[ \frac{P_j P_k}{ P_l P_{ref}} = K_p^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) \]
\(K_p \) is the simplest form of the equilibrium constant for ideal gases. However, it isn't necessarily the simplest form of the equilibrium constant for other types of phases; \(K_c \) is used instead because it is completely general.
The reverse rate of progress may be written down as
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C^o a_l) \]
where we can use the concept of microscopic reversibility to write the reverse rate constant in terms of the forward reate constant and the concentration equilibrium constant, \(K_c \).
\[ k^{-1} = k^1 K^1_c \]
\(k^{-1} \) has units of s-1.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new PhaseCombo_Interaction object may be created by the following code snippet:
XML_Node *xc = get_XML_File("LiFeS_X_combo.xml");
XML_Node * const xs = xc->findNameID("phase", "LiFeS_X");
ThermoPhase *l_tp = newPhase(*xs);
PhaseCombo_Interaction *LiFeS_X_solid = dynamic_cast <PhaseCombo_Interaction *>(l_tp);
or by the following code
std::string id = "LiFeS_X";
Cantera::ThermoPhase *LiFeS_X_Phase = Cantera::newPhase("LiFeS_X_combo.xml", id);
PhaseCombo_Interaction *LiFeS_X_solid = dynamic_cast <PhaseCombo_Interaction *>(l_tp);
or by the following constructor:
XML_Node *xc = get_XML_File("LiFeS_X_combo.xml");
XML_Node * const xs = xc->findNameID("phase", "LiFeS_X");
PhaseCombo_Interaction *LiFeS_X_solid = new PhaseCombo_Interaction(*xs);
XML Example
An example of an XML Element named phase setting up a PhaseCombo_Interaction object named LiFeS_X is given below.
<phase dim="3" id="LiFeS_X">
  <elementArray datasrc="elements.xml">
     Li Fe S
  </elementArray>
  <speciesArray datasrc="#species_LiFeS">
    LiTFe1S2(S)  Li2Fe1S2(S)
  </speciesArray>
  <thermo model="PhaseCombo_Interaction">
    <activityCoefficients model="Margules" TempModel="constant">
      <binaryNeutralSpeciesParameters speciesA="LiTFe1S2(S)" speciesB="Li2Fe1S2(S)">
        <excessEnthalpy model="poly_Xb" terms="2" units="kJ/mol">
            84.67069219, -269.1959421
        </excessEnthalpy>
        <excessEntropy  model="poly_Xb" terms="2" units="J/mol/K">
            100.7511565, -361.4222659
        </excessEntropy>
        <excessVolume_Enthalpy model="poly_Xb" terms="2" units="ml/mol">
             0, 0
        </excessVolume_Enthalpy>
        <excessVolume_Entropy  model="poly_Xb" terms="2" units="ml/mol/K">
             0, 0
        </excessVolume_Entropy>
      </binaryNeutralSpeciesParameters>
    </activityCoefficients>
  </thermo>
  <transport model="none"/>
  <kinetics model="none"/>
</phase>
The model attribute "PhaseCombo_Interaction" of the thermo XML element identifies the phase as being of the type handled by the PhaseCombo_Interaction object.
Definition at line 333 of file PhaseCombo_Interaction.h.
Constructor & Destructor Documentation
PhaseCombo_Interaction ()
Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements.xml file. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 21 of file PhaseCombo_Interaction.cpp.
Referenced by PhaseCombo_Interaction::duplMyselfAsThermoPhase().
PhaseCombo_Interaction (const std::string & inputFile, const std::string & id = "")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an xml input file.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 29 of file PhaseCombo_Interaction.cpp.
References ThermoPhase::initThermoFile().
PhaseCombo_Interaction (XML_Node & phaseRef, const std::string & id = "")
Construct and initialize a PhaseCombo_Interaction ThermoPhase object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 39 of file PhaseCombo_Interaction.cpp.
References Cantera::findXMLPhase(), and Cantera::importPhase().
PhaseCombo_Interaction (int testProb)
Special constructor for a hard-coded problem.
Parameters
testProb Hard-coded value. Only the value of 1 is used. It's for a LiKCl system -> test to predict the eutectic and liquidus correctly.
Definition at line 90 of file PhaseCombo_Interaction.cpp.
References ThermoPhase::initThermoFile(), PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, Cantera::npos, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::speciesIndex().
PhaseCombo_Interaction (const PhaseCombo_Interaction & b)
Copy constructor.
Parameters
b class to be copied
Definition at line 49 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::operator=().
Member Function Documentation
PhaseCombo_Interaction & operator= (const PhaseCombo_Interaction & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 55 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::formMargules_, PhaseCombo_Interaction::formTempModel_, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, PhaseCombo_Interaction::numBinaryInteractions_, and GibbsExcessVPSSTP::operator=().
Referenced by PhaseCombo_Interaction::PhaseCombo_Interaction().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate thermophase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 85 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::PhaseCombo_Interaction().
int eosType () const virtual
Equation of state type flag.
The ThermoPhase base class returns zero. Subclasses should define this to return a unique non-zero value. Known constants defined for this purpose are listed in mix_defs.h.
Reimplemented from ThermoPhase.
Definition at line 154 of file PhaseCombo_Interaction.cpp.
Referenced by PhaseCombo_Interaction::err().
doublereal enthalpy_mole () const virtual
Molar enthalpy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 215 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::getPartialMolarEnthalpies(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
doublereal entropy_mole () const virtual
Molar entropy. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 227 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::getPartialMolarEntropies(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 239 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::getPartialMolarCp(), GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
Referenced by PhaseCombo_Interaction::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume. Units: J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 251 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::cp_mole(), and Cantera::GasConstant.
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 163 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_lnActCoeff().
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 191 of file PhaseCombo_Interaction.cpp.
References Cantera::GasConstant, VPStandardStateTP::getStandardChemPotentials(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::s_update_lnActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getElectrochemPotentials().
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the molality-based activity coefficient wrt temperature
\[ \bar h_k(T,P) = h^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} \]
Parameters
hbar Vector of returned partial molar enthalpies (length m_kk, units = J/kmol)
Reimplemented from ThermoPhase.
Definition at line 256 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEnthalpy_RT(), Phase::m_kk, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), and Phase::temperature().
Referenced by PhaseCombo_Interaction::enthalpy_mole().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} \]
Parameters
sbar Vector of returned partial molar entropies (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Definition at line 307 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getEntropy_R(), GibbsExcessVPSSTP::lnActCoeff_Scaled_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), Cantera::SmallNumber, and Phase::temperature().
Referenced by PhaseCombo_Interaction::entropy_mole().
void getPartialMolarCp (doublereal * cpbar) const virtual
Returns an array of partial molar entropies for the species in the mixture.
Units (J/kmol)
For this phase, the partial molar enthalpies are equal to the standard state enthalpies modified by the derivative of the activity coefficient wrt temperature
\[ ??????????????? \bar s_k(T,P) = s^o_k(T,P) - R T^2 \frac{d \ln(\gamma_k)}{dT} - R \ln(\gamma_k X_k) - R T \frac{d \ln(\gamma_k) }{dT} ??????????????? \]
Parameters
cpbar Vector of returned partial molar heat capacities (length m_kk, units = J/kmol/K)
Reimplemented from ThermoPhase.
Definition at line 282 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, VPStandardStateTP::getCp_R(), Phase::m_kk, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), PhaseCombo_Interaction::s_update_lnActCoeff(), and Phase::temperature().
Referenced by PhaseCombo_Interaction::cp_mole().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Frequently, for this class of thermodynamics representations, the excess Volume due to mixing is zero. Here, we set it as a default. It may be overridden in derived classes.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 334 of file PhaseCombo_Interaction.cpp.
References VPStandardStateTP::getStandardVolumes(), Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk., units = J/kmol
Definition at line 182 of file PhaseCombo_Interaction.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), PhaseCombo_Interaction::getChemPotentials(), and Phase::m_kk.
void getd2lnActCoeffdT2 (doublereal * d2lnActCoeffdT2) const virtual
Get the array of temperature second derivatives of the log activity coefficients.
This function is a virtual class, but it first appears in GibbsExcessVPSSTP class and derived classes from GibbsExcessVPSSTP.
units = 1/Kelvin
Parameters
d2lnActCoeffdT2 Output vector of temperature 2nd derivatives of the log Activity Coefficients. length = m_kk
Definition at line 535 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dT().
void getdlnActCoeffdT (doublereal * dlnActCoeffdT) const virtual
Get the array of temperature derivatives of the log activity coefficients.
This function is a virtual class, but it first appears in GibbsExcessVPSSTP class and derived classes from GibbsExcessVPSSTP.
units = 1/Kelvin
Parameters
dlnActCoeffdT Output vector of temperature derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from GibbsExcessVPSSTP.
Definition at line 527 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dT().
void initThermo () virtual
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from GibbsExcessVPSSTP.
Definition at line 377 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::initLengths(), and GibbsExcessVPSSTP::initThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 389 of file PhaseCombo_Interaction.cpp.
References XML_Node::attrib(), XML_Node::child(), XML_Node::hasChild(), XML_Node::id(), VPStandardStateTP::initThermoXML(), Cantera::lowercase(), XML_Node::name(), XML_Node::nChildren(), PhaseCombo_Interaction::readXMLBinarySpecies(), and Phase::size().
void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal * dlnActCoeffds) const virtual
Get the change in activity coefficients w.r.t.
change in state (temp, mole fraction, etc.) along a line in parameter space or along a line in physical space
Parameters
dTds Input of temperature change along the path
dXds Input vector of changes in mole fraction along the path. length = m_kk Along the path length it must be the case that the mole fractions sum to one.
dlnActCoeffds Output vector of the directional derivatives of the log Activity Coefficients along the path. length = m_kk units are 1/units(s). if s is a physical coordinate then the units are 1/m.
Reimplemented from ThermoPhase.
Definition at line 543 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), Cantera::SmallNumber, and Phase::temperature().
void getdlnActCoeffdlnX_diag (doublereal * dlnActCoeffdlnX_diag) const virtual
Get the array of log concentration-like derivatives of the log activity coefficients - diagonal component.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the mole fraction.
units = dimensionless
Parameters
dlnActCoeffdlnX_diag Output vector of the diagonal component of the log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from ThermoPhase.
Definition at line 745 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag().
void getdlnActCoeffdlnN_diag (doublereal * dlnActCoeffdlnN_diag) const virtual
Get the array of derivatives of the log activity coefficients wrt mole numbers - diagonal only.
This function is a virtual method. For ideal mixtures (unity activity coefficients), this can return zero. Implementations should take the derivative of the logarithm of the activity coefficient with respect to the logarithm of the concentration-like variable (i.e. mole fraction, molality, etc.) that represents the standard state.
units = dimensionless
Parameters
dlnActCoeffdlnN_diag Output vector of the diagonal entries for the log(mole fraction) derivatives of the log Activity Coefficients. length = m_kk
Reimplemented from VPStandardStateTP.
Definition at line 737 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag().
void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN) virtual
Get the array of derivatives of the log activity coefficients with respect to the ln species mole numbers.
Implementations should take the derivative of the logarithm of the activity coefficient with respect to a log of a species mole number (with all other species mole numbers held constant)
units = 1 / kmol
dlnActCoeffdlnN[ ld * k + m] will contain the derivative of log act_coeff for the mth species with respect to the number of moles of the kth species.
\[ \frac{d \ln(\gamma_m) }{d \ln(n_k) }\Bigg|_{n_i} \]
Parameters
ld Number of rows in the matrix
dlnActCoeffdlnN Output vector of derivatives of the log Activity Coefficients. length = m_kk * m_kk
Reimplemented from GibbsExcessVPSSTP.
Definition at line 753 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Phase::m_kk, and PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN().
void readXMLBinarySpecies (XML_Node & xmlBinarySpecies) private
Process an XML node called "binaryNeutralSpeciesParameters".
This node contains all of the parameters necessary to describe the Margules model for a particular binary interaction. This function reads the XML file and writes the coefficients it finds to an internal data structures.
Parameters
xmlBinarySpecies Reference to the XML_Node named "binaryNeutralSpeciesParameters" containing the binary interaction
Definition at line 784 of file PhaseCombo_Interaction.cpp.
References XML_Node::attrib(), Phase::charge(), XML_Node::child(), ctml::getFloatArray(), Cantera::lowercase(), PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, XML_Node::name(), XML_Node::nChildren(), Cantera::npos, PhaseCombo_Interaction::numBinaryInteractions_, PhaseCombo_Interaction::resizeNumInteractions(), Phase::speciesIndex(), and Phase::speciesName().
Referenced by PhaseCombo_Interaction::initThermoXML().
void resizeNumInteractions (const size_t num) private
Resize internal arrays within the object that depend upon the number of binary Margules interaction terms.
Parameters
num Number of binary Margules interaction terms
Definition at line 764 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, PhaseCombo_Interaction::m_HE_d_ij, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, PhaseCombo_Interaction::m_SE_d_ij, PhaseCombo_Interaction::m_VHE_b_ij, PhaseCombo_Interaction::m_VHE_c_ij, PhaseCombo_Interaction::m_VHE_d_ij, PhaseCombo_Interaction::m_VSE_b_ij, PhaseCombo_Interaction::m_VSE_c_ij, PhaseCombo_Interaction::m_VSE_d_ij, Cantera::npos, and PhaseCombo_Interaction::numBinaryInteractions_.
Referenced by PhaseCombo_Interaction::readXMLBinarySpecies().
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 383 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Phase::m_kk, Phase::nSpecies(), and Array2D::resize().
Referenced by PhaseCombo_Interaction::initThermo().
void s_update_lnActCoeff () const private
Update the activity coefficients.
This function will be called to update the internally stored natural logarithm of the activity coefficients
Definition at line 456 of file PhaseCombo_Interaction.cpp.
References Cantera::GasConstant, GibbsExcessVPSSTP::lnActCoeff_Scaled_, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Cantera::SmallNumber, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getActivityCoefficients(), PhaseCombo_Interaction::getChemPotentials(), PhaseCombo_Interaction::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), and PhaseCombo_Interaction::getPartialMolarEntropies().
void s_update_dlnActCoeff_dT () const private
Update the derivative of the log of the activity coefficients wrt T.
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt temperature.
Definition at line 497 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::d2lnActCoeffdT2_Scaled_, GibbsExcessVPSSTP::dlnActCoeffdT_Scaled_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getd2lnActCoeffdT2(), PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getdlnActCoeffdT(), PhaseCombo_Interaction::getPartialMolarCp(), PhaseCombo_Interaction::getPartialMolarEnthalpies(), and PhaseCombo_Interaction::getPartialMolarEntropies().
void s_update_dlnActCoeff_dlnX_diag () const private
Update the derivative of the log of the activity coefficients wrt log(mole fraction)
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the mole fractions.
Definition at line 713 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnX_diag_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnX_diag().
void s_update_dlnActCoeff_dlnN_diag () const private
Update the derivative of the log of the activity coefficients wrt log(moles) - diagonal only.
This function will be called to update the internally stored diagonal entries for the derivative of the natural logarithm of the activity coefficients wrt logarithm of the moles.
Definition at line 595 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_diag_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Cantera::SmallNumber, and Phase::temperature().
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnN_diag().
void s_update_dlnActCoeff_dlnN () const private
Update the derivative of the log of the activity coefficients wrt log(moles_m)
This function will be called to update the internally stored derivative of the natural logarithm of the activity coefficients wrt logarithm of the mole number of species
Definition at line 646 of file PhaseCombo_Interaction.cpp.
References GibbsExcessVPSSTP::dlnActCoeffdlnN_, Cantera::GasConstant, PhaseCombo_Interaction::m_HE_b_ij, PhaseCombo_Interaction::m_HE_c_ij, Phase::m_kk, PhaseCombo_Interaction::m_pSpecies_A_ij, PhaseCombo_Interaction::m_pSpecies_B_ij, PhaseCombo_Interaction::m_SE_b_ij, PhaseCombo_Interaction::m_SE_c_ij, GibbsExcessVPSSTP::moleFractions_, PhaseCombo_Interaction::numBinaryInteractions_, Cantera::SmallNumber, Phase::temperature(), and Array2D::zero().
Referenced by PhaseCombo_Interaction::getdlnActCoeffdlnN().
doublereal err (const std::string & msg) const private
Error function.
Print an error string and exit
Parameters
msg Message to be printed
Definition at line 370 of file PhaseCombo_Interaction.cpp.
References PhaseCombo_Interaction::eosType(), and Cantera::int2str().
Member Data Documentation
size_t numBinaryInteractions_ protected
number of binary interaction expressions
Definition at line 755 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_b_ij mutable protected
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 759 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_c_ij mutable protected
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 763 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_HE_d_ij mutable protected
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 767 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_SE_b_ij mutable protected
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 771 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_SE_c_ij mutable protected
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 775 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), and PhaseCombo_Interaction::s_update_lnActCoeff().
vector_fp m_SE_d_ij mutable protected
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 779 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_b_ij mutable protected
Enthalpy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 783 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_c_ij mutable protected
Enthalpy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 787 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VHE_d_ij mutable protected
Enthalpy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 791 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_b_ij mutable protected
Entropy term for the binary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 795 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_c_ij mutable protected
Entropy term for the ternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 799 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), and PhaseCombo_Interaction::resizeNumInteractions().
vector_fp m_VSE_d_ij mutable protected
Entropy term for the quaternary mole fraction interaction of the excess gibbs free energy expression.
Definition at line 803 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), and PhaseCombo_Interaction::resizeNumInteractions().
std::vector<size_t> m_pSpecies_A_ij protected
vector of species indices representing species A in the interaction
Each Margules excess Gibbs free energy term involves two species, A and B. This vector identifies species A.
Definition at line 810 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
std::vector<size_t> m_pSpecies_B_ij protected
vector of species indices representing species B in the interaction
Each Margules excess Gibbs free energy term involves two species, A and B. This vector identifies species B.
Definition at line 817 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::getdlnActCoeffds(), PhaseCombo_Interaction::getPartialMolarVolumes(), PhaseCombo_Interaction::operator=(), PhaseCombo_Interaction::PhaseCombo_Interaction(), PhaseCombo_Interaction::readXMLBinarySpecies(), PhaseCombo_Interaction::resizeNumInteractions(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnN_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dlnX_diag(), PhaseCombo_Interaction::s_update_dlnActCoeff_dT(), and PhaseCombo_Interaction::s_update_lnActCoeff().
int formMargules_ protected
form of the Margules interaction expression
Currently there is only one form.
Definition at line 823 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=().
int formTempModel_ protected
form of the temperature dependence of the Margules interaction expression
Currently there is only one form -> constant wrt temperature.
Definition at line 829 of file PhaseCombo_Interaction.h.
Referenced by PhaseCombo_Interaction::operator=().
The documentation for this class was generated from the following files:
PhaseCombo_Interaction.h
PhaseCombo_Interaction.cpp