Cantera: PecosTransport Class Reference
PecosTransport Class Reference
Class PecosTransport implements mixture-averaged transport properties for ideal gas mixtures.
#include <PecosTransport.h>
Public Member Functions
virtual int model () const
Transport model.
virtual doublereal viscosity ()
Viscosity of the mixture.
virtual void getSpeciesViscosities (doublereal *const visc)
Returns the pure species viscosities.
virtual void getThermalDiffCoeffs (doublereal *const dt)
Return the thermal diffusion coefficients.
virtual doublereal thermalConductivity ()
The thermal conductivity is computed using the Wilke mixture rule.
virtual void getBinaryDiffCoeffs (const size_t ld, doublereal *const d)
Returns the matrix of binary diffusion coefficients [m^2/s].
virtual void getMixDiffCoeffs (doublereal *const d)
Mixture-averaged diffusion coefficients [m^2/s].
void getMixDiffCoeffsMole (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
void getMixDiffCoeffsMass (doublereal *const d)
Returns the mixture-averaged diffusion coefficients [m^2/s].
virtual void getMobilities (doublereal *const mobil)
Get the Electrical mobilities (m^2/V/s).
virtual void update_T ()
virtual void update_C ()
virtual void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual bool initGas (GasTransportParams &tr)
Initialize the transport object.
void read_blottner_transport_table ()
Reads the transport table specified (currently defaults to internal file)
struct GasTransportData getGasTransportData (int)
Return a structure containing all of the pertinent parameters about a species that was used to construct the Transport properties in this object.
virtual Transport * duplMyselfAsTransport () const
Duplication routine for objects which inherit from Transport.
thermo_t & thermo ()
Phase object.
bool ready ()
Returns true if the transport manager is ready for use.
void setNDim (const int ndim)
Set the number of dimensions to be expected in flux expressions.
size_t nDim () const
Return the number of dimensions in flux expressions.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
virtual doublereal getElectricConduct ()
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
virtual void getElectricCurrent (int ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_V, doublereal *current)
Compute the electric current density in A/m^2.
virtual void getSpeciesFluxesES (size_t ndim, const doublereal *grad_T, size_t ldx, const doublereal *grad_X, size_t ldf, const doublereal *grad_Phi, doublereal *fluxes)
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
virtual void getSpeciesVdiff (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
virtual void getSpeciesVdiffES (size_t ndim, const doublereal *grad_T, int ldx, const doublereal *grad_X, int ldf, const doublereal *grad_Phi, doublereal *Vdiff)
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const cfluxes)
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMassFluxes (const doublereal *state1, const doublereal *state2, doublereal delta, doublereal *mfluxes)
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d)
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
virtual void setParameters (const int type, const int k, const doublereal *const p)
Set model parameters for derived classes.
void setVelocityBasis (VelocityBasis ivb)
Sets the velocity basis.
VelocityBasis getVelocityBasis () const
Gets the velocity basis.
Transport Properties
virtual doublereal bulkViscosity ()
The bulk viscosity in Pa-s.
virtual doublereal ionConductivity ()
The ionic conductivity in 1/ohm/m.
virtual void getSpeciesIonConductivity (doublereal *const ionCond)
Returns the pure species ionic conductivity.
virtual void mobilityRatio (double *mobRat)
Returns the pointer to the mobility ratios of the species in the phase.
virtual void getSpeciesMobilityRatio (double **mobRat)
Returns the pure species limit of the mobility ratios.
virtual void selfDiffusion (doublereal *const selfDiff)
Returns the self diffusion coefficients of the species in the phase.
virtual void getSpeciesSelfDiffusion (double **selfDiff)
Returns the pure species self diffusion in solution of each species.
virtual doublereal electricalConductivity ()
The electrical conductivity (Siemens/m).
virtual void getFluidMobilities (doublereal *const mobil_f)
Get the fluid mobilities (s kmol/kg).
Protected Member Functions
PecosTransport ()
default constructor
Protected Attributes
thermo_t * m_thermo
pointer to the object representing the phase
bool m_ready
true if finalize has been called
size_t m_nDim
Number of dimensions used in flux expressions.
int m_velocityBasis
Velocity basis from which diffusion velocities are computed.
Private Member Functions
doublereal pressure_ig () const
Calculate the pressure from the ideal gas law.
void updateThermal_T ()
void updateViscosity_T ()
Update the temperature-dependent viscosity terms.
void updateCond_T ()
Update the temperature-dependent parts of the mixture-averaged thermal conductivity.
void updateSpeciesViscosities ()
Update the pure-species viscosities.
void updateDiff_T ()
Update the binary diffusion coefficients.
void correctBinDiffCoeffs ()
Private Attributes
int m_nsp
vector_fp m_mw
std::vector< vector_fp > m_visccoeffs
std::vector< vector_fp > m_condcoeffs
std::vector< vector_fp > m_diffcoeffs
vector_fp m_polytempvec
double a [500]
double b [500]
double c [500]
DenseMatrix m_bdiff
vector_fp m_visc
vector_fp m_sqvisc
vector_fp m_cond
vector_fp m_molefracs
std::vector< std::vector< int > > m_poly
std::vector< vector_fp > m_astar_poly
std::vector< vector_fp > m_bstar_poly
std::vector< vector_fp > m_cstar_poly
std::vector< vector_fp > m_om22_poly
DenseMatrix m_astar
DenseMatrix m_bstar
DenseMatrix m_cstar
DenseMatrix m_om22
DenseMatrix m_phi
DenseMatrix m_wratjk
DenseMatrix m_wratkj1
vector_fp m_zrot
vector_fp m_crot
vector_fp m_cinternal
vector_fp m_eps
vector_fp m_alpha
vector_fp m_dipoleDiag
doublereal m_temp
doublereal m_logt
doublereal m_kbt
doublereal m_t14
doublereal m_t32
doublereal m_sqrt_kbt
doublereal m_sqrt_t
vector_fp m_sqrt_eps_k
DenseMatrix m_log_eps_k
vector_fp m_frot_298
vector_fp m_rotrelax
doublereal m_lambda
doublereal m_viscmix
vector_fp m_spwork
bool m_viscmix_ok
bool m_viscwt_ok
bool m_spvisc_ok
bool m_diffmix_ok
bool m_bindiff_ok
bool m_abc_ok
bool m_spcond_ok
bool m_condmix_ok
int m_mode
DenseMatrix m_epsilon
DenseMatrix m_diam
DenseMatrix incl
bool m_debug
vector_fp cv_rot
vector_fp cp_R
vector_fp cv_int
Friends
class TransportFactory
Transport manager construction
These methods are used internally during construction.
virtual bool initSolid (SolidTransportData &tr)
Called by TransportFactory to set parameters.
virtual void setThermo (thermo_t &thermo)
Specifies the ThermPhase object.
virtual bool initLiquid (LiquidTransportParams &tr)
Called by TransportFactory to set parameters.
void finalize ()
Enable the transport object for use.
Detailed Description
Class PecosTransport implements mixture-averaged transport properties for ideal gas mixtures.
Definition at line 43 of file PecosTransport.h.
Constructor & Destructor Documentation
PecosTransport () protected
default constructor
Definition at line 31 of file PecosTransport.cpp.
Member Function Documentation
virtual int model () const inline virtual
Transport model.
The transport model is the set of equations used to compute the transport properties. This virtual method returns an integer flag that identifies the transport model implemented. The base class returns 0.
Reimplemented from Transport.
Definition at line 50 of file PecosTransport.h.
doublereal viscosity () virtual
Viscosity of the mixture.
The viscosity is computed using the Wilke mixture rule.
\[ \mu = \sum_k \frac{\mu_k X_k}{\sum_j \Phi_{k,j} X_j}. \]
Here \(\mu_k \) is the viscosity of pure species k, and
\[ \Phi_{k,j} = \frac{\left[1 + \sqrt{\left(\frac{\mu_k}{\mu_j}\sqrt{\frac{M_j}{M_k}}\right)}\right]^2} {\sqrt{8}\sqrt{1 + M_k/M_j}} \]
See Also
updateViscosity_T();
Reimplemented from Transport.
Definition at line 140 of file PecosTransport.cpp.
References DATA_PTR, Cantera::multiply(), PecosTransport::update_C(), PecosTransport::update_T(), and PecosTransport::updateViscosity_T().
virtual void getSpeciesViscosities (doublereal *const visc) inline virtual
Returns the pure species viscosities.
The units are Pa-s and the length is the number of species
Parameters
visc Vector of viscosities
Reimplemented from Transport.
Definition at line 60 of file PecosTransport.h.
References PecosTransport::update_T(), and PecosTransport::updateViscosity_T().
void getThermalDiffCoeffs (doublereal *const dt) virtual
Return the thermal diffusion coefficients.
Thermal diffusion is not considered in this pecos model.
For this approximation, these are all zero.
To include thermal diffusion, use transport manager MultiTransport instead. This methods fills out array dt with zeros.
Reimplemented from Transport.
Definition at line 255 of file PecosTransport.cpp.
doublereal thermalConductivity () virtual
The thermal conductivity is computed using the Wilke mixture rule.
returns the mixture thermal conductivity
  This is computed using the lumped model,
\[ k = k^{tr} + k^{ve} \]
where,
\[ k^{tr}= 5/2 \mu_s C_{v,s}^{trans} + \mu_s C_{v,s}^{rot} \]
and,
\[ k^{ve}= \mu_s C_{v,s}^{vib} + \mu_s C_{v,s}^{elec} \]
\[ \k = \sum_s \frac{k_s X_s}{\sum_j \Phi_{s,j} X_j}. \]
Here \(\k_s \) is the conductivity of pure species s, and
\[ \Phi_{s,j} = \frac{\left[1 + \sqrt{\left(\frac{\mu_k}{\mu_j}\sqrt{\frac{M_j}{M_s}}\right)}\right]^2} {\sqrt{8}\sqrt{1 + M_s/M_j}} \]
See Also
updateCond_T();
Reimplemented from Transport.
Definition at line 220 of file PecosTransport.cpp.
References DATA_PTR, Cantera::multiply(), PecosTransport::update_C(), PecosTransport::update_T(), and PecosTransport::updateCond_T().
void getBinaryDiffCoeffs (const size_t ld, doublereal *const d) virtual
Returns the matrix of binary diffusion coefficients [m^2/s].
Parameters
ld Inner stride for writing the two dimension diffusion coefficients into a one dimensional vector
d Diffusion coefficient matrix (must be at least m_k * m_k in length.
Reimplemented from Transport.
Definition at line 174 of file PecosTransport.cpp.
References PecosTransport::pressure_ig(), PecosTransport::update_T(), and PecosTransport::updateDiff_T().
void getMixDiffCoeffs (doublereal *const d) virtual
Mixture-averaged diffusion coefficients [m^2/s].
For the single species case or the pure fluid case the routine returns the self-diffusion coefficient. This is need to avoid a Nan result in the formula below.
Reimplemented from Transport.
Definition at line 322 of file PecosTransport.cpp.
References Transport::m_thermo, Phase::meanMolecularWeight(), PecosTransport::pressure_ig(), PecosTransport::update_C(), PecosTransport::update_T(), and PecosTransport::updateDiff_T().
Referenced by PecosTransport::getMobilities(), and PecosTransport::getSpeciesFluxes().
void getMixDiffCoeffsMole (doublereal *const d) virtual
Returns the mixture-averaged diffusion coefficients [m^2/s].
These are the coefficients for calculating the molar diffusive fluxes from the species mole fraction gradients, computed according to Eq. 12.176 in "Chemically Reacting Flow":
\[ D_{km}^* = \frac{1-X_k}{\sum_{j \ne k}^K X_j/\mathcal{D}_{kj}} \]
Parameters
[out] d vector of mixture-averaged diffusion coefficients for each species, length m_nsp.
Reimplemented from Transport.
Definition at line 359 of file PecosTransport.cpp.
References Transport::m_thermo, ThermoPhase::pressure(), PecosTransport::update_C(), PecosTransport::update_T(), and PecosTransport::updateDiff_T().
void getMixDiffCoeffsMass (doublereal *const d) virtual
Returns the mixture-averaged diffusion coefficients [m^2/s].
These are the coefficients for calculating the diffusive mass fluxes from the species mass fraction gradients, computed according to Eq. 12.178 in "Chemically Reacting Flow":
\[ \frac{1}{D_{km}} = \sum_{j \ne k}^K \frac{X_j}{\mathcal{D}_{kj}} + //! \frac{X_k}{1-Y_k} \sum_{j \ne k}^K \frac{Y_j}{\mathcal{D}_{kj}} \]
Parameters
[out] d vector of mixture-averaged diffusion coefficients for each species, length m_nsp.
Reimplemented from Transport.
Definition at line 389 of file PecosTransport.cpp.
References Transport::m_thermo, Phase::meanMolecularWeight(), ThermoPhase::pressure(), PecosTransport::update_C(), PecosTransport::update_T(), and PecosTransport::updateDiff_T().
void getMobilities (doublereal *const mobil_e) virtual
Get the Electrical mobilities (m^2/V/s).
This function returns the mobilities. In some formulations this is equal to the normal mobility multiplied by faraday's constant.
Frequently, but not always, the mobility is calculated from the diffusion coefficient using the Einstein relation
\[ \mu^e_k = \frac{F D_k}{R T} \]
Parameters
mobil_e Returns the mobilities of the species in array mobil_e. The array must be dimensioned at least as large as the number of species.
Reimplemented from Transport.
Definition at line 193 of file PecosTransport.cpp.
References Cantera::Boltzmann, Phase::charge(), DATA_PTR, PecosTransport::getMixDiffCoeffs(), and Transport::m_thermo.
void update_T (void) virtual
This is called whenever a transport property is requested from ThermoSubstance if the temperature has changed since the last call to update_T.
Definition at line 427 of file PecosTransport.cpp.
References Cantera::Boltzmann, Cantera::fp2str(), Transport::m_thermo, and Phase::temperature().
Referenced by PecosTransport::getBinaryDiffCoeffs(), PecosTransport::getMixDiffCoeffs(), PecosTransport::getMixDiffCoeffsMass(), PecosTransport::getMixDiffCoeffsMole(), PecosTransport::getSpeciesFluxes(), PecosTransport::getSpeciesViscosities(), PecosTransport::thermalConductivity(), and PecosTransport::viscosity().
void update_C () virtual
This is called the first time any transport property is requested from Mixture after the concentrations have changed.
Definition at line 469 of file PecosTransport.cpp.
References DATA_PTR, Phase::getMoleFractions(), Transport::m_thermo, and MIN_X.
Referenced by PecosTransport::getMixDiffCoeffs(), PecosTransport::getMixDiffCoeffsMass(), PecosTransport::getMixDiffCoeffsMole(), PecosTransport::getSpeciesFluxes(), PecosTransport::thermalConductivity(), and PecosTransport::viscosity().
void getSpeciesFluxes (size_t ndim, const doublereal *const grad_T, size_t ldx, const doublereal *const grad_X, size_t ldf, doublereal *const fluxes) virtual
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
Units for the returned fluxes are kg m-2 s-1.
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
fluxes Output of the diffusive mass fluxes Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ndim The number of spatial dimensions (1, 2, or 3).
grad_T The temperature gradient (ignored in this model).
ldx Leading dimension of the grad_X array. The diffusive mass flux of species k is computed from
\[ \vec{j}_k = -n M_k D_k \nabla X_k + \frac{\rho_k}{\rho} \sum_r n M_r D_r \nabla X_r \]
This is neglective pressure, forced and thermal diffusion.
Reimplemented from Transport.
Definition at line 275 of file PecosTransport.cpp.
References DATA_PTR, PecosTransport::getMixDiffCoeffs(), Transport::m_thermo, Phase::massFractions(), Phase::molarDensity(), Phase::molecularWeights(), PecosTransport::update_C(), and PecosTransport::update_T().
bool initGas (GasTransportParams & tr) virtual
Initialize the transport object.
Here we change all of the internal dimensions to be sufficient. We get the object ready to do property evaluations.
Parameters
tr Transport parameters for all of the species in the phase.
Reimplemented from Transport.
Definition at line 40 of file PecosTransport.cpp.
References GasTransportParams::alpha, GasTransportParams::condcoeffs, GasTransportParams::crot, GasTransportParams::diam, GasTransportParams::diffcoeffs, GasTransportParams::dipole, GasTransportParams::eps, GasTransportParams::epsilon, Transport::m_thermo, TransportParams::mode_, Phase::molecularWeights(), Phase::nSpecies(), GasTransportParams::poly, PecosTransport::read_blottner_transport_table(), DenseMatrix::resize(), TransportParams::thermo, GasTransportParams::visccoeffs, and GasTransportParams::zrot.
void read_blottner_transport_table ()
Reads the transport table specified (currently defaults to internal file)
Reads the user-specified transport table, appending new species data and/or replacing default species data.
Definition at line 589 of file PecosTransport.cpp.
References Transport::m_thermo, and Phase::speciesName().
Referenced by PecosTransport::initGas().
struct GasTransportData getGasTransportData (int) read
Return a structure containing all of the pertinent parameters about a species that was used to construct the Transport properties in this object.
Parameters
k Species number to obtain the properties from.
doublereal pressure_ig () const inline private
Calculate the pressure from the ideal gas law.
Definition at line 197 of file PecosTransport.h.
References Cantera::GasConstant, Transport::m_thermo, Phase::molarDensity(), and Phase::temperature().
Referenced by PecosTransport::getBinaryDiffCoeffs(), and PecosTransport::getMixDiffCoeffs().
void updateViscosity_T () private
Update the temperature-dependent viscosity terms.
Updates the array of pure species viscosities, and the weighting functions in the viscosity mixture rule. The flag m_visc_ok is set to true.
Definition at line 718 of file PecosTransport.cpp.
References Cantera::SqrtEight, and PecosTransport::updateSpeciesViscosities().
Referenced by PecosTransport::getSpeciesViscosities(), and PecosTransport::viscosity().
void updateCond_T () private
Update the temperature-dependent parts of the mixture-averaged thermal conductivity.
Calculated as,
\[ k= \mu_s (5/2 * C_{v,s}^{trans} + C_{v,s}^{rot} + C_{v,s}^{vib} \]
Definition at line 506 of file PecosTransport.cpp.
References ThermoPhase::cv_vib(), and Transport::m_thermo.
Referenced by PecosTransport::thermalConductivity().
void updateSpeciesViscosities () private
Update the pure-species viscosities.
(Pa-s) = (kg/m/sec)
Using Blottner fit for viscosity. Defines kinematic viscosity of the form
\[ \mu_s\left(T\right) = 0.10 \exp\left(A_s\left(\log T\right)^2 + B_s\log T + C_s\right) \]
where \(A_s \), \(B_s \), and \(C_s \) are constants.
Definition at line 566 of file PecosTransport.cpp.
Referenced by PecosTransport::updateViscosity_T().
void updateDiff_T () private
Update the binary diffusion coefficients.
These are evaluated from the polynomial fits at unit pressure (1 Pa).
Definition at line 524 of file PecosTransport.cpp.
References Cantera::dot4(), and Cantera::dot5().
Referenced by PecosTransport::getBinaryDiffCoeffs(), PecosTransport::getMixDiffCoeffs(), PecosTransport::getMixDiffCoeffsMass(), and PecosTransport::getMixDiffCoeffsMole().
Transport * duplMyselfAsTransport () const virtual inherited
Duplication routine for objects which inherit from Transport.
This virtual routine can be used to duplicate Transport objects inherited from Transport even if the application only has a pointer to Transport to work with.
These routines are basically wrappers around the derived copy constructor.
Reimplemented in SimpleTransport, LiquidTransport, DustyGasTransport, MixTransport, WaterTransport, and SolidTransport.
Definition at line 64 of file TransportBase.cpp.
References Transport::Transport().
thermo_t& thermo () inline inherited
Phase object.
Every transport manager is designed to compute properties for a specific phase of a mixture, which might be a liquid solution, a gas mixture, a surface, etc. This method returns a reference to the object representing the phase itself.
Definition at line 241 of file TransportBase.h.
References Transport::m_thermo.
Referenced by Transport::setThermo().
bool ready () inherited
Returns true if the transport manager is ready for use.
Definition at line 74 of file TransportBase.cpp.
References Transport::m_ready.
Referenced by Transport::finalize(), and Transport::setThermo().
void setNDim (const int ndim) inherited
Set the number of dimensions to be expected in flux expressions.
Internal memory will be set with this value.
Parameters
ndim Number of dimensions in flux expressions
Definition at line 82 of file TransportBase.cpp.
References Transport::m_nDim.
size_t nDim () const inline inherited
Return the number of dimensions in flux expressions.
Returns
Returns the number of dimensions
Definition at line 263 of file TransportBase.h.
References Transport::m_nDim.
void checkSpeciesIndex (size_t k) const inherited
Check that the specified species index is in range Throws an exception if k is greater than nSpecies()
Definition at line 87 of file TransportBase.cpp.
References Transport::m_nsp.
void checkSpeciesArraySize (size_t kk) const inherited
Check that an array size is at least nSpecies() Throws an exception if kk is less than nSpecies().
Used before calls which take an array pointer.
Definition at line 94 of file TransportBase.cpp.
References Transport::m_nsp.
virtual doublereal bulkViscosity () inline virtual inherited
The bulk viscosity in Pa-s.
The bulk viscosity is only non-zero in rare cases. Most transport managers either overload this method to return zero, or do not implement it, in which case an exception is thrown if called.
Reimplemented in WaterTransport, and FtnTransport.
Definition at line 305 of file TransportBase.h.
References Transport::err().
virtual doublereal ionConductivity () inline virtual inherited
The ionic conductivity in 1/ohm/m.
Reimplemented in LiquidTransport, and SolidTransport.
Definition at line 312 of file TransportBase.h.
References Transport::err().
virtual void getSpeciesIonConductivity (doublereal *const ionCond) inline virtual inherited
Returns the pure species ionic conductivity.
The units are 1/ohm/m and the length is the number of species
Parameters
ionCond Vector of ionic conductivities
Reimplemented in LiquidTransport.
Definition at line 322 of file TransportBase.h.
References Transport::err().
virtual void mobilityRatio (double * mobRat) inline virtual inherited
Returns the pointer to the mobility ratios of the species in the phase.
Parameters
mobRat Returns a matrix of mobility ratios for the current problem. The mobility ratio mobRat(i,j) is defined as the ratio of the mobility of species i to species j.
mobRat(i,j) = mu_i / mu_j
It is returned in fortran-ordering format. ie. it is returned as mobRat[k], where
k = j * nsp + i
The size of mobRat must be at least equal to nsp*nsp
Reimplemented in LiquidTransport.
Definition at line 342 of file TransportBase.h.
References Transport::err().
virtual void getSpeciesMobilityRatio (double ** mobRat) inline virtual inherited
Returns the pure species limit of the mobility ratios.
The value is dimensionless and the length is the number of species
Parameters
mobRat Vector of mobility ratios
Reimplemented in LiquidTransport.
Definition at line 352 of file TransportBase.h.
References Transport::err().
virtual void selfDiffusion (doublereal *const selfDiff) inline virtual inherited
Returns the self diffusion coefficients of the species in the phase.
The self diffusion coefficient is the diffusion coefficient of a tracer species at the current temperature and composition of the species. Therefore, the dilute limit of transport is assumed for the tracer species. The effective formula may be calculated from the stefan-maxwell formulation by adding another row for the tracer species, assigning all D's to be equal to the respective species D's, and then taking the limit as the tracer species mole fraction goes to zero. The corresponding flux equation for the tracer species k in units of kmol m-2 s-1 is.
\[ J_k = - D^{sd}_k \frac{C_k}{R T} \nabla \mu_k \]
The derivative is taken at constant T and P.
The self diffusion calculation is handled by subclasses of LiquidTranInteraction as specified in the input file. These in turn employ subclasses of LTPspecies to determine the individual species self diffusion coeffs.
Parameters
selfDiff Vector of self-diffusion coefficients Length = number of species in phase units = m**2 s-1
Reimplemented in LiquidTransport.
Definition at line 382 of file TransportBase.h.
References Transport::err().
virtual void getSpeciesSelfDiffusion (double ** selfDiff) inline virtual inherited
Returns the pure species self diffusion in solution of each species.
The pure species molar volumes are evaluated using the appropriate subclasses of LTPspecies as specified in the input file.
Parameters
selfDiff array of length "number of species" to hold returned self diffusion coeffs.
Reimplemented in LiquidTransport.
Definition at line 396 of file TransportBase.h.
References Transport::err().
virtual doublereal electricalConductivity () inline virtual inherited
The electrical conductivity (Siemens/m).
Reimplemented in FtnTransport, and SolidTransport.
Definition at line 413 of file TransportBase.h.
References Transport::err().
virtual void getFluidMobilities (doublereal *const mobil_f) inline virtual inherited
Get the fluid mobilities (s kmol/kg).
This function returns the fluid mobilities. Usually, you have to multiply Faraday's constant into the resulting expression to general a species flux expression.
Frequently, but not always, the mobility is calculated from the diffusion coefficient using the Einstein relation
\[ \mu^f_k = \frac{D_k}{R T} \]
Parameters
mobil_f Returns the mobilities of the species in array mobil. The array must be dimensioned at least as large as the number of species.
Reimplemented in LiquidTransport, SimpleTransport, and AqueousTransport.
Definition at line 457 of file TransportBase.h.
References Transport::err().
virtual doublereal getElectricConduct () inline virtual inherited
Compute the mixture electrical conductivity (S m-1) at the current conditions of the phase (Siemens m-1)
The electrical conductivity, \(\sigma \), relates the electric current density, J, to the electric field, E.
\[ \vec{J} = \sigma \vec{E} \]
We assume here that the mixture electrical conductivity is an isotropic quantity, at this stage. Tensors may be included at a later time.
The conductivity is the reciprocal of the resistivity.
The units are Siemens m-1, where 1 S = 1 A / volt = 1 s^3 A^2 /kg /m^2
Reimplemented in LiquidTransport.
Definition at line 482 of file TransportBase.h.
References Transport::err().
virtual void getElectricCurrent (int ndim, const doublereal * grad_T, int ldx, const doublereal * grad_X, int ldf, const doublereal * grad_V, doublereal * current) inline virtual inherited
Compute the electric current density in A/m^2.
Calculates the electric current density as a vector, given the gradients of the field variables.
Parameters
ndim The number of spatial dimensions (1, 2, or 3).
grad_T The temperature gradient (ignored in this model).
ldx Leading dimension of the grad_X array.
grad_X The gradient of the mole fraction
ldf Leading dimension of the grad_V and current vectors.
grad_V The electrostatic potential gradient.
current The electric current in A/m^2. This is a vector of length ndim
Reimplemented in LiquidTransport.
Definition at line 500 of file TransportBase.h.
References Transport::err().
virtual void getSpeciesFluxesES (size_t ndim, const doublereal * grad_T, size_t ldx, const doublereal * grad_X, size_t ldf, const doublereal * grad_Phi, doublereal * fluxes) inline virtual inherited
Get the species diffusive mass fluxes wrt to the mass averaged velocity, given the gradients in mole fraction, temperature and electrostatic potential.
Units for the returned fluxes are kg m-2 s-1.
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
grad_Phi Gradients of the electrostatic potential (length = ndim)
fluxes Output of the diffusive mass fluxes Flat vector with the m_nsp in the inner loop. length = ldx * ndim
Reimplemented in LiquidTransport.
Definition at line 560 of file TransportBase.h.
References Transport::getSpeciesFluxes().
virtual void getSpeciesVdiff (size_t ndim, const doublereal * grad_T, int ldx, const doublereal * grad_X, int ldf, doublereal * Vdiff) inline virtual inherited
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction and temperature.
Units for the returned velocities are m s-1
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
Vdiff Output of the diffusive velocities wrt the mass-averaged velocity Flat vector with the m_nsp in the inner loop. length = ldx * ndim units are m / s.
Reimplemented in LiquidTransport, and SimpleTransport.
Definition at line 593 of file TransportBase.h.
References Transport::err().
Referenced by Transport::getSpeciesVdiffES().
virtual void getSpeciesVdiffES (size_t ndim, const doublereal * grad_T, int ldx, const doublereal * grad_X, int ldf, const doublereal * grad_Phi, doublereal * Vdiff) inline virtual inherited
Get the species diffusive velocities wrt to the mass averaged velocity, given the gradients in mole fraction, temperature, and electrostatic potential.
Units for the returned velocities are m s-1.
Parameters
ndim Number of dimensions in the flux expressions
grad_T Gradient of the temperature (length = ndim)
ldx Leading dimension of the grad_X array (usually equal to m_nsp but not always)
grad_X Gradients of the mole fraction Flat vector with the m_nsp in the inner loop. length = ldx * ndim
ldf Leading dimension of the fluxes array (usually equal to m_nsp but not always)
grad_Phi Gradients of the electrostatic potential (length = ndim)
Vdiff Output of the diffusive velocities wrt the mass-averaged velocity Flat vector with the m_nsp in the inner loop. length = ldx * ndim units are m / s.
Reimplemented in LiquidTransport, and SimpleTransport.
Definition at line 625 of file TransportBase.h.
References Transport::getSpeciesVdiff().
virtual void getMolarFluxes (const doublereal *const state1, const doublereal *const state2, const doublereal delta, doublereal *const cfluxes) inline virtual inherited
Get the molar fluxes [kmol/m^2/s], given the thermodynamic state at two nearby points.
Parameters
state1 Array of temperature, density, and mass fractions for state 1.
state2 Array of temperature, density, and mass fractions for state 2.
delta Distance from state 1 to state 2 (m).
cfluxes Output array containing the diffusive molar fluxes of species from state1 to state2. This is a flat vector with the m_nsp in the inner loop. length = ldx * ndim. Units are [kmol/m^2/s].
Reimplemented in DustyGasTransport, and MultiTransport.
Definition at line 650 of file TransportBase.h.
References Transport::err().
virtual void getMassFluxes (const doublereal * state1, const doublereal * state2, doublereal delta, doublereal * mfluxes) inline virtual inherited
Get the mass fluxes [kg/m^2/s], given the thermodynamic state at two nearby points.
Parameters
state1 Array of temperature, density, and mass fractions for state 1.
state2 Array of temperature, density, and mass fractions for state 2.
delta Distance from state 1 to state 2 (m).
mfluxes Output array containing the diffusive mass fluxes of species from state1 to state2. This is a flat vector with the m_nsp in the inner loop. length = ldx * ndim. Units are [kg/m^2/s].
Reimplemented in MultiTransport.
Definition at line 671 of file TransportBase.h.
References Transport::err().
virtual void getMultiDiffCoeffs (const size_t ld, doublereal *const d) inline virtual inherited
Return the Multicomponent diffusion coefficients. Units: [m^2/s].
If the transport manager implements a multicomponent diffusion model, then this method returns the array of multicomponent diffusion coefficients. Otherwise it throws an exception.
Parameters
ld The dimension of the inner loop of d (usually equal to m_nsp)
d flat vector of diffusion coefficients, fortran ordering. d[ld*j+i] is the D_ij diffusion coefficient (the diffusion coefficient for species i due to species j).
Reimplemented in DustyGasTransport, and MultiTransport.
Definition at line 721 of file TransportBase.h.
References Transport::err().
Referenced by StFlow::updateTransport().
void setParameters (const int type, const int k, const doublereal *const p) virtual inherited
Set model parameters for derived classes.
This method may be derived in subclasses to set model-specific parameters. The primary use of this class is to set parameters while in the middle of a calculation without actually having to dynamically cast the base Transport pointer.
Parameters
type Specifies the type of parameters to set 0 : Diffusion coefficient 1 : Thermal Conductivity The rest are currently unused.
k Species index to set the parameters on
p Vector of parameters. The length of the vector varies with the parameterization
Reimplemented in DustyGasTransport, and SolidTransport.
Definition at line 105 of file TransportBase.cpp.
References Transport::err().
void setVelocityBasis (VelocityBasis ivb) inline inherited
Sets the velocity basis.
What the transport object does with this parameter is up to the individual operator. Currently, this is not functional for most transport operators including all of the gas-phase operators.
Parameters
ivb Species the velocity basis
Definition at line 777 of file TransportBase.h.
References Transport::m_velocityBasis.
VelocityBasis getVelocityBasis () const inline inherited
Gets the velocity basis.
What the transport object does with this parameter is up to the individual operator. Currently, this is not functional for most transport operators including all of the gas-phase operators.
Returns
Returns the velocity basis
Definition at line 789 of file TransportBase.h.
References Transport::m_velocityBasis.
virtual bool initLiquid (LiquidTransportParams & tr) inline protected virtual inherited
Called by TransportFactory to set parameters.
This is called by classes that use the liquid phase parameter list to initialize themselves.
Parameters
tr Reference to the parameter list that will be used to initialize the class
Reimplemented in AqueousTransport, SimpleTransport, and LiquidTransport.
Definition at line 832 of file TransportBase.h.
References Transport::err().
Referenced by TransportFactory::initLiquidTransport().
virtual bool initSolid (SolidTransportData & tr) inline virtual inherited
Called by TransportFactory to set parameters.
This is called by classes that use the solid phase parameter list to initialize themselves.
Parameters
tr Reference to the parameter list that will be used to initialize the class
Reimplemented in SolidTransport.
Definition at line 846 of file TransportBase.h.
References Transport::err().
Referenced by TransportFactory::initSolidTransport().
void setThermo (thermo_t & thermo) virtual inherited
Specifies the ThermPhase object.
We have relaxed this operation so that it will succeed when the underlying old and new ThermoPhase objects have the same number of species and the same names of the species in the same order. The idea here is to allow copy constructors and duplicators to work. In order for them to work, we need a method to switch the internal pointer within the Transport object after the duplication takes place. Also, different thermodynamic instanteations of the same species should also work.
Parameters
thermo Reference to the ThermoPhase object that the transport object will use
Reimplemented in DustyGasTransport.
Definition at line 112 of file TransportBase.cpp.
References Transport::m_thermo, Phase::nSpecies(), Transport::ready(), Phase::speciesName(), and Transport::thermo().
Referenced by TransportFactory::newTransport(), and DustyGasTransport::setThermo().
void finalize () protected inherited
Enable the transport object for use.
Once finalize() has been called, the transport manager should be ready to compute any supported transport property, and no further modifications to the model parameters should be made.
Definition at line 151 of file TransportBase.cpp.
References Transport::m_ready, and Transport::ready().
Member Data Documentation
thermo_t* m_thermo protected inherited
pointer to the object representing the phase
Definition at line 883 of file TransportBase.h.
Referenced by SolidTransport::electricalConductivity(), GasTransport::getBinaryDiffCoeffs(), AqueousTransport::getBinaryDiffCoeffs(), AqueousTransport::getLiquidTransportData(), MultiTransport::getMassFluxes(), GasTransport::getMixDiffCoeffs(), PecosTransport::getMixDiffCoeffs(), SolidTransport::getMixDiffCoeffs(), AqueousTransport::getMixDiffCoeffs(), GasTransport::getMixDiffCoeffsMass(), PecosTransport::getMixDiffCoeffsMass(), GasTransport::getMixDiffCoeffsMole(), PecosTransport::getMixDiffCoeffsMole(), SolidTransport::getMobilities(), PecosTransport::getMobilities(), MultiTransport::getMolarFluxes(), DustyGasTransport::getMolarFluxes(), MultiTransport::getMultiDiffCoeffs(), MultiTransport::getSpeciesFluxes(), PecosTransport::getSpeciesFluxes(), MixTransport::getSpeciesFluxes(), AqueousTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesFluxesExt(), SimpleTransport::getSpeciesVdiff(), SimpleTransport::getSpeciesVdiffES(), GasTransport::initGas(), PecosTransport::initGas(), DustyGasTransport::initialize(), LiquidTransport::initLiquid(), SimpleTransport::initLiquid(), AqueousTransport::initLiquid(), SolidTransport::initSolid(), WaterTransport::initTP(), Transport::operator=(), PecosTransport::pressure_ig(), MixTransport::pressure_ig(), PecosTransport::read_blottner_transport_table(), SolidTransport::setParameters(), Transport::setThermo(), AqueousTransport::stefan_maxwell_solve(), LiquidTransport::stefan_maxwell_solve(), SolidTransport::thermalConductivity(), Transport::thermo(), Transport::Transport(), PecosTransport::update_C(), MultiTransport::update_C(), MixTransport::update_C(), AqueousTransport::update_C(), SimpleTransport::update_C(), LiquidTransport::update_C(), LiquidTransport::update_Grad_lnAC(), PecosTransport::update_T(), MultiTransport::update_T(), MixTransport::update_T(), AqueousTransport::update_T(), SimpleTransport::update_T(), LiquidTransport::update_T(), PecosTransport::updateCond_T(), MultiTransport::updateThermal_T(), DustyGasTransport::updateTransport_C(), and DustyGasTransport::updateTransport_T().
bool m_ready protected inherited
true if finalize has been called
Definition at line 886 of file TransportBase.h.
Referenced by Transport::finalize(), Transport::operator=(), Transport::ready(), and Transport::Transport().
size_t m_nDim protected inherited
Number of dimensions used in flux expressions.
Definition at line 892 of file TransportBase.h.
Referenced by LiquidTransport::getElectricConduct(), LiquidTransport::getElectricCurrent(), LiquidTransport::getMixDiffCoeffs(), LiquidTransport::getSpeciesFluxesExt(), LiquidTransport::getSpeciesVdiffExt(), LiquidTransport::initLiquid(), Transport::nDim(), LiquidTransport::operator=(), Transport::operator=(), LiquidTransport::set_Grad_T(), LiquidTransport::set_Grad_V(), LiquidTransport::set_Grad_X(), Transport::setNDim(), LiquidTransport::stefan_maxwell_solve(), Transport::Transport(), and LiquidTransport::update_Grad_lnAC().
int m_velocityBasis protected inherited
Velocity basis from which diffusion velocities are computed.
Defaults to the mass averaged basis = -2
Definition at line 896 of file TransportBase.h.
Referenced by SimpleTransport::getSpeciesFluxesExt(), Transport::getVelocityBasis(), LiquidTransport::initLiquid(), Transport::operator=(), Transport::setVelocityBasis(), LiquidTransport::stefan_maxwell_solve(), and Transport::Transport().
The documentation for this class was generated from the following files:
PecosTransport.h
PecosTransport.cpp