Cantera: IdealGasConstPressureReactor Class Reference
IdealGasConstPressureReactor Class Reference
Class ConstPressureReactor is a class for constant-pressure reactors.
#include <IdealGasConstPressureReactor.h>
Public Member Functions
virtual int type () const
Return a constant indicating the type of this Reactor.
virtual void setThermoMgr (ThermoPhase &thermo)
Specify the mixture contained in the reactor.
virtual void getInitialConditions (doublereal t0, size_t leny, doublereal *y)
Called by ReactorNet to get the initial conditions.
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
virtual void evalEqs (doublereal t, doublereal *y, doublereal *ydot, doublereal *params)
virtual void updateState (doublereal *y)
Set the state of the reactor to correspond to the state vector y.
virtual size_t componentIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the component named nm.
Protected Attributes
vector_fp m_hk
Species molar enthalpies.
Additional Inherited Members
Protected Member Functions inherited from Reactor
virtual void applySensitivity (double *params)
Set reaction rate multipliers based on the sensitivity variables in params.
virtual void resetSensitivity (double *params)
Reset the reaction rate multipliers.
virtual size_t speciesIndex (const std::string &nm) const
Return the index in the solution vector for this reactor of the species named nm, in either the homogeneous phase or a surface phase, relative to the start of the species terms.
Detailed Description
Class ConstPressureReactor is a class for constant-pressure reactors.
The reactor may have an arbitrary number of inlets and outlets, each of which may be connected to a "flow device" such as a mass flow controller, a pressure regulator, etc. Additional reactors may be connected to the other end of the flow device, allowing construction of arbitrary reactor networks.
Definition at line 23 of file IdealGasConstPressureReactor.h.
Member Function Documentation
virtual int type () const inline virtual
Return a constant indicating the type of this Reactor.
Reimplemented from ConstPressureReactor.
Definition at line 28 of file IdealGasConstPressureReactor.h.
void setThermoMgr (ThermoPhase & thermo) virtual
Specify the mixture contained in the reactor.
Note that a pointer to this substance is stored, and as the integration proceeds, the state of the substance is modified.
Reimplemented from ReactorBase.
Definition at line 19 of file IdealGasConstPressureReactor.cpp.
References Cantera::cIdealGas, and ThermoPhase::eosType().
void getInitialConditions (doublereal t0, size_t leny, doublereal * y) virtual
Called by ReactorNet to get the initial conditions.
Parameters
[in] t0 Time at which initial conditions are determined
[in] leny Length of y (unused)
[out] y state vector representing the initial state of the reactor
Reimplemented from ConstPressureReactor.
Definition at line 31 of file IdealGasConstPressureReactor.cpp.
References SurfPhase::getCoverages(), and Phase::nSpecies().
void initialize (doublereal t0 = 0.0) virtual
Initialize the reactor.
Called automatically by ReactorNet::initialize.
Reimplemented from ConstPressureReactor.
Definition at line 63 of file IdealGasConstPressureReactor.cpp.
void evalEqs (doublereal t, doublereal * y, doublereal * ydot, doublereal * params) virtual
Evaluate the reactor governing equations. Called by ReactorNet::eval.
Parameters
[in] t time.
[in] y solution vector, length neq()
[out] ydot rate of change of solution vector, length neq()
[in] params sensitivity parameter vector, length ReactorNet::nparams()
Reimplemented from ConstPressureReactor.
Definition at line 127 of file IdealGasConstPressureReactor.cpp.
References DATA_PTR, Kinetics::getNetProductionRates(), Kinetics::kineticsSpeciesIndex(), Phase::nSpecies(), Phase::setTemperature(), SurfPhase::siteDensity(), Phase::size(), and Kinetics::surfacePhaseIndex().
void updateState (doublereal * y) virtual
Set the state of the reactor to correspond to the state vector y.
Reimplemented from ConstPressureReactor.
Definition at line 101 of file IdealGasConstPressureReactor.cpp.
References Phase::nSpecies(), and SurfPhase::setCoverages().
size_t componentIndex (const std::string & nm) const virtual
Return the index in the solution vector for this reactor of the component named nm.
Possible values for nm are "m", "T", the name of a homogeneous phase species, or the name of a surface species.
Reimplemented from ConstPressureReactor.
Definition at line 232 of file IdealGasConstPressureReactor.cpp.
References Cantera::npos.
Member Data Documentation
vector_fp m_hk protected
Species molar enthalpies.
Definition at line 49 of file IdealGasConstPressureReactor.h.
The documentation for this class was generated from the following files:
IdealGasConstPressureReactor.h
IdealGasConstPressureReactor.cpp