Cantera: IdealGasPhase Class Reference
IdealGasPhase Class Reference
Thermodynamic Properties
Class IdealGasPhase represents low-density gases that obey the ideal gas equation of state.
#include <IdealGasPhase.h>
Public Member Functions
IdealGasPhase ()
Default empty Constructor.
IdealGasPhase (const std::string &inputFile, const std::string &id="")
Construct and initialize an IdealGasPhase ThermoPhase object directly from an ASCII input file.
IdealGasPhase (XML_Node &phaseRef, const std::string &id="")
Construct and initialize an IdealGasPhase ThermoPhase object directly from an XML database.
IdealGasPhase (const IdealGasPhase &right)
IdealGasPhase & operator= (const IdealGasPhase &right)
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
virtual int eosType () const
Equation of state flag.
virtual std::string type () const
String indicating the thermodynamic model implemented.
virtual bool addSpecies (shared_ptr< Species > spec)
virtual void setToEquilState (const doublereal *lambda_RT)
This method is used by the ChemEquil equilibrium solver.
Molar Thermodynamic Properties of the Solution
virtual doublereal enthalpy_mole () const
Return the Molar enthalpy. Units: J/kmol.
virtual doublereal entropy_mole () const
Molar entropy.
virtual doublereal cp_mole () const
Molar heat capacity at constant pressure.
virtual doublereal cv_mole () const
Molar heat capacity at constant volume.
Mechanical Equation of State
virtual doublereal pressure () const
Pressure.
virtual void setPressure (doublereal p)
Set the pressure at constant temperature and composition.
virtual void setState_RP (doublereal rho, doublereal p)
Set the density and pressure at constant composition.
virtual doublereal isothermalCompressibility () const
Returns the isothermal compressibility. Units: 1/Pa.
virtual doublereal thermalExpansionCoeff () const
Return the volumetric thermal expansion coefficient. Units: 1/K.
Chemical Potentials and Activities
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k(T,P,X_k) = \mu_k^0(T,P) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the standard state chemical potential at unit activity.
It may depend on the pressure and the temperature. However, it may not depend on the mole fractions of the species in the solution.
The activities are related to the generalized concentrations, \(\tilde C_k\), and standard concentrations, \(C^0_k\), by the following formula:
\[ a_k = \frac{\tilde C_k}{C^0_k} \]
The generalized concentrations are used in the kinetics classes to describe the rates of progress of reactions involving the species. Their formulation depends upon the specification of the rate constants for reaction, especially the units used in specifying the rate constants. The bridge between the thermodynamic equilibrium expressions that use a_k and the kinetics expressions which use the generalized concentrations is provided by the multiplicative factor of the standard concentrations.
virtual void getActivityConcentrations (doublereal *c) const
This method returns the array of generalized concentrations.
virtual doublereal standardConcentration (size_t k=0) const
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
Partial Molar Properties of the Solution
virtual void getChemPotentials (doublereal *mu) const
Get the species chemical potentials. Units: J/kmol.
virtual void getPartialMolarEnthalpies (doublereal *hbar) const
Returns an array of partial molar enthalpies for the species in the mixture.
virtual void getPartialMolarEntropies (doublereal *sbar) const
Returns an array of partial molar entropies of the species in the solution.
virtual void getPartialMolarIntEnergies (doublereal *ubar) const
Return an array of partial molar internal energies for the species in the mixture.
virtual void getPartialMolarCp (doublereal *cpbar) const
Return an array of partial molar heat capacities for the species in the mixture.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
Properties of the Standard State of the Species in the Solution
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
virtual void getPureGibbs (doublereal *gpure) const
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of the species standard states at the current T and P of the solution.
Thermodynamic Values for the Species Reference States
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getEntropy_R_ref (doublereal *er) const
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getIntEnergy_RT_ref (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
virtual void getCp_R_ref (doublereal *cprt) const
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
NonVirtual Internal methods to Return References to Reference State Thermo
const vector_fp & enthalpy_RT_ref () const
Returns a reference to the dimensionless reference state enthalpy vector.
const vector_fp & gibbs_RT_ref () const
Returns a reference to the dimensionless reference state Gibbs free energy vector.
const vector_fp & entropy_R_ref () const
Returns a reference to the dimensionless reference state Entropy vector.
const vector_fp & cp_R_ref () const
Returns a reference to the dimensionless reference state Heat Capacity vector.
Public Member Functions inherited from ThermoPhase
ThermoPhase ()
Constructor.
ThermoPhase (const ThermoPhase &right)
ThermoPhase & operator= (const ThermoPhase &right)
doublereal _RT () const
Return the Gas Constant multiplied by the current temperature.
doublereal RT () const
Return the Gas Constant multiplied by the current temperature.
virtual doublereal refPressure () const
Returns the reference pressure in Pa.
virtual doublereal minTemp (size_t k=npos) const
Minimum temperature for which the thermodynamic data for the species or phase are valid.
doublereal Hf298SS (const int k) const
Report the 298 K Heat of Formation of the standard state of one species (J kmol-1)
virtual void modifyOneHf298SS (const size_t k, const doublereal Hf298New)
Modify the value of the 298 K Heat of Formation of one species in the phase (J kmol-1)
virtual void resetHf298 (const size_t k=npos)
Restore the original heat of formation of one or more species.
virtual doublereal maxTemp (size_t k=npos) const
Maximum temperature for which the thermodynamic data for the species are valid.
bool chargeNeutralityNecessary () const
Returns the chargeNeutralityNecessity boolean.
virtual doublereal intEnergy_mole () const
Molar internal energy. Units: J/kmol.
virtual doublereal gibbs_mole () const
Molar Gibbs function. Units: J/kmol.
void setElectricPotential (doublereal v)
Set the electric potential of this phase (V).
doublereal electricPotential () const
Returns the electric potential of this phase (V).
virtual int activityConvention () const
This method returns the convention used in specification of the activities, of which there are currently two, molar- and molality-based conventions.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual doublereal logStandardConc (size_t k=0) const
Natural logarithm of the standard concentration of the kth species.
virtual void getActivities (doublereal *a) const
Get the array of non-dimensional activities at the current solution temperature, pressure, and solution concentration.
virtual void getLnActivityCoefficients (doublereal *lnac) const
Get the array of non-dimensional molar-based ln activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials These are partial molar Gibbs free energies.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void setReferenceComposition (const doublereal *const x)
Sets the reference composition.
virtual void getReferenceComposition (doublereal *const x) const
Gets the reference composition.
doublereal enthalpy_mass () const
Specific enthalpy. Units: J/kg.
doublereal intEnergy_mass () const
Specific internal energy. Units: J/kg.
doublereal entropy_mass () const
Specific entropy. Units: J/kg/K.
doublereal gibbs_mass () const
Specific Gibbs function. Units: J/kg.
doublereal cp_mass () const
Specific heat at constant pressure. Units: J/kg/K.
doublereal cv_mass () const
Specific heat at constant volume. Units: J/kg/K.
virtual void setState_TPX (doublereal t, doublereal p, const doublereal *x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const compositionMap &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPX (doublereal t, doublereal p, const std::string &x)
Set the temperature (K), pressure (Pa), and mole fractions.
virtual void setState_TPY (doublereal t, doublereal p, const doublereal *y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const compositionMap &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TPY (doublereal t, doublereal p, const std::string &y)
Set the internally stored temperature (K), pressure (Pa), and mass fractions of the phase.
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setState_PX (doublereal p, doublereal *x)
Set the pressure (Pa) and mole fractions.
virtual void setState_PY (doublereal p, doublereal *y)
Set the internally stored pressure (Pa) and mass fractions.
virtual void setState_HP (doublereal h, doublereal p, doublereal tol=1.e-4)
Set the internally stored specific enthalpy (J/kg) and pressure (Pa) of the phase.
virtual void setState_UV (doublereal u, doublereal v, doublereal tol=1.e-4)
Set the specific internal energy (J/kg) and specific volume (m^3/kg).
virtual void setState_SP (doublereal s, doublereal p, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and pressure (Pa).
virtual void setState_SV (doublereal s, doublereal v, doublereal tol=1.e-4)
Set the specific entropy (J/kg/K) and specific volume (m^3/kg).
virtual void setState_ST (double s, double t, double tol=1.e-4)
Set the specific entropy (J/kg/K) and temperature (K).
virtual void setState_TV (double t, double v, double tol=1.e-4)
Set the temperature (K) and specific volume (m^3/kg).
virtual void setState_PV (double p, double v, double tol=1.e-4)
Set the pressure (Pa) and specific volume (m^3/kg).
virtual void setState_UP (double u, double p, double tol=1.e-4)
Set the specific internal energy (J/kg) and pressure (Pa).
virtual void setState_VH (double v, double h, double tol=1.e-4)
Set the specific volume (m^3/kg) and the specific enthalpy (J/kg)
virtual void setState_TH (double t, double h, double tol=1.e-4)
Set the temperature (K) and the specific enthalpy (J/kg)
virtual void setState_SH (double s, double h, double tol=1.e-4)
Set the specific entropy (J/kg/K) and the specific enthalpy (J/kg)
virtual void setState_RPX (doublereal rho, doublereal p, const doublereal *x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const compositionMap &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPX (doublereal rho, doublereal p, const std::string &x)
Set the density (kg/m**3), pressure (Pa) and mole fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const doublereal *y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const compositionMap &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
virtual void setState_RPY (doublereal rho, doublereal p, const std::string &y)
Set the density (kg/m**3), pressure (Pa) and mass fractions.
void equilibrate (const std::string &XY, const std::string &solver="auto", double rtol=1e-9, int max_steps=50000, int max_iter=100, int estimate_equil=0, int log_level=0)
Equilibrate a ThermoPhase object.
void setElementPotentials (const vector_fp &lambda)
Stores the element potentials in the ThermoPhase object.
bool getElementPotentials (doublereal *lambda) const
Returns the element potentials stored in the ThermoPhase object.
virtual bool compatibleWithMultiPhase () const
Indicates whether this phase type can be used with class MultiPhase for equilibrium calculations.
virtual doublereal critTemperature () const
Critical temperature (K).
virtual doublereal critPressure () const
Critical pressure (Pa).
virtual doublereal critVolume () const
Critical volume (m3/kmol).
virtual doublereal critCompressibility () const
Critical compressibility (unitless).
virtual doublereal critDensity () const
Critical density (kg/m3).
virtual doublereal satTemperature (doublereal p) const
Return the saturation temperature given the pressure.
virtual doublereal satPressure (doublereal t)
Return the saturation pressure given the temperature.
virtual doublereal vaporFraction () const
Return the fraction of vapor at the current conditions.
virtual void setState_Tsat (doublereal t, doublereal x)
Set the state to a saturated system at a particular temperature.
virtual void setState_Psat (doublereal p, doublereal x)
Set the state to a saturated system at a particular pressure.
virtual void modifySpecies (size_t k, shared_ptr< Species > spec)
Modify the thermodynamic data associated with a species.
void saveSpeciesData (const size_t k, const XML_Node *const data)
Store a reference pointer to the XML tree containing the species data for this phase.
const std::vector< const
XML_Node * > & speciesData () const
Return a pointer to the vector of XML nodes containing the species data for this phase.
void setSpeciesThermo (MultiSpeciesThermo *spthermo)
Install a species thermodynamic property manager.
virtual MultiSpeciesThermo & speciesThermo (int k=-1)
Return a changeable reference to the calculation manager for species reference-state thermodynamic properties.
virtual void initThermoFile (const std::string &inputFile, const std::string &id)
virtual void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object using an XML tree.
virtual void initThermo ()
Initialize the ThermoPhase object after all species have been set up.
virtual void installSlavePhases (XML_Node *phaseNode)
Add in species from Slave phases.
virtual void setParameters (int n, doublereal *const c)
Set the equation of state parameters.
virtual void getParameters (int &n, doublereal *const c) const
Get the equation of state parameters in a vector.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
virtual void setStateFromXML (const XML_Node &state)
Set the initial state of the phase to the conditions specified in the state XML element.
virtual void invalidateCache ()
Invalidate any cached values which are normally updated only when a change in state is detected.
virtual void getdlnActCoeffds (const doublereal dTds, const doublereal *const dXds, doublereal *dlnActCoeffds) const
Get the change in activity coefficients wrt changes in state (temp, mole fraction, etc) along a line in parameter space or along a line in physical space.
virtual void getdlnActCoeffdlnX_diag (doublereal *dlnActCoeffdlnX_diag) const
Get the array of ln mole fraction derivatives of the log activity coefficients - diagonal component only.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log species mole number derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnN_numderiv (const size_t ld, doublereal *const dlnActCoeffdlnN)
virtual std::string report (bool show_thermo=true, doublereal threshold=-1e-14) const
returns a summary of the state of the phase as a string
virtual void reportCSV (std::ofstream &csvFile) const
returns a summary of the state of the phase to a comma separated file.
Public Member Functions inherited from Phase
Phase ()
Default constructor.
Phase (const Phase &right)
Phase & operator= (const Phase &right)
XML_Node & xml () const
Returns a const reference to the XML_Node that describes the phase.
void setXMLdata (XML_Node &xmlPhase)
Stores the XML tree information for the current phase.
void saveState (vector_fp &state) const
Save the current internal state of the phase.
void saveState (size_t lenstate, doublereal *state) const
Write to array 'state' the current internal state.
void restoreState (const vector_fp &state)
Restore a state saved on a previous call to saveState.
void restoreState (size_t lenstate, const doublereal *state)
Restore the state of the phase from a previously saved state vector.
doublereal molecularWeight (size_t k) const
Molecular weight of species k.
void getMolecularWeights (vector_fp &weights) const
Copy the vector of molecular weights into vector weights.
void getMolecularWeights (doublereal *weights) const
Copy the vector of molecular weights into array weights.
const vector_fp & molecularWeights () const
Return a const reference to the internal vector of molecular weights.
doublereal size (size_t k) const
This routine returns the size of species k.
doublereal charge (size_t k) const
Dimensionless electrical charge of a single molecule of species k The charge is normalized by the the magnitude of the electron charge.
doublereal chargeDensity () const
Charge density [C/m^3].
size_t nDim () const
Returns the number of spatial dimensions (1, 2, or 3)
void setNDim (size_t ndim)
Set the number of spatial dimensions (1, 2, or 3).
virtual bool ready () const
Returns a bool indicating whether the object is ready for use.
int stateMFNumber () const
Return the State Mole Fraction Number.
std::string id () const
Return the string id for the phase.
void setID (const std::string &id)
Set the string id for the phase.
std::string name () const
Return the name of the phase.
void setName (const std::string &nm)
Sets the string name for the phase.
std::string elementName (size_t m) const
Name of the element with index m.
size_t elementIndex (const std::string &name) const
Return the index of element named 'name'.
const std::vector< std::string > & elementNames () const
Return a read-only reference to the vector of element names.
doublereal atomicWeight (size_t m) const
Atomic weight of element m.
doublereal entropyElement298 (size_t m) const
Entropy of the element in its standard state at 298 K and 1 bar.
int atomicNumber (size_t m) const
Atomic number of element m.
int elementType (size_t m) const
Return the element constraint type Possible types include:
int changeElementType (int m, int elem_type)
Change the element type of the mth constraint Reassigns an element type.
const vector_fp & atomicWeights () const
Return a read-only reference to the vector of atomic weights.
size_t nElements () const
Number of elements.
void checkElementIndex (size_t m) const
Check that the specified element index is in range.
void checkElementArraySize (size_t mm) const
Check that an array size is at least nElements().
doublereal nAtoms (size_t k, size_t m) const
Number of atoms of element m in species k.
void getAtoms (size_t k, double *atomArray) const
Get a vector containing the atomic composition of species k.
size_t speciesIndex (const std::string &name) const
Returns the index of a species named 'name' within the Phase object.
std::string speciesName (size_t k) const
Name of the species with index k.
std::string speciesSPName (int k) const
Returns the expanded species name of a species, including the phase name This is guaranteed to be unique within a Cantera problem.
const std::vector< std::string > & speciesNames () const
Return a const reference to the vector of species names.
size_t nSpecies () const
Returns the number of species in the phase.
void checkSpeciesIndex (size_t k) const
Check that the specified species index is in range.
void checkSpeciesArraySize (size_t kk) const
Check that an array size is at least nSpecies().
void setMoleFractionsByName (const compositionMap &xMap)
Set the species mole fractions by name.
void setMoleFractionsByName (const std::string &x)
Set the mole fractions of a group of species by name.
void setMassFractionsByName (const compositionMap &yMap)
Set the species mass fractions by name.
void setMassFractionsByName (const std::string &x)
Set the species mass fractions by name.
void setState_TRX (doublereal t, doublereal dens, const doublereal *x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRX (doublereal t, doublereal dens, const compositionMap &x)
Set the internally stored temperature (K), density, and mole fractions.
void setState_TRY (doublereal t, doublereal dens, const doublereal *y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TRY (doublereal t, doublereal dens, const compositionMap &y)
Set the internally stored temperature (K), density, and mass fractions.
void setState_TNX (doublereal t, doublereal n, const doublereal *x)
Set the internally stored temperature (K), molar density (kmol/m^3), and mole fractions.
void setState_TR (doublereal t, doublereal rho)
Set the internally stored temperature (K) and density (kg/m^3)
void setState_TX (doublereal t, doublereal *x)
Set the internally stored temperature (K) and mole fractions.
void setState_TY (doublereal t, doublereal *y)
Set the internally stored temperature (K) and mass fractions.
void setState_RX (doublereal rho, doublereal *x)
Set the density (kg/m^3) and mole fractions.
void setState_RY (doublereal rho, doublereal *y)
Set the density (kg/m^3) and mass fractions.
compositionMap getMoleFractionsByName (double threshold=0.0) const
Get the mole fractions by name.
doublereal moleFraction (size_t k) const
Return the mole fraction of a single species.
doublereal moleFraction (const std::string &name) const
Return the mole fraction of a single species.
compositionMap getMassFractionsByName (double threshold=0.0) const
Get the mass fractions by name.
doublereal massFraction (size_t k) const
Return the mass fraction of a single species.
doublereal massFraction (const std::string &name) const
Return the mass fraction of a single species.
void getMoleFractions (doublereal *const x) const
Get the species mole fraction vector.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
void getMassFractions (doublereal *const y) const
Get the species mass fractions.
const doublereal * massFractions () const
Return a const pointer to the mass fraction array.
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values and normalize them.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
void getConcentrations (doublereal *const c) const
Get the species concentrations (kmol/m^3).
doublereal concentration (const size_t k) const
Concentration of species k.
virtual void setConcentrations (const doublereal *const conc)
Set the concentrations to the specified values within the phase.
virtual void setConcentrationsNoNorm (const double *const conc)
Set the concentrations without ignoring negative concentrations.
doublereal elementalMassFraction (const size_t m) const
Elemental mass fraction of element m.
doublereal elementalMoleFraction (const size_t m) const
Elemental mole fraction of element m.
const doublereal * moleFractdivMMW () const
Returns a const pointer to the start of the moleFraction/MW array.
doublereal temperature () const
Temperature (K).
virtual doublereal density () const
Density (kg/m^3).
doublereal molarDensity () const
Molar density (kmol/m^3).
doublereal molarVolume () const
Molar volume (m^3/kmol).
virtual void setDensity (const doublereal density_)
Set the internally stored density (kg/m^3) of the phase.
virtual void setMolarDensity (const doublereal molarDensity)
Set the internally stored molar density (kmol/m^3) of the phase.
virtual void setTemperature (const doublereal temp)
Set the internally stored temperature of the phase (K).
doublereal mean_X (const doublereal *const Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal mean_X (const vector_fp &Q) const
Evaluate the mole-fraction-weighted mean of an array Q.
doublereal meanMolecularWeight () const
The mean molecular weight. Units: (kg/kmol)
doublereal sum_xlogx () const
Evaluate \(\sum_k X_k \log X_k \).
size_t addElement (const std::string &symbol, doublereal weight=-12345.0, int atomicNumber=0, doublereal entropy298=ENTROPY298_UNKNOWN, int elem_type=CT_ELEM_TYPE_ABSPOS)
Add an element.
shared_ptr< Species > species (const std::string &name) const
Return the Species object for the named species.
shared_ptr< Species > species (size_t k) const
Return the Species object for species whose index is k.
void ignoreUndefinedElements ()
Set behavior when adding a species containing undefined elements to just skip the species.
void addUndefinedElements ()
Set behavior when adding a species containing undefined elements to add those elements to the phase.
void throwUndefinedElements ()
Set the behavior when adding a species containing undefined elements to throw an exception.
Protected Attributes
doublereal m_p0
Reference state pressure.
doublereal m_logc0
Temporary storage for log of p/RT.
vector_fp m_h0_RT
Temporary storage for dimensionless reference state enthalpies.
vector_fp m_cp0_R
Temporary storage for dimensionless reference state heat capacities.
vector_fp m_g0_RT
Temporary storage for dimensionless reference state Gibbs energies.
vector_fp m_s0_R
Temporary storage for dimensionless reference state entropies.
vector_fp m_expg0_RT
vector_fp m_pp
Temporary array containing internally calculated partial pressures.
Protected Attributes inherited from ThermoPhase
MultiSpeciesThermo * m_spthermo
Pointer to the calculation manager for species reference-state thermodynamic properties.
std::vector< const XML_Node * > m_speciesData
Vector of pointers to the species databases.
doublereal m_phi
Stored value of the electric potential for this phase. Units are Volts.
vector_fp m_lambdaRRT
Vector of element potentials. Length equal to number of elements.
bool m_hasElementPotentials
Boolean indicating whether there is a valid set of saved element potentials for this phase.
bool m_chargeNeutralityNecessary
Boolean indicating whether a charge neutrality condition is a necessity.
int m_ssConvention
Contains the standard state convention.
vector_fp xMol_Ref
Reference Mole Fraction Composition.
doublereal m_tlast
last value of the temperature processed by reference state
Protected Attributes inherited from Phase
ValueCache m_cache
Cached for saved calculations within each ThermoPhase.
size_t m_kk
Number of species in the phase.
size_t m_ndim
Dimensionality of the phase.
vector_fp m_speciesComp
Atomic composition of the species.
vector_fp m_speciesSize
Vector of species sizes.
vector_fp m_speciesCharge
Vector of species charges. length m_kk.
std::map< std::string,
shared_ptr< Species > > m_species
UndefElement::behavior m_undefinedElementBehavior
Flag determining behavior when adding species with an undefined element.
Private Member Functions
void _updateThermo () const
Update the species reference state thermodynamic functions.
Additional Inherited Members
Protected Member Functions inherited from ThermoPhase
virtual void getCsvReportData (std::vector< std::string > &names, std::vector< vector_fp > &data) const
Fills names and data with the column names and species thermo properties to be included in the output of the reportCSV method.
Protected Member Functions inherited from Phase
void setMolecularWeight (const int k, const double mw)
Set the molecular weight of a single species to a given value.
virtual void compositionChanged ()
Apply changes to the state which are needed after the composition changes.
Detailed Description
Class IdealGasPhase represents low-density gases that obey the ideal gas equation of state.
IdealGasPhase derives from class ThermoPhase, and overloads the virtual methods defined there with ones that use expressions appropriate for ideal gas mixtures.
The independent unknowns are density, mass fraction, and temperature. the setPressure() function will calculate the density consistent with the current mass fraction vector and temperature and the desired pressure, and then set the density.
Specification of Species Standard State Properties
It is assumed that the reference state thermodynamics may be obtained by a pointer to a populated species thermodynamic property manager class in the base class, ThermoPhase::m_spthermo (see the base class MultiSpeciesThermo for a description of the specification of reference state species thermodynamics functions). The reference state, where the pressure is fixed at a single pressure, is a key species property calculation for the Ideal Gas Equation of state.
This class is optimized for speed of execution. All calls to thermodynamic functions first call internal routines (aka enthalpy_RT_ref()) which return references the reference state thermodynamics functions. Within these internal reference state functions, the function _updateThermo() is called, that first checks to see whether the temperature has changed. If it has, it updates the internal reference state thermo functions by calling the MultiSpeciesThermo object.
Functions for the calculation of standard state properties for species at arbitrary pressure are provided in IdealGasPhase. However, they are all derived from their reference state counterparts.
The standard state enthalpy is independent of pressure:
\[ h^o_k(T,P) = h^{ref}_k(T) \]
The standard state constant-pressure heat capacity is independent of pressure:
\[ Cp^o_k(T,P) = Cp^{ref}_k(T) \]
The standard state entropy depends in the following fashion on pressure:
\[ S^o_k(T,P) = S^{ref}_k(T) - R \ln(\frac{P}{P_{ref}}) \]
The standard state Gibbs free energy is obtained from the enthalpy and entropy functions:
\[ \mu^o_k(T,P) = h^o_k(T,P) - S^o_k(T,P) T \]
\[ \mu^o_k(T,P) = \mu^{ref}_k(T) + R T \ln(\frac{P}{P_{ref}}) \]
where
\[ \mu^{ref}_k(T) = h^{ref}_k(T) - T S^{ref}_k(T) \]
The standard state internal energy is obtained from the enthalpy function also
\[ u^o_k(T,P) = h^o_k(T) - R T \]
The molar volume of a species is given by the ideal gas law
\[ V^o_k(T,P) = \frac{R T}{P} \]
where R is the molar gas constant. For a complete list of physical constants used within Cantera, see Physical Constants .
Specification of Solution Thermodynamic Properties
The activity of a species defined in the phase is given by the ideal gas law:
\[ a_k = X_k \]
where \(X_k \) is the mole fraction of species k. The chemical potential for species k is equal to
\[ \mu_k(T,P) = \mu^o_k(T, P) + R T \log(X_k) \]
In terms of the reference state, the above can be rewritten
\[ \mu_k(T,P) = \mu^{ref}_k(T, P) + R T \log(\frac{P X_k}{P_{ref}}) \]
The partial molar entropy for species k is given by the following relation,
\[ \tilde{s}_k(T,P) = s^o_k(T,P) - R \log(X_k) = s^{ref}_k(T) - R \log(\frac{P X_k}{P_{ref}}) \]
The partial molar enthalpy for species k is
\[ \tilde{h}_k(T,P) = h^o_k(T,P) = h^{ref}_k(T) \]
The partial molar Internal Energy for species k is
\[ \tilde{u}_k(T,P) = u^o_k(T,P) = u^{ref}_k(T) \]
The partial molar Heat Capacity for species k is
\[ \tilde{Cp}_k(T,P) = Cp^o_k(T,P) = Cp^{ref}_k(T) \]
Application within Kinetics Managers
\(C^a_k\) are defined such that \(a_k = C^a_k / C^s_k, \) where \(C^s_k \) is a standard concentration defined below and \(a_k \) are activities used in the thermodynamic functions. These activity (or generalized) concentrations are used by kinetics manager classes to compute the forward and reverse rates of elementary reactions. The activity concentration, \(C^a_k \),is given by the following expression.
\[ C^a_k = C^s_k X_k = \frac{P}{R T} X_k \]
The standard concentration for species k is independent of k and equal to
\[ C^s_k = C^s = \frac{P}{R T} \]
For example, a bulk-phase binary gas reaction between species j and k, producing a new gas species l would have the following equation for its rate of progress variable, \(R^1 \), which has units of kmol m-3 s-1.
\[ R^1 = k^1 C_j^a C_k^a = k^1 (C^s a_j) (C^s a_k) \]
where
\[ C_j^a = C^s a_j \quad \mbox{and} \quad C_k^a = C^s a_k \]
\(C_j^a \) is the activity concentration of species j, and \(C_k^a \) is the activity concentration of species k. \(C^s \) is the standard concentration. \(a_j \) is the activity of species j which is equal to the mole fraction of j.
The reverse rate constant can then be obtained from the law of microscopic reversibility and the equilibrium expression for the system.
\[ \frac{a_j a_k}{ a_l} = K_a^{o,1} = \exp(\frac{\mu^o_l - \mu^o_j - \mu^o_k}{R T}) \]
\(K_a^{o,1} \) is the dimensionless form of the equilibrium constant, associated with the pressure dependent standard states \(\mu^o_l(T,P) \) and their associated activities, \(a_l \), repeated here:
\[ \mu_l(T,P) = \mu^o_l(T, P) + R T \log(a_l) \]
We can switch over to expressing the equilibrium constant in terms of the reference state chemical potentials
\[ K_a^{o,1} = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{P} \]
The concentration equilibrium constant, \(K_c \), may be obtained by changing over to activity concentrations. When this is done:
\[ \frac{C^a_j C^a_k}{ C^a_l} = C^o K_a^{o,1} = K_c^1 = \exp(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T}) * \frac{P_{ref}}{RT} \]
Kinetics managers will calculate the concentration equilibrium constant, \(K_c \), using the second and third part of the above expression as a definition for the concentration equilibrium constant.
For completeness, the pressure equilibrium constant may be obtained as well
\[ \frac{P_j P_k}{ P_l P_{ref}} = K_p^1 = \exp\left(\frac{\mu^{ref}_l - \mu^{ref}_j - \mu^{ref}_k}{R T} \right) \]
\(K_p \) is the simplest form of the equilibrium constant for ideal gases. However, it isn't necessarily the simplest form of the equilibrium constant for other types of phases; \(K_c \) is used instead because it is completely general.
The reverse rate of progress may be written down as
\[ R^{-1} = k^{-1} C_l^a = k^{-1} (C^o a_l) \]
where we can use the concept of microscopic reversibility to write the reverse rate constant in terms of the forward rate constant and the concentration equilibrium constant, \(K_c \).
\[ k^{-1} = k^1 K^1_c \]
\(k^{-1} \) has units of s-1.
Instantiation of the Class
The constructor for this phase is located in the default ThermoFactory for Cantera. A new IdealGasPhase may be created by the following code snippet:
XML_Node *xc = get_XML_File("silane.xml");
XML_Node * const xs = xc->findNameID("phase", "silane");
ThermoPhase *silane_tp = newPhase(*xs);
IdealGasPhase *silaneGas = dynamic_cast <IdealGasPhase *>(silane_tp);
or by the following constructor:
XML_Node *xc = get_XML_File("silane.xml");
XML_Node * const xs = xc->findNameID("phase", "silane");
IdealGasPhase *silaneGas = new IdealGasPhase(*xs);
XML Example
An example of an XML Element named phase setting up a IdealGasPhase object named silane is given below.
<!--     phase silane      -->
<phase dim="3" id="silane">
  <elementArray datasrc="elements.xml"> Si  H  He </elementArray>
  <speciesArray datasrc="#species_data">
    H2  H  HE  SIH4  SI  SIH  SIH2  SIH3  H3SISIH  SI2H6
    H2SISIH2  SI3H8  SI2  SI3
  </speciesArray>
  <reactionArray datasrc="#reaction_data"/>
  <thermo model="IdealGas"/>
  <kinetics model="GasKinetics"/>
  <transport model="None"/>
</phase>
The model attribute "IdealGas" of the thermo XML element identifies the phase as being of the type handled by the IdealGasPhase object.
Definition at line 286 of file IdealGasPhase.h.
Constructor & Destructor Documentation
IdealGasPhase ()
Default empty Constructor.
Definition at line 17 of file IdealGasPhase.cpp.
Referenced by IdealGasPhase::duplMyselfAsThermoPhase().
IdealGasPhase (const std::string & inputFile, const std::string & id = "")
Construct and initialize an IdealGasPhase ThermoPhase object directly from an ASCII input file.
Parameters
inputFile Name of the input file containing the phase XML data to set up the object
id ID of the phase in the input file. Defaults to the empty string.
Definition at line 23 of file IdealGasPhase.cpp.
References ThermoPhase::initThermoFile().
IdealGasPhase (XML_Node & phaseRef, const std::string & id = "")
Construct and initialize an IdealGasPhase ThermoPhase object directly from an XML database.
Parameters
phaseRef XML phase node containing the description of the phase
id id attribute containing the name of the phase. (default is the empty string)
Definition at line 30 of file IdealGasPhase.cpp.
References Cantera::importPhase().
Member Function Documentation
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate ThermoPhase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
These routines are basically wrappers around the derived copy constructor.
Reimplemented from ThermoPhase.
Definition at line 62 of file IdealGasPhase.cpp.
References IdealGasPhase::IdealGasPhase().
virtual int eosType () const inline virtual
Equation of state flag.
Returns the value cIdealGas, defined in mix_defs.h.
Deprecated:
To be removed after Cantera 2.3.
Reimplemented from ThermoPhase.
Definition at line 320 of file IdealGasPhase.h.
References Cantera::cIdealGas, and Cantera::warn_deprecated().
virtual std::string type () const inline virtual
String indicating the thermodynamic model implemented.
Usually corresponds to the name of the derived class, less any suffixes such as "Phase", TP", "VPSS", etc.
Reimplemented from ThermoPhase.
Definition at line 325 of file IdealGasPhase.h.
virtual doublereal enthalpy_mole () const inline virtual
Return the Molar enthalpy. Units: J/kmol.
For an ideal gas mixture,
\[ \hat h(T) = \sum_k X_k \hat h^0_k(T), \]
and is a function only of temperature. The standard-state pure-species enthalpies \(\hat h^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 344 of file IdealGasPhase.h.
References IdealGasPhase::enthalpy_RT_ref(), Phase::mean_X(), and ThermoPhase::RT().
doublereal entropy_mole () const virtual
Molar entropy.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat s(T, P) = \sum_k X_k \hat s^0_k(T) - \hat R \log (P/P^0). \]
The reference-state pure-species entropies \(\hat s^0_k(T) \) are computed by the species thermodynamic property manager.
See Also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 69 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Cantera::GasConstant, ThermoPhase::m_spthermo, Phase::mean_X(), IdealGasPhase::pressure(), MultiSpeciesThermo::refPressure(), and Phase::sum_xlogx().
doublereal cp_mole () const virtual
Molar heat capacity at constant pressure.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat c_p(t) = \sum_k \hat c^0_{p,k}(T). \]
The reference-state pure-species heat capacities \(\hat c^0_{p,k}(T) \) are computed by the species thermodynamic property manager.
See Also
MultiSpeciesThermo
Reimplemented from ThermoPhase.
Definition at line 74 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref(), Cantera::GasConstant, and Phase::mean_X().
Referenced by IdealGasPhase::cv_mole().
doublereal cv_mole () const virtual
Molar heat capacity at constant volume.
Units: J/kmol/K. For an ideal gas mixture,
\[ \hat c_v = \hat c_p - \hat R. \]
Reimplemented from ThermoPhase.
Definition at line 79 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_mole(), and Cantera::GasConstant.
virtual doublereal pressure () const inline virtual
Pressure.
Units: Pa. For an ideal gas mixture,
\[ P = n \hat R T. \]
Reimplemented from ThermoPhase.
Definition at line 388 of file IdealGasPhase.h.
References Cantera::GasConstant, Phase::molarDensity(), and Phase::temperature().
Referenced by IdealGasPhase::entropy_mole(), IdealGasPhase::getEntropy_R(), IdealGasPhase::getGibbs_RT(), IdealGasPhase::getPartialMolarEntropies(), IdealGasPhase::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), IdealGasPhase::isothermalCompressibility(), and IdealGasPhase::standardConcentration().
virtual void setPressure (doublereal p) inline virtual
Set the pressure at constant temperature and composition.
Units: Pa. This method is implemented by setting the mass density to
\[ \rho = \frac{P \overline W}{\hat R T }. \]
Parameters
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 402 of file IdealGasPhase.h.
References Phase::meanMolecularWeight(), ThermoPhase::RT(), and Phase::setDensity().
Referenced by StFlow::setGas(), and StFlow::setGasAtMidpoint().
virtual void setState_RP (doublereal rho, doublereal p) inline virtual
Set the density and pressure at constant composition.
Units: kg/m^3, Pa. This method is implemented by setting the density to the input value and setting the temperature to
\[ T = \frac{P \overline W}{\hat R \rho}. \]
Parameters
rho Density (kg/m^3)
p Pressure (Pa)
Reimplemented from ThermoPhase.
Definition at line 418 of file IdealGasPhase.h.
References Cantera::GasConstant, Phase::meanMolecularWeight(), Phase::setDensity(), and Phase::setTemperature().
virtual doublereal isothermalCompressibility () const inline virtual
Returns the isothermal compressibility. Units: 1/Pa.
The isothermal compressibility is defined as
\[ \kappa_T = -\frac{1}{v}\left(\frac{\partial v}{\partial P}\right)_T \]
For ideal gases it's equal to the inverse of the pressure
Reimplemented from ThermoPhase.
Definition at line 436 of file IdealGasPhase.h.
References IdealGasPhase::pressure().
virtual doublereal thermalExpansionCoeff () const inline virtual
Return the volumetric thermal expansion coefficient. Units: 1/K.
The thermal expansion coefficient is defined as
\[ \beta = \frac{1}{v}\left(\frac{\partial v}{\partial T}\right)_P \]
For ideal gases, it's equal to the inverse of the temperature.
Reimplemented from ThermoPhase.
Definition at line 448 of file IdealGasPhase.h.
References Phase::temperature().
virtual void getActivityConcentrations (doublereal * c) const inline virtual
This method returns the array of generalized concentrations.
For an ideal gas mixture, these are simply the actual concentrations.
Parameters
c Output array of generalized concentrations. The units depend upon the implementation of the reaction rate expressions within the phase.
Reimplemented from ThermoPhase.
Definition at line 493 of file IdealGasPhase.h.
References Phase::getConcentrations().
doublereal standardConcentration (size_t k = 0) const virtual
Returns the standard concentration \(C^0_k \), which is used to normalize the generalized concentration.
This is defined as the concentration by which the generalized concentration is normalized to produce the activity. In many cases, this quantity will be the same for all species in a phase. Since the activity for an ideal gas mixture is simply the mole fraction, for an ideal gas \(C^0_k = P/\hat R T \).
Parameters
k Optional parameter indicating the species. The default is to assume this refers to species 0.
Returns
Returns the standard Concentration in units of m3 kmol-1.
Reimplemented from ThermoPhase.
Definition at line 84 of file IdealGasPhase.cpp.
References IdealGasPhase::pressure(), and ThermoPhase::RT().
void getActivityCoefficients (doublereal * ac) const virtual
Get the array of non-dimensional activity coefficients at the current solution temperature, pressure, and solution concentration.
For ideal gases, the activity coefficients are all equal to one.
Parameters
ac Output vector of activity coefficients. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 89 of file IdealGasPhase.cpp.
References Phase::m_kk.
void getChemPotentials (doublereal * mu) const virtual
Get the species chemical potentials. Units: J/kmol.
This function returns a vector of chemical potentials of the species in solution at the current temperature, pressure and mole fraction of the solution.
Parameters
mu Output vector of species chemical potentials. Length: m_kk. Units: J/kmol
Reimplemented from ThermoPhase.
Definition at line 108 of file IdealGasPhase.cpp.
References IdealGasPhase::getStandardChemPotentials(), Phase::m_kk, Phase::moleFraction(), ThermoPhase::RT(), and Cantera::SmallNumber.
void getPartialMolarEnthalpies (doublereal * hbar) const virtual
Returns an array of partial molar enthalpies for the species in the mixture.
Units (J/kmol)
Parameters
hbar Output vector of species partial molar enthalpies. Length: m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 117 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), ThermoPhase::RT(), and Cantera::scale().
void getPartialMolarEntropies (doublereal * sbar) const virtual
Returns an array of partial molar entropies of the species in the solution.
Units: J/kmol/K.
Parameters
sbar Output vector of species partial molar entropies. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 123 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Cantera::GasConstant, Phase::m_kk, ThermoPhase::m_spthermo, Phase::moleFraction(), IdealGasPhase::pressure(), MultiSpeciesThermo::refPressure(), Cantera::scale(), and Cantera::SmallNumber.
void getPartialMolarIntEnergies (doublereal * ubar) const virtual
Return an array of partial molar internal energies for the species in the mixture.
Units: J/kmol.
Parameters
ubar Output vector of species partial molar internal energies. Length = m_kk. units are J/kmol.
Reimplemented from ThermoPhase.
Definition at line 134 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), Phase::m_kk, and ThermoPhase::RT().
void getPartialMolarCp (doublereal * cpbar) const virtual
Return an array of partial molar heat capacities for the species in the mixture.
Units: J/kmol/K
Parameters
cpbar Output vector of species partial molar heat capacities at constant pressure. Length = m_kk. units are J/kmol/K.
Reimplemented from ThermoPhase.
Definition at line 142 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref(), Cantera::GasConstant, and Cantera::scale().
void getPartialMolarVolumes (doublereal * vbar) const virtual
Return an array of partial molar volumes for the species in the mixture.
Units: m^3/kmol.
Parameters
vbar Output vector of species partial molar volumes. Length = m_kk. units are m^3/kmol.
Reimplemented from ThermoPhase.
Definition at line 148 of file IdealGasPhase.cpp.
References Phase::m_kk, and Phase::molarDensity().
void getStandardChemPotentials (doublereal * mu) const virtual
Get the array of chemical potentials at unit activity for the species at their standard states at the current T and P of the solution.
These are the standard state chemical potentials \(\mu^0_k(T,P) \). The values are evaluated at the current temperature and pressure of the solution
Parameters
mu Output vector of chemical potentials. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 96 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), MultiSpeciesThermo::refPressure(), ThermoPhase::RT(), and Cantera::scale().
Referenced by IdealGasPhase::getChemPotentials().
void getEnthalpy_RT (doublereal * hrt) const virtual
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
Parameters
hrt Output vector of nondimensional standard state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 158 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref().
void getEntropy_R (doublereal * sr) const virtual
Get the array of nondimensional Entropy functions for the standard state species at the current T and P of the solution.
Parameters
sr Output vector of nondimensional standard state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 164 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), and MultiSpeciesThermo::refPressure().
void getGibbs_RT (doublereal * grt) const virtual
Get the nondimensional Gibbs functions for the species in their standard states at the current T and P of the solution.
Parameters
grt Output vector of nondimensional standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 174 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), and MultiSpeciesThermo::refPressure().
void getPureGibbs (doublereal * gpure) const virtual
Get the Gibbs functions for the standard state of the species at the current T and P of the solution.
Units are Joules/kmol
Parameters
gpure Output vector of standard state Gibbs free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 184 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, ThermoPhase::m_spthermo, IdealGasPhase::pressure(), MultiSpeciesThermo::refPressure(), ThermoPhase::RT(), and Cantera::scale().
void getIntEnergy_RT (doublereal * urt) const virtual
Returns the vector of nondimensional Internal Energies of the standard state species at the current T and P of the solution.
Parameters
urt output vector of nondimensional standard state internal energies of the species. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 194 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), and Phase::m_kk.
void getCp_R (doublereal * cpr) const virtual
Get the nondimensional Heat Capacities at constant pressure for the species standard states at the current T and P of the solution.
Parameters
cpr Output vector of nondimensional standard state heat capacities. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 202 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref().
void getStandardVolumes (doublereal * vol) const virtual
Get the molar volumes of the species standard states at the current T and P of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 208 of file IdealGasPhase.cpp.
References Phase::m_kk, and Phase::molarDensity().
void getEnthalpy_RT_ref (doublereal * hrt) const virtual
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
hrt Output vector containing the nondimensional reference state enthalpies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 218 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref().
void getGibbs_RT_ref (doublereal * grt) const virtual
Returns the vector of nondimensional Gibbs Free Energies of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
grt Output vector containing the nondimensional reference state Gibbs Free energies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 224 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref().
void getGibbs_ref (doublereal * g) const virtual
Returns the vector of the Gibbs function of the reference state at the current temperature of the solution and the reference pressure for the species.
Parameters
g Output vector containing the reference state Gibbs Free energies. Length: m_kk. Units: J/kmol.
Reimplemented from ThermoPhase.
Definition at line 230 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), ThermoPhase::RT(), and Cantera::scale().
void getEntropy_R_ref (doublereal * er) const virtual
Returns the vector of nondimensional entropies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
er Output vector containing the nondimensional reference state entropies. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 236 of file IdealGasPhase.cpp.
References IdealGasPhase::entropy_R_ref().
void getIntEnergy_RT_ref (doublereal * urt) const virtual
Returns the vector of nondimensional internal Energies of the reference state at the current temperature of the solution and the reference pressure for each species.
Parameters
urt Output vector of nondimensional reference state internal energies of the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 242 of file IdealGasPhase.cpp.
References IdealGasPhase::enthalpy_RT_ref(), and Phase::m_kk.
void getCp_R_ref (doublereal * cprt) const virtual
Returns the vector of nondimensional constant pressure heat capacities of the reference state at the current temperature of the solution and reference pressure for each species.
Parameters
cprt Output vector of nondimensional reference state heat capacities at constant pressure for the species. Length: m_kk
Reimplemented from ThermoPhase.
Definition at line 250 of file IdealGasPhase.cpp.
References IdealGasPhase::cp_R_ref().
void getStandardVolumes_ref (doublereal * vol) const virtual
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
units = m^3 / kmol
Parameters
vol Output vector containing the standard state volumes. Length: m_kk.
Reimplemented from ThermoPhase.
Definition at line 256 of file IdealGasPhase.cpp.
References Phase::m_kk, IdealGasPhase::m_p0, and ThermoPhase::RT().
const vector_fp& enthalpy_RT_ref () const inline
Returns a reference to the dimensionless reference state enthalpy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 567 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_h0_RT.
Referenced by IdealGasPhase::enthalpy_mole(), StFlow::eval(), IdealGasPhase::getEnthalpy_RT(), IdealGasPhase::getEnthalpy_RT_ref(), IdealGasPhase::getIntEnergy_RT(), IdealGasPhase::getIntEnergy_RT_ref(), IdealGasPhase::getPartialMolarEnthalpies(), and IdealGasPhase::getPartialMolarIntEnergies().
const vector_fp& gibbs_RT_ref () const inline
Returns a reference to the dimensionless reference state Gibbs free energy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 577 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_g0_RT.
Referenced by IdealGasPhase::getGibbs_ref(), IdealGasPhase::getGibbs_RT(), IdealGasPhase::getGibbs_RT_ref(), IdealGasPhase::getPureGibbs(), IdealGasPhase::getStandardChemPotentials(), and IdealGasPhase::setToEquilState().
const vector_fp& entropy_R_ref () const inline
Returns a reference to the dimensionless reference state Entropy vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 587 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_s0_R.
Referenced by IdealGasPhase::entropy_mole(), IdealGasPhase::getEntropy_R(), IdealGasPhase::getEntropy_R_ref(), and IdealGasPhase::getPartialMolarEntropies().
const vector_fp& cp_R_ref () const inline
Returns a reference to the dimensionless reference state Heat Capacity vector.
This function is part of the layer that checks/recalculates the reference state thermo functions.
Definition at line 597 of file IdealGasPhase.h.
References IdealGasPhase::_updateThermo(), and IdealGasPhase::m_cp0_R.
Referenced by IdealGasPhase::cp_mole(), StFlow::eval(), IdealGasPhase::getCp_R(), IdealGasPhase::getCp_R_ref(), and IdealGasPhase::getPartialMolarCp().
bool addSpecies (shared_ptr< Species > spec) virtual
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file. They are not normally used in application programs. To see how they are used, see importPhase().
Reimplemented from ThermoPhase.
Definition at line 264 of file IdealGasPhase.cpp.
References ThermoPhase::addSpecies(), IdealGasPhase::m_cp0_R, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, Phase::m_kk, IdealGasPhase::m_p0, IdealGasPhase::m_pp, IdealGasPhase::m_s0_R, and ThermoPhase::refPressure().
void setToEquilState (const doublereal * lambda_RT) virtual
This method is used by the ChemEquil equilibrium solver.
It sets the state such that the chemical potentials satisfy
\[ \frac{\mu_k}{\hat R T} = \sum_m A_{k,m} \left(\frac{\lambda_m} {\hat R T}\right) \]
where \(\lambda_m \) is the element potential of element m. The temperature is unchanged. Any phase (ideal or not) that implements this method can be equilibrated by ChemEquil.
Parameters
lambda_RT Input vector of dimensionless element potentials The length is equal to nElements().
Reimplemented from ThermoPhase.
Definition at line 281 of file IdealGasPhase.cpp.
References IdealGasPhase::gibbs_RT_ref(), Phase::m_kk, IdealGasPhase::m_p0, IdealGasPhase::m_pp, and ThermoPhase::setState_PX().
void _updateThermo () const private
Update the species reference state thermodynamic functions.
This method is called each time a thermodynamic property is requested, to check whether the internal species properties within the object need to be updated. Currently, this updates the species thermo polynomial values for the current value of the temperature. A check is made to see if the temperature has changed since the last evaluation. This object does not contain any persistent data that depends on the concentration, that needs to be updated. The state object modifies its concentration dependent information at the time the setMoleFractions() (or equivalent) call is made.
Definition at line 308 of file IdealGasPhase.cpp.
References ValueCache::getId(), ValueCache::getScalar(), Phase::m_cache, IdealGasPhase::m_cp0_R, IdealGasPhase::m_g0_RT, IdealGasPhase::m_h0_RT, Phase::m_kk, IdealGasPhase::m_logc0, IdealGasPhase::m_p0, IdealGasPhase::m_s0_R, ThermoPhase::m_spthermo, ThermoPhase::RT(), CachedValue< T >::state1, Phase::temperature(), and MultiSpeciesThermo::update().
Referenced by IdealGasPhase::cp_R_ref(), IdealGasPhase::enthalpy_RT_ref(), IdealGasPhase::entropy_R_ref(), and IdealGasPhase::gibbs_RT_ref().
Member Data Documentation
doublereal m_p0 protected
Reference state pressure.
Value of the reference state pressure in Pascals. All species must have the same reference state pressure.
Definition at line 613 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::addSpecies(), IdealGasPhase::getStandardVolumes_ref(), and IdealGasPhase::setToEquilState().
doublereal m_logc0 mutable protected
Temporary storage for log of p/RT.
Definition at line 616 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo().
vector_fp m_h0_RT mutable protected
Temporary storage for dimensionless reference state enthalpies.
Definition at line 619 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::addSpecies(), and IdealGasPhase::enthalpy_RT_ref().
vector_fp m_cp0_R mutable protected
Temporary storage for dimensionless reference state heat capacities.
Definition at line 622 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::addSpecies(), and IdealGasPhase::cp_R_ref().
vector_fp m_g0_RT mutable protected
Temporary storage for dimensionless reference state Gibbs energies.
Definition at line 625 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::addSpecies(), and IdealGasPhase::gibbs_RT_ref().
vector_fp m_s0_R mutable protected
Temporary storage for dimensionless reference state entropies.
Definition at line 628 of file IdealGasPhase.h.
Referenced by IdealGasPhase::_updateThermo(), IdealGasPhase::addSpecies(), and IdealGasPhase::entropy_R_ref().
vector_fp m_pp mutable protected
Temporary array containing internally calculated partial pressures.
Definition at line 633 of file IdealGasPhase.h.
Referenced by IdealGasPhase::addSpecies(), and IdealGasPhase::setToEquilState().
The documentation for this class was generated from the following files:
IdealGasPhase.h
IdealGasPhase.cpp