Cantera: PseudoBinaryVPSSTP Class Reference
PseudoBinaryVPSSTP Class Reference
Thermodynamic Properties
#include <PseudoBinaryVPSSTP.h>
Public Member Functions
PseudoBinaryVPSSTP ()
Constructor.
PseudoBinaryVPSSTP (const PseudoBinaryVPSSTP &b)
Copy constructor.
PseudoBinaryVPSSTP & operator= (const PseudoBinaryVPSSTP &b)
Assignment operator.
virtual ThermoPhase * duplMyselfAsThermoPhase () const
Duplication routine for objects which inherit from ThermoPhase.
virtual void calcPseudoBinaryMoleFractions () const
Calculate pseudo binary mole fractions.
Utilities
virtual int eosType () const
Equation of state type flag.
Activities, Standard States, and Activity Concentrations
The activity \(a_k\) of a species in solution is related to the chemical potential by
\[ \mu_k = \mu_k^0(T) + \hat R T \log a_k. \]
The quantity \(\mu_k^0(T,P)\) is the chemical potential at unit activity, which depends only on temperature and pressure.
virtual doublereal standardConcentration (size_t k=0) const
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
virtual doublereal logStandardConc (size_t k=0) const
Returns the natural logarithm of the standard concentration of the kth species.
Partial Molar Properties of the Solution
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
Public Member Functions inherited from GibbsExcessVPSSTP
GibbsExcessVPSSTP ()
GibbsExcessVPSSTP (const GibbsExcessVPSSTP &b)
Copy constructor.
GibbsExcessVPSSTP & operator= (const GibbsExcessVPSSTP &b)
Assignment operator.
virtual void getActivityConcentrations (doublereal *c) const
This method returns an array of generalized concentrations.
virtual void getUnitsStandardConc (double *uA, int k=0, int sizeUA=6) const
Returns the units of the standard and generalized concentrations Note they have the same units, as their ratio is defined to be equal to the activity of the kth species in the solution, which is unitless.
virtual void getActivities (doublereal *ac) const
Get the array of non-dimensional activities (molality based for this class and classes that derive from it) at the current solution temperature, pressure, and solution concentration.
virtual void getActivityCoefficients (doublereal *ac) const
Get the array of non-dimensional molar-based activity coefficients at the current solution temperature, pressure, and solution concentration.
virtual void getdlnActCoeffdT (doublereal *dlnActCoeffdT) const
Get the array of temperature derivatives of the log activity coefficients.
virtual void getdlnActCoeffdlnN (const size_t ld, doublereal *const dlnActCoeffdlnN)
Get the array of derivatives of the log activity coefficients with respect to the log of the species mole numbers.
virtual void getdlnActCoeffdlnX (doublereal *dlnActCoeffdlnX) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getElectrochemPotentials (doublereal *mu) const
Get the species electrochemical potentials.
virtual void getPartialMolarVolumes (doublereal *vbar) const
Return an array of partial molar volumes for the species in the mixture.
virtual const vector_fp & getPartialMolarVolumes () const
virtual void setState_TP (doublereal t, doublereal p)
Set the temperature (K) and pressure (Pa)
virtual void setMassFractions (const doublereal *const y)
Set the mass fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMassFractions_NoNorm (const doublereal *const y)
Set the mass fractions to the specified values without normalizing.
virtual void setMoleFractions (const doublereal *const x)
Set the mole fractions to the specified values, and then normalize them so that they sum to 1.0.
virtual void setMoleFractions_NoNorm (const doublereal *const x)
Set the mole fractions to the specified values without normalizing.
virtual void setConcentrations (const doublereal *const c)
Set the concentrations to the specified values within the phase.
virtual void setPressure (doublereal p)
Set the internally stored pressure (Pa) at constant temperature and composition.
Public Member Functions inherited from VPStandardStateTP
VPStandardStateTP ()
Constructor.
VPStandardStateTP (const VPStandardStateTP &b)
Copy Constructor.
VPStandardStateTP & operator= (const VPStandardStateTP &b)
Assignment operator.
virtual ~VPStandardStateTP ()
Destructor.
virtual int standardStateConvention () const
This method returns the convention used in specification of the standard state, of which there are currently two, temperature based, and variable pressure based.
virtual void getdlnActCoeffdlnN_diag (doublereal *dlnActCoeffdlnN_diag) const
Get the array of log concentration-like derivatives of the log activity coefficients.
void getChemPotentials_RT (doublereal *mu) const
Get the array of non-dimensional species chemical potentials.
virtual void getStandardChemPotentials (doublereal *mu) const
Get the array of chemical potentials at unit activity.
virtual void getEnthalpy_RT (doublereal *hrt) const
Get the nondimensional Enthalpy functions for the species at their standard states at the current T and P of the solution.
virtual void getEntropy_R (doublereal *sr) const
Get the array of nondimensional Enthalpy functions for the standard state species at the current T and P of the solution.
virtual void getGibbs_RT (doublereal *grt) const
Get the nondimensional Gibbs functions for the species at their standard states of solution at the current T and P of the solution.
void getPureGibbs (doublereal *gpure) const
Get the standard state Gibbs functions for each species at the current T and P.
virtual void getIntEnergy_RT (doublereal *urt) const
Returns the vector of nondimensional internal Energies of the standard state at the current temperature and pressure of the solution for each species.
virtual void getCp_R (doublereal *cpr) const
Get the nondimensional Heat Capacities at constant pressure for the standard state of the species at the current T and P.
virtual void getStandardVolumes (doublereal *vol) const
Get the molar volumes of each species in their standard states at the current T and P of the solution.
virtual const vector_fp & getStandardVolumes () const
virtual void setTemperature (const doublereal temp)
Set the temperature of the phase.
doublereal pressure () const
Returns the current pressure of the phase.
virtual void updateStandardStateThermo () const
Updates the standard state thermodynamic functions at the current T and P of the solution.
virtual void getEnthalpy_RT_ref (doublereal *hrt) const
Returns the vector of nondimensional enthalpies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_RT_ref (doublereal *grt) const
Returns the vector of nondimensional Gibbs free energies of the reference state at the current temperature of the solution and the reference pressure for the species.
virtual void getGibbs_ref (doublereal *g) const
virtual void getEntropy_R_ref (doublereal *er) const
virtual void getCp_R_ref (doublereal *cprt) const
virtual void getStandardVolumes_ref (doublereal *vol) const
Get the molar volumes of the species reference states at the current T and P_ref of the solution.
virtual void setParametersFromXML (const XML_Node &eosdata)
Set equation of state parameter values from XML entries.
void setVPSSMgr (VPSSMgr *vp_ptr)
set the VPSS Mgr
VPSSMgr * provideVPSSMgr ()
Return a pointer to the VPSSMgr for this phase.
void createInstallPDSS (size_t k, const XML_Node &s, const XML_Node *phaseNode_ptr)
PDSS * providePDSS (size_t k)
const PDSS * providePDSS (size_t k) const
Initialization
The following methods are used in the process of constructing the phase and setting its parameters from a specification in an input file.
They are not normally used in application programs. To see how they are used, see files importCTML.cpp and ThermoFactory.cpp.
int PBType_
size_t numPBSpecies_
Number of pseudo binary species.
size_t indexSpecialSpecies_
index of special species
std::vector< doublereal > PBMoleFractions_
std::vector< int > cationList_
size_t numCationSpecies_
std::vector< int > anionList_
size_t numAnionSpecies_
std::vector< int > passThroughList_
size_t numPassThroughSpecies_
size_t neutralPBindexStart
ThermoPhase * cationPhase_
ThermoPhase * anionPhase_
std::vector< doublereal > moleFractionsTmp_
virtual void initThermo ()
void initThermoXML (XML_Node &phaseNode, const std::string &id)
Import and initialize a ThermoPhase object.
virtual std::string report (bool show_thermo=true) const
returns a summary of the state of the phase as a string
void initLengths ()
Initialize lengths of local variables after all species have been identified.
doublereal err (const std::string &msg) const
Error function.
Additional Inherited Members
Protected Member Functions inherited from GibbsExcessVPSSTP
double checkMFSum (const doublereal *const x) const
utility routine to check mole fraction sum
void calcDensity ()
Calculate the density of the mixture using the partial molar volumes and mole fractions as input.
Protected Attributes inherited from GibbsExcessVPSSTP
std::vector< doublereal > moleFractions_
Storage for the current values of the mole fractions of the species.
std::vector< doublereal > lnActCoeff_Scaled_
Storage for the current values of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdT_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > d2lnActCoeffdT2_Scaled_
Storage for the current derivative values of the gradients with respect to temperature of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnN_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
std::vector< doublereal > dlnActCoeffdlnX_diag_
Storage for the current derivative values of the gradients with respect to logarithm of the mole fraction of the log of the activity coefficients of the species.
Array2D dlnActCoeffdlnN_
Storage for the current derivative values of the gradients with respect to logarithm of the species mole number of the log of the activity coefficients of the species.
std::vector< doublereal > m_pp
Temporary storage space that is fair game.
Detailed Description
PseudoBinaryVPSSTP is a derived class of ThermoPhase GibbsExcessVPSSTP that handles variable pressure standard state methods for calculating thermodynamic properties that are further based on expressing the Excess Gibbs free energy as a function of the mole fractions (or pseudo mole fractions) of constituents. This category is the workhorse for describing molten salts, solid-phase mixtures of semiconductors, and mixtures of miscible and semi-miscible compounds.
It includes
regular solutions
Margules expansions
NTRL equation
Wilson's equation
UNIQUAC equation of state.
This class adds additional functions onto the ThermoPhase interface that handles the calculation of the excess Gibbs free energy. The ThermoPhase class includes a member function, ThermoPhase::activityConvention() that indicates which convention the activities are based on. The default is to assume activities are based on the molar convention. That default is used here.
All of the Excess Gibbs free energy formulations in this area employ symmetrical formulations.
This layer will massage the mole fraction vector to implement cation and anion based mole numbers in an optional manner
The way that it collects the cation and anion based mole numbers is via holding two extra ThermoPhase objects. These can include standard states for salts.
Definition at line 65 of file PseudoBinaryVPSSTP.h.
Constructor & Destructor Documentation
PseudoBinaryVPSSTP ()
Constructor.
This doesn't do much more than initialize constants with default values for water at 25C. Water molecular weight comes from the default elements.xml file. It actually differs slightly from the IAPWS95 value of 18.015268. However, density conservation and therefore element conservation is the more important principle to follow.
Definition at line 28 of file PseudoBinaryVPSSTP.cpp.
Referenced by PseudoBinaryVPSSTP::duplMyselfAsThermoPhase().
PseudoBinaryVPSSTP (const PseudoBinaryVPSSTP & b)
Copy constructor.
Parameters
b class to be copied
Definition at line 42 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::operator=().
Member Function Documentation
PseudoBinaryVPSSTP & operator= (const PseudoBinaryVPSSTP & b)
Assignment operator.
Parameters
b class to be copied.
Definition at line 58 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::indexSpecialSpecies_, PseudoBinaryVPSSTP::numPBSpecies_, and GibbsExcessVPSSTP::operator=().
Referenced by PseudoBinaryVPSSTP::PseudoBinaryVPSSTP().
ThermoPhase * duplMyselfAsThermoPhase () const virtual
Duplication routine for objects which inherit from ThermoPhase.
This virtual routine can be used to duplicate thermophase objects inherited from ThermoPhase even if the application only has a pointer to ThermoPhase to work with.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 83 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::PseudoBinaryVPSSTP().
int eosType () const virtual
Equation of state type flag.
The ThermoPhase base class returns zero. Subclasses should define this to return a unique non-zero value. Known constants defined for this purpose are listed in mix_defs.h.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 88 of file PseudoBinaryVPSSTP.cpp.
Referenced by PseudoBinaryVPSSTP::err().
doublereal standardConcentration (size_t k = 0) const virtual
The standard concentration \(C^0_k \) used to normalize the generalized concentration.
In many cases, this quantity will be the same for all species in a phase - for example, for an ideal gas \(C^0_k = P/\hat R T \). For this reason, this method returns a single value, instead of an array. However, for phases in which the standard concentration is species-specific (e.g. surface species of different sizes), this method may be called with an optional parameter indicating the species.
Parameters
k species index. Defaults to zero.
Reimplemented from GibbsExcessVPSSTP.
Definition at line 93 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::err().
doublereal logStandardConc (size_t k = 0) const virtual
Returns the natural logarithm of the standard concentration of the kth species.
Parameters
k species index
Reimplemented from GibbsExcessVPSSTP.
Definition at line 99 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::err().
void getElectrochemPotentials (doublereal * mu) const
Get the species electrochemical potentials.
These are partial molar quantities. This method adds a term \(Fz_k \phi_k \) to the to each chemical potential.
Units: J/kmol
Parameters
mu output vector containing the species electrochemical potentials. Length: m_kk.
Definition at line 105 of file PseudoBinaryVPSSTP.cpp.
References Phase::charge(), ThermoPhase::electricPotential(), ThermoPhase::getChemPotentials(), and Phase::m_kk.
void calcPseudoBinaryMoleFractions () const virtual
Calculate pseudo binary mole fractions.
Definition at line 114 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::indexSpecialSpecies_, Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, and PseudoBinaryVPSSTP::numPBSpecies_.
void initThermo () virtual
Initialize. This method is provided to allow subclasses to perform any initialization required after all species have been added. For example, it might be used to resize internal work arrays that must have an entry for each species. The base class implementation does nothing, and subclasses that do not require initialization do not need to overload this method. When importing a CTML phase description, this method is called just prior to returning from function importPhase.
See Also
importCTML.cpp
Reimplemented from GibbsExcessVPSSTP.
Definition at line 181 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::initLengths(), and GibbsExcessVPSSTP::initThermo().
void initThermoXML (XML_Node & phaseNode, const std::string & id) virtual
Import and initialize a ThermoPhase object.
Parameters
phaseNode This object must be the phase node of a complete XML tree description of the phase, including all of the species data. In other words while "phase" must point to an XML phase object, it must have sibling nodes "speciesData" that describe the species in the phase.
id ID of the phase. If nonnull, a check is done to see if phaseNode is pointing to the phase with the correct id.
Reimplemented from VPStandardStateTP.
Definition at line 193 of file PseudoBinaryVPSSTP.cpp.
References VPStandardStateTP::initThermoXML().
std::string report (bool show_thermo = true) const virtual
returns a summary of the state of the phase as a string
Parameters
show_thermo If true, extra information is printed out about the thermodynamic state of the system.
Reimplemented from ThermoPhase.
Definition at line 198 of file PseudoBinaryVPSSTP.cpp.
References ThermoPhase::cp_mass(), ThermoPhase::cp_mole(), ThermoPhase::cv_mass(), ThermoPhase::cv_mole(), Phase::density(), ThermoPhase::electricPotential(), ThermoPhase::enthalpy_mass(), ThermoPhase::enthalpy_mole(), ThermoPhase::entropy_mass(), ThermoPhase::entropy_mole(), GibbsExcessVPSSTP::getActivities(), ThermoPhase::getChemPotentials(), Phase::getMoleFractions(), VPStandardStateTP::getStandardChemPotentials(), ThermoPhase::gibbs_mass(), ThermoPhase::gibbs_mole(), ThermoPhase::intEnergy_mass(), ThermoPhase::intEnergy_mole(), Phase::meanMolecularWeight(), Phase::name(), Phase::nSpecies(), VPStandardStateTP::pressure(), CanteraError::save(), and Phase::temperature().
void initLengths () private
Initialize lengths of local variables after all species have been identified.
Definition at line 187 of file PseudoBinaryVPSSTP.cpp.
References Phase::m_kk, GibbsExcessVPSSTP::moleFractions_, and Phase::nSpecies().
Referenced by PseudoBinaryVPSSTP::initThermo().
doublereal err (const std::string & msg) const private
Error function.
Print an error string and exit
Parameters
msg Message to be printed
Definition at line 174 of file PseudoBinaryVPSSTP.cpp.
References PseudoBinaryVPSSTP::eosType(), and Cantera::int2str().
Referenced by PseudoBinaryVPSSTP::logStandardConc(), and PseudoBinaryVPSSTP::standardConcentration().
Member Data Documentation
size_t numPBSpecies_ protected
Number of pseudo binary species.
Definition at line 229 of file PseudoBinaryVPSSTP.h.
Referenced by PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), and PseudoBinaryVPSSTP::operator=().
size_t indexSpecialSpecies_ protected
index of special species
Definition at line 232 of file PseudoBinaryVPSSTP.h.
Referenced by PseudoBinaryVPSSTP::calcPseudoBinaryMoleFractions(), and PseudoBinaryVPSSTP::operator=().
The documentation for this class was generated from the following files:
PseudoBinaryVPSSTP.h
PseudoBinaryVPSSTP.cpp