Cantera: Reactor Class Reference
Reactor Class Reference
Class Reactor is a general-purpose class for stirred reactors.
#include <Reactor.h>
Public Member Functions
Reactor ()
Default constructor.
virtual ~Reactor ()
Destructor.
virtual int type () const
template<class G >
void insert (G &contents)
Insert something into the reactor.
void setKineticsMgr (Kinetics &kin)
void disableChemistry ()
void enableChemistry ()
void setEnergy (int eflag=1)
Set the energy equation on or off.
bool energyEnabled () const
Returns 'true' if solution of the energy equation is enabled.
virtual size_t neq ()
virtual void getInitialConditions (doublereal t0, size_t leny, doublereal *y)
virtual void initialize (doublereal t0=0.0)
Initialize the reactor.
virtual void evalEqs (doublereal t, doublereal *y, doublereal *ydot, doublereal *params)
virtual void updateState (doublereal *y)
Set the mixture to a state consistent with solution vector y.
virtual size_t nSensParams ()
virtual void addSensitivityReaction (size_t rxn)
std::vector< std::pair< void
*, int > > getSensitivityOrder () const
virtual size_t componentIndex (const std::string &nm) const
Public Member Functions inherited from ReactorBase
ReactorBase (const std::string &name="(none)")
std::string name () const
void setName (const std::string &name)
void restoreState ()
Set the state of the Phase object associated with this reactor to the reactor's current state.
thermo_t & contents ()
return a reference to the contents.
const thermo_t & contents () const
doublereal residenceTime ()
int error (const std::string &msg) const
ReactorNet & network ()
The ReactorNet that this reactor belongs to.
void setNetwork (ReactorNet *net)
Set the ReactorNet that this reactor belongs to.
void setInitialVolume (doublereal vol)
Set the initial reactor volume.
void setThermoMgr (thermo_t &thermo)
Specify the mixture contained in the reactor.
void addInlet (FlowDevice &inlet)
void addOutlet (FlowDevice &outlet)
FlowDevice & inlet (size_t n=0)
FlowDevice & outlet (size_t n=0)
size_t nInlets ()
size_t nOutlets ()
size_t nWalls ()
void addWall (Wall &w, int lr)
Wall & wall (size_t n)
virtual void start ()
doublereal volume () const
Returns the current volume of the reactor.
doublereal density () const
doublereal temperature () const
doublereal enthalpy_mass () const
doublereal intEnergy_mass () const
doublereal pressure () const
doublereal mass () const
const doublereal * massFractions () const
doublereal massFraction (size_t k) const
Protected Attributes
Kinetics * m_kin
Pointer to the homogeneous Kinetics object that handles the reactions.
doublereal m_vdot
Tolerance on the temperature.
doublereal m_Q
vector_fp m_work
vector_fp m_sdot
bool m_chem
bool m_energy
size_t m_nv
size_t m_nsens
std::vector< size_t > m_pnum
std::vector< size_t > m_nsens_wall
vector_fp m_mult_save
Protected Attributes inherited from ReactorBase
size_t m_nsp
Number of homogeneous species in the mixture.
thermo_t * m_thermo
doublereal m_vol
doublereal m_vol0
bool m_init
size_t m_nInlets
size_t m_nOutlets
bool m_open
doublereal m_enthalpy
doublereal m_intEnergy
doublereal m_pressure
vector_fp m_state
std::vector< FlowDevice * > m_inlet
std::vector< FlowDevice * > m_outlet
std::vector< Wall * > m_wall
vector_int m_lr
size_t m_nwalls
std::string m_name
double m_rho0
ReactorNet * m_net
The ReactorNet that this reactor is part of.
Detailed Description
Class Reactor is a general-purpose class for stirred reactors.
The reactor may have an arbitrary number of inlets and outlets, each of which may be connected to a "flow device" such as a mass flow controller, a pressure regulator, etc. Additional reactors may be connected to the other end of the flow device, allowing construction of arbitrary reactor networks.
The reactor class integrates the same governing equations no matter what type of reactor is simulated. The differences among reactor types are completely specified by the attached flow devices and the time-dependent user-specified boundary conditions.
If an instance of class Reactor is used directly, it will simulate an adiabatic, constant volume reactor with gas-phase chemistry but no surface chemistry. Other reactor types may be simulated by deriving a class from Reactor and overloading method getParams. This method allows specifying the following in terms of the instantaneous reactor state:
rate of change of the total volume (m^3/s)
surface heat loss rate (W)
species surface production rates (kmol/s)
class Reactor inherits from both ReactorBase and FuncEval. ReactorBase provides the basic reactor-like methods that FlowDevice instances can access to determine their mass flow rate. Class FuncEval is the class used to define a system of ODE's to be integrated.
Definition at line 49 of file Reactor.h.
Constructor & Destructor Documentation
Reactor ()
Default constructor.
Definition at line 22 of file Reactor.cpp.
virtual ~Reactor () inline virtual
Destructor.
Deletes the integrator.
Definition at line 60 of file Reactor.h.
Member Function Documentation
void insert (G & contents) inline
Insert something into the reactor.
The 'something' must belong to a class that is a subclass of both ThermoPhase and Kinetics.
Definition at line 72 of file Reactor.h.
References ReactorBase::setThermoMgr().
void setEnergy (int eflag = 1) inline
Set the energy equation on or off.
Definition at line 94 of file Reactor.h.
bool energyEnabled () const inline
Returns 'true' if solution of the energy equation is enabled.
Definition at line 103 of file Reactor.h.
void initialize (doublereal t0 = 0.0) virtual
Initialize the reactor.
Must be called after specifying the (and if necessary the inlet mixture) and before calling advance.
Reimplemented from ReactorBase.
Reimplemented in ConstPressureReactor, and FlowReactor.
Definition at line 74 of file Reactor.cpp.
References ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), Reactor::m_kin, ReactorBase::m_nsp, ThermoPhase::pressure(), Phase::restoreState(), and Kinetics::thermo().
void updateState (doublereal * y) virtual
Set the mixture to a state consistent with solution vector y.
Reimplemented in ConstPressureReactor, and FlowReactor.
Definition at line 126 of file Reactor.cpp.
References ThermoPhase::cv_mass(), ThermoPhase::enthalpy_mass(), ThermoPhase::intEnergy_mass(), ReactorBase::m_nsp, Phase::nSpecies(), ThermoPhase::pressure(), Phase::saveState(), Phase::setDensity(), Phase::setMassFractions(), and Phase::setState_TR().
Member Data Documentation
Kinetics* m_kin protected
Pointer to the homogeneous Kinetics object that handles the reactions.
Definition at line 133 of file Reactor.h.
Referenced by ConstPressureReactor::initialize(), and Reactor::initialize().
doublereal m_vdot protected
Tolerance on the temperature.
Definition at line 136 of file Reactor.h.
The documentation for this class was generated from the following files:
Reactor.h
Reactor.cpp