Cantera: Writing messages to the screen
Writing messages to the screen
Diagnostic Output
Classes
class Application
Class to hold global data.
class Logger
Base class for 'loggers' that write text messages to log files.
Functions
void writelog (const std::string &msg)
Write a message to the screen.
void setLogger (Logger *logwriter)
Install a logger.
template<typename... Args>
void writelog (const std::string &fmt, const Args &...args)
Write a formatted message to the screen.
template<typename... Args>
void writelogf (const char *fmt, const Args &...args)
Write a formatted message to the screen.
Detailed Description
Function Documentation
void writelog (const std::string & msg)
Write a message to the screen.
The string may be of any length, and may contain end-of-line characters. This method is used throughout Cantera to write log messages. It can also be called by user programs. The advantage of using writelog over writing directly to the standard output is that messages written with writelog will display correctly even when Cantera is used from MATLAB or other application that do not have a standard output stream.
Parameters
msg c++ string to be written to the screen
Definition at line 90 of file application.cpp.
References Application::Messages::logwriter.
void setLogger (Logger * logwriter)
Install a logger.
Called by the language interfaces to install an appropriate logger. The logger is used for the writelog() function
Parameters
logwriter Pointer to a logger object
See also
Logger.
Definition at line 85 of file application.cpp.
References Application::Messages::logwriter.
void Cantera::writelog (const std::string & fmt, const Args &... args)
Write a formatted message to the screen.
This function passes its arguments to the fmt library 'format' function to generate a formatted string from a Python-style (curly braces) format string. This method is used throughout Cantera to write log messages. It can also be called by user programs. The advantage of using writelog over writing directly to the standard output is that messages written with writelog will display correctly even when Cantera is used from MATLAB or other application that do not have a standard output stream.
Definition at line 179 of file global.h.
References Cantera::writelog_direct().
Referenced by Cantera::BasisOptimize(), MixtureFugacityTP::calculatePsat(), InterfaceKinetics::checkPartialEquil(), Cantera::ck2cti(), Cantera::ct2ctml(), MultiNewton::dampStep(), ChemEquil::dampStep(), Cantera::ElemRearrange(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), FuncEval::eval_nothrow(), GasTransport::fitCollisionIntegrals(), GasTransport::fitProperties(), Cantera::getFloatArray(), Cantera::getFloatCurrent(), Cantera::getInteger(), MMCollisionInt::init(), ChemEquil::initialize(), ReactorNet::initialize(), PDSS_HKFT::initThermo(), Sim1D::newtonSolve(), RedlichKwongMFTP::NicholsSolve(), solveSP::print_header(), HMWSoln::printCoeffs(), solveSP::printIteration(), Sim1D::refine(), StFlow::restore(), Sim1D::restore(), Domain1D::restore(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), Refiner::setCriteria(), ChemEquil::setInitialMoles(), Integrator::setMaxErrTestFails(), Sim1D::showSolution(), Inlet1D::showSolution(), StFlow::showSolution(), Surf1D::showSolution(), ReactingSurf1D::showSolution(), Domain1D::showSolution(), MultiNewton::solve(), RootFind::solve(), solveSP::solveSurfProb(), OneDim::timeStep(), NasaPoly2::validate(), VCS_SOLVE::vcs_basopt(), Cantera::vcs_Cantera_to_vprob(), VCS_SOLVE::vcs_deltag(), VCS_SOLVE::vcs_printSpeciesChemPot(), ResidEval::writeSolution(), OneDim::writeStats(), and XML_Node::XML_Node().
void Cantera::writelogf (const char * fmt, const Args &... args)
Write a formatted message to the screen.
Using the printf formatting of C, write a message to the screen with variable values.
Here, we format an internal string with the correct values and then feed it into writelog().
Parameters
fmt c format string for the following arguments
args arguments used to interpolate the format string
Definition at line 200 of file global.h.
References Cantera::actEnergyToSI(), Cantera::close_XML_File(), Cantera::get_XML_File(), Cantera::get_XML_from_string(), Cantera::get_XML_NameID(), Cantera::get_XML_Node(), Cantera::make_deprecation_warnings_fatal(), Cantera::setLogger(), Cantera::suppress_deprecation_warnings(), Cantera::toSI(), Cantera::warn_deprecated(), Cantera::writelog_direct(), and Cantera::writelogendl().
Referenced by Cantera::BasisOptimize(), HMWSoln::calc_lambdas(), InterfaceKinetics::checkPartialEquil(), ChemEquil::dampStep(), Cantera::ElemRearrange(), ChemEquil::equilibrate(), ChemEquil::equilResidual(), ChemEquil::estimateElementPotentials(), ChemEquil::estimateEP_Brinkley(), SquareMatrix::factor(), SquareMatrix::factorQR(), GasTransport::fitProperties(), MMCollisionInt::init(), Cantera::invert(), solveSP::print_header(), HMWSoln::printCoeffs(), solveSP::printIteration(), RootFind::printTable(), SquareMatrix::rcond(), SquareMatrix::rcondQR(), HMWSoln::s_updatePitzer_d2lnMolalityActCoeff_dT2(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dP(), HMWSoln::s_updatePitzer_dlnMolalityActCoeff_dT(), HMWSoln::s_updatePitzer_lnMolalityActCoeff(), ChemEquil::setInitialMoles(), SquareMatrix::solve(), Cantera::solve(), RootFind::solve(), SquareMatrix::solveQR(), solveSP::solveSurfProb(), VCS_SOLVE::vcs_deltag(), VCS_SOLVE::vcs_printSpeciesChemPot(), and ResidEval::writeSolution().